[package]
name = "base-shadow-metrics"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
base-shadow-indexer-db.workspace = true
anyhow = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "tls-native-tls"] }
