[package]
name = "base-shadow-metrics"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tracing.workspace = true
base-metrics.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
base-shadow-indexer-db.workspace = true
base-common-consensus = { workspace = true, features = ["reth"] }
serde = { workspace = true, features = ["derive"] }
axum = { workspace = true, features = ["json", "query"] }
tower-http = { workspace = true, features = ["cors"] }
metrics = { workspace = true, optional = true }
anyhow = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["time"] }
thiserror = { workspace = true, features = ["std"] }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "tls-native-tls"] }

[dev-dependencies]
chrono.workspace = true
reth-primitives-traits.workspace = true

[features]
default = [ "metrics" ]
metrics = [ "base-metrics/metrics", "dep:metrics" ]
