[package]
name = "base-common-evm2"
description = "Base EVM2 execution type family (scaffold)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# base
base-common-consensus.workspace = true

# evm2
evm2 = { workspace = true, features = ["std"] }

# alloy
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
