{
 "title": "OP Succinct Lite Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Game Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Game Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "op_succinct_fp_finalized_l2_block_number",
     "legendFormat": "Finalized L2 Block Number"
    },
    {
     "expr": "op_succinct_fp_latest_game_l2_block_number",
     "legendFormat": "Latest proposed L2 Block Number"
    },
    {
     "expr": "op_succinct_fp_anchor_game_l2_block_number",
     "legendFormat": "Anchor Game L2 Block Number"
    }
   ]
  },
  {
   "title": "L2 Finalized Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{__name__=\"op_succinct_fp_finalized_l2_block_number\"} - {__name__=\"op_succinct_fp_latest_game_l2_block_number\"}",
     "legendFormat": "Finalized L2 Block Number - Latest proposed L2 Block Number"
    }
   ]
  },
  {
   "title": "Proposer Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "op_succinct_fp_games_created", "legendFormat": "Number of Games Created" },
    {
     "expr": "op_succinct_fp_games_resolved{job=\"proposer\"}",
     "legendFormat": "Number of Games Resolved"
    },
    {
     "expr": "op_succinct_fp_games_bonds_claimed",
     "legendFormat": "Number of Games Bonds Claimed"
    }
   ]
  },
  {
   "title": "Number of Invalid State Roots Proposed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "op_succinct_fp_challenger_games_challenged",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "op_succinct_fp_errors", "legendFormat": "__auto" },
    {
     "expr": "op_succinct_fp_challenger_errors",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}