[package]
name = "base-node-runner"
description = "Primitive types and traits for Base node runner extensions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-exex = { workspace = true }
reth-provider = { workspace = true }
tracing = { workspace = true, features = ["std"] }
reth-tasks = { workspace = true, optional = true }
eyre = { workspace = true, features = ["default"] }
reth-network = { workspace = true, optional = true }
reth-db = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
reth-node-core = { workspace = true, optional = true }
base-test-utils = { workspace = true, optional = true }
alloy-primitives = { workspace = true, optional = true }
reth-primitives-traits = { workspace = true, optional = true}
base-node-core = { workspace = true, features = ["default"] }
base-execution-payload-types = { workspace = true, optional = true}
base-common-rpc-types-engine = { workspace = true, optional = true }
base-execution-txpool = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default"], optional = true }
alloy-eips = { workspace = true, features = ["std"], optional = true }
alloy-genesis = { workspace = true, features = ["std"], optional = true }
base-execution-payload-builder = { workspace = true, features = ["default"] }
alloy-provider = { workspace = true, optional = true, features = ["default"] }
alloy-rpc-types = { workspace = true, optional = true, features = ["default"] }
alloy-rpc-client = { workspace = true, optional = true, features = ["default"] }
alloy-rpc-types-engine = { workspace = true, features = ["std"], optional = true }
tracing-subscriber = { workspace = true, optional = true, features = ["default"] }
base-execution-chainspec = { workspace = true, features = ["default"], optional = true }
base-common-rpc-types = { workspace = true, optional = true, features = ["default", "network"] }

[dependencies.base-node-context]
workspace = true
[dev-dependencies]
serde_json = { workspace = true }
base-protocol = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["default"] }
base-node-runner = { workspace = true, features = ["test-utils"] }
criterion = { workspace = true, features = ["default", "async_tokio", "html_reports"] }
[[bench]]
name = "fcu_unsafe"
harness = false

[features]
test-utils = [
    "dep:base-execution-chainspec",
    "dep:reth-network",
    "dep:tokio",
    "base-node-core/test-utils",
    "dep:alloy-eips",
    "dep:alloy-genesis",
    "dep:alloy-primitives",
    "dep:alloy-provider",
    "dep:alloy-rpc-client",
    "dep:alloy-rpc-types",
    "dep:alloy-rpc-types-engine",
    "dep:base-common-rpc-types",
    "dep:base-common-rpc-types",
    "dep:base-common-rpc-types-engine",
    "dep:base-test-utils",
    "dep:reth-node-core",
    "dep:reth-tasks",
    "dep:tracing-subscriber",
    "reth-db/test-utils",
    "base-node-core/test-utils",
    "reth-primitives-traits/test-utils",
    "reth-provider/test-utils",
    "reth-tasks?/test-utils",
    "dep:reth-primitives-traits",
    "dep:base-execution-payload-types",
]
