[package]
name = "base-node-runner"
description = "Primitive types and traits for Base node runner extensions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
eyre = { workspace = true, features = ["default"] }
base-execution-state-provider = { workspace = true }
base-metering = { workspace = true, optional = true }
base-node-config = { workspace = true, optional = true }
alloy-primitives = { workspace = true, optional = true }
base-tx-forwarding = { workspace = true, optional = true }
base-testing-support = { workspace = true, optional = true }
base-node-core = { workspace = true, features = ["default"] }
reth-primitives-traits = { workspace = true, optional = true}
base-common-types-chain = { workspace = true, optional = true }
base-common-runtime-tasks = { workspace = true, optional = true }
base-consensus-batch-types = { workspace = true, optional = true }
base-execution-engine-driver = {workspace = true, optional = true}
base-execution-evm-runtime = { workspace = true, optional = true }
base-execution-payload-types = { workspace = true, optional = true}
base-execution-rpc-handlers = { workspace = true, optional = true }
tokio = { workspace = true, features = ["default"], optional = true }
alloy-eips = { workspace = true, features = ["std"], optional = true }
base-execution-network-service = { workspace = true, optional = true }
alloy-genesis = { workspace = true, features = ["std"], optional = true }
base-common-client-ethereum = {workspace = true,  features = ["default"]}
base-execution-state-database = { workspace = true, features = ["default"] }
base-execution-payload-builder = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, optional = true, features = ["default"] }
base-common-chain-config = {optional = true, features = ["std"], workspace = true}
tracing-subscriber = { workspace = true, optional = true, features = ["default"] }
base-common-types-payload = {workspace = true, optional = true, features = ["std"]}
base-common-types-rpc = { workspace = true, optional = true, features = ["serde", "std"] }

[dev-dependencies]
serde_json = { workspace = true }
base-consensus-batch-types = { workspace = true }
base-execution-engine-driver = {workspace = true}
futures = { workspace = true, features = ["default"] }
tokio-tungstenite = { workspace = true, features = ["default"] }
base-node-runner = { workspace = true, features = ["test-utils"] }
criterion = { workspace = true, features = ["default", "async_tokio", "html_reports"] }

[[bench]]
name = "fcu_unsafe"
harness = false

[features]
test-utils = [
    "dep:base-tx-forwarding",
    "dep:base-execution-rpc-handlers",
    "dep:base-metering",
    "dep:base-common-chain-config",
    "dep:base-common-types-chain",
    "dep:base-execution-evm-runtime",
    "dep:base-consensus-batch-types",
    "dep:base-execution-network-service",
    "dep:tokio",
    "base-node-core/test-utils",
    "dep:alloy-eips",
    "dep:alloy-genesis",
    "dep:alloy-primitives",
    "dep:alloy-rpc-client",
    "dep:base-common-types-rpc",
    "dep:base-common-types-payload",
    "dep:base-testing-support",
    "dep:base-node-config",
    "dep:base-common-runtime-tasks",
    "dep:tracing-subscriber",
    "base-execution-state-database/test-utils",
    "reth-primitives-traits/test-utils",
    "base-execution-state-provider/test-utils",
    "base-common-runtime-tasks?/test-utils",
    "dep:reth-primitives-traits",
    "dep:base-execution-payload-types",
    "dep:base-execution-engine-driver",
]
