[package]
name = "base-prover-service"
description = "Base prover service JSON-RPC definitions and server implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
metrics = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
base-prover-service-db = { workspace = true }
jsonrpsee = { workspace = true, optional = true }
anyhow = { workspace = true, features = ["default"] }
uuid = { workspace = true, features = ["default", "v4"] }
base-proof-service-protocol = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread", "sync", "time"] }
[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
chrono = { workspace = true, features = ["default"] }
jsonrpsee = { workspace = true, features = ["http-client"] }
metrics-util = { workspace = true, features = ["debugging"] }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio"] }
base-proof-service-protocol = { workspace = true, features = ["default", "rpc-client"] }
[lints]
workspace = true

[features]
default = [ "rpc-server" ]
rpc-server = [
	"base-proof-service-protocol/rpc-server",
	"dep:jsonrpsee",
	"jsonrpsee/server",
]
