[package]
name = "base-execution-payload-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
serde = { workspace = true }
either = { workspace = true }
thiserror = { workspace = true }
auto_impl = { workspace = true }
alloy-eips = { workspace = true }
base-evm-handler = {workspace = true}
alloy-hardforks = { workspace = true }
alloy-consensus = { workspace = true }
reth-trie-common = { workspace = true }
reth-storage-errors = {workspace = true}
reth-execution-types = { workspace = true }
reth-primitives-traits = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
pin-project = { workspace = true, optional = true}
alloy-rlp = { workspace = true, features = ["core-net"] }
base-common-consensus = { workspace = true, features = ["reth"] }
alloy-rpc-types-engine = { workspace = true, features = ["serde"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"] }
base-common-rpc-types-engine = { workspace = true, features = ["serde"] }
tracing = { workspace = true, features = ["attributes"], optional = true}
tokio-stream = { workspace = true, features = ["default", "sync"], optional = true}
[dev-dependencies]
assert_matches = { workspace = true }
base-common-genesis = { workspace = true }
base-execution-chainspec = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
    "base-common-rpc-types-engine/std",
    "reth-execution-types/std",
    "reth-trie-common/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rpc-types-engine/std",
    "serde/std",
    "thiserror/std",
    "reth-primitives-traits/std",
    "either/std",
    "alloy-consensus/std",
    "alloy-rlp/std",
    "serde_json/std",
    "sha2/std",
    "dep:pin-project",
    "dep:tracing",
    "dep:tokio-stream",
]
