//! Generated EntryPoint simulation bytecode
//!
//! This module includes the compiled bytecode for EntryPoint/EntryPointSimulations contracts.
//! The bytecode is generated at compile time by build.rs from the Solidity sources
//! in `contracts/solidity/`.
//!
//! # Version differences
//!
//! - **v0.6**: `simulateHandleOp` is built into EntryPoint.sol
//! - **v0.7+**: `simulateHandleOp` is in a separate EntryPointSimulations.sol
//!
//! # Building with bytecode
//!
//! The contracts are included as git submodules. To compile:
//!
//! ```sh
//! cd contracts/solidity/v0_6 && forge build
//! cd contracts/solidity/v0_7 && forge build
//! cd contracts/solidity/v0_8 && forge build
//! cd contracts/solidity/v0_9 && forge build
//! ```
//!
//! Then rebuild the crate:
//! ```sh
//! cargo build -p base-account-abstraction
//! ```

// Include the generated bytecode module
include!(concat!(env!("OUT_DIR"), "/entrypoint_bytecode.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bytecode_constants_exist() {
        // These should at least be defined (may be empty if contracts not compiled)
        let _ = ENTRYPOINT_V06_SIMULATIONS_DEPLOYED_BYTECODE;
        let _ = ENTRYPOINT_V07_SIMULATIONS_DEPLOYED_BYTECODE;
        let _ = ENTRYPOINT_V08_SIMULATIONS_DEPLOYED_BYTECODE;
        let _ = ENTRYPOINT_V09_SIMULATIONS_DEPLOYED_BYTECODE;

        // Verify they have content
        assert!(has_v06_bytecode(), "v0.6 bytecode should be available");
        assert!(has_v07_bytecode(), "v0.7 bytecode should be available");
        assert!(has_v08_bytecode(), "v0.8 bytecode should be available");
        assert!(has_v09_bytecode(), "v0.9 bytecode should be available");
    }
}

