[package]
name = "base-common-client-contracts"
description = "Interact with on-chain contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
build = false
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--show-type-layout",
]

[lib]
name = "base_common_client_contracts"
path = "src/lib.rs"

[dependencies]
thiserror = { workspace = true }
alloy-json-abi = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-transport = { workspace = true }
base-common-types-chain = { workspace = true }
base-common-client-ethereum = {workspace = true}
alloy-pubsub = { workspace = true, optional = true }
futures = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["default"] }
alloy-dyn-abi = { workspace = true, features = ["std"] }
alloy-primitives = { workspace = true, features = ["map"] }
futures-util = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, features = ["serde"] }
serde_json = { workspace = true, features = [
    "alloc",
    "raw_value",
] }

[dev-dependencies]
alloy-node-bindings = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
tracing-subscriber = { workspace = true, features = ["default"] }
base-common-client-ethereum = {workspace = true, features = ["anvil-node", "ws"]}
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread"] }

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
wasmtimer = { workspace = true, features = ["default"] }
[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
tokio = { workspace = true, features = ["default", "time"] }
[lints]
workspace = true

[features]
pubsub = ["base-common-client-ethereum/pubsub", "dep:alloy-pubsub"]
