[package]
name = "base-common-network"
description = "Base blockchain RPC behavior abstraction"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
alloy-network = { workspace = true }
alloy-transport = { workspace = true }
alloy-primitives = { workspace = true }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["default"] }
base-common-rpc-types-engine = { workspace = true, features = ["serde"] }
alloy-rpc-types-engine = { workspace = true, features = ["serde", "std"] }
base-common-rpc-types = { workspace = true, features = ["default", "network"] }
base-common-consensus = { workspace = true, features = ["alloy-compat", "std"] }
[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
[features]
std = [
	"alloy-consensus/std",
	"alloy-primitives/std",
	"alloy-rpc-types-engine/std",
	"base-common-consensus/std",
	"base-common-rpc-types-engine/std",
	"base-common-rpc-types/std",
]
serde = [
	"alloy-consensus/serde",
	"alloy-primitives/serde",
	"alloy-rpc-types-engine/serde",
	"base-common-consensus/serde",
	"base-common-rpc-types-engine/serde",
	"base-common-rpc-types/serde",
]
reth = [ "base-common-rpc-types/reth", "std" ]
