[package]
name = "base-common-network"
description = "Remote transaction signer for EthereumWallet integration via eth_signTransaction"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
alloy-signer = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
tracing = { workspace = true, features = ["std"] }
url = { workspace = true, features = ["default"] }
coins-bip32 = { workspace = true, optional = true }
thiserror = { workspace = true, features = ["std"] }
rand_08 = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map"]}
alloy-eips = { workspace = true, features = ["std", "serde"] }
jsonrpsee = { workspace = true, features = ["http-client", "macros"] }
alloy-rpc-types-eth = { workspace = true, features = ["std", "serde"] }
coins-bip39 = { workspace = true, features = ["english"], optional = true }
zeroize = { workspace = true, features = [
    "zeroize_derive",
    "alloc",
], optional = true }
auto_impl = { workspace = true }
alloy-serde = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-rpc-types-any = { workspace = true }
alloy-network-primitives = { workspace = true }
derive_more = { workspace = true, features = ["from"] }
serde_json = { workspace = true, features = ["alloc"] }
futures-utils-wasm = { workspace = true, features = ["default"] }
serde = { workspace = true, features = [
    "derive",
    "alloc",
] }
alloy-consensus-any = { workspace = true, features = [
    "std",
    "serde",
] }
base-common-consensus = {workspace = true, features = ["serde", "std"]}
[dev-dependencies]
alloy-node-bindings = { workspace = true }
tempfile = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread"] }
serde = { workspace = true, features = [
    "derive",
    "alloc",
] }
base-common-consensus = { workspace = true, features = ["std"] }

[features]
mnemonic = ["dep:coins-bip32", "dep:coins-bip39", "zeroize"]
zeroize = ["dep:zeroize"]
k256 = [
    "alloy-primitives/k256",
    "base-common-consensus/k256",
    "alloy-eips/k256",
    "alloy-rpc-types-eth/k256",
]
