[package]
name = "base-common-network"
description = "Base blockchain RPC behavior abstraction"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-common-rpc-types = { workspace = true, features = ["network"] }
base-common-rpc-types-engine = { workspace = true, features = ["serde"] }
base-common-consensus = { workspace = true, features = ["alloy-compat", "std"] }

# Alloy
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
alloy-rpc-client.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["serde", "std"] }
alloy-consensus = { workspace = true, features = ["std"] }

# misc
thiserror.workspace = true
async-trait.workspace = true


[dev-dependencies]
url.workspace = true
rstest.workspace = true
httpmock.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
std = [
	"alloy-consensus/std",
	"alloy-primitives/std",
	"alloy-rpc-types-engine/std",
	"base-common-consensus/std",
	"base-common-rpc-types-engine/std",
	"base-common-rpc-types/std",
]
serde = [
	"alloy-consensus/serde",
	"alloy-primitives/serde",
	"alloy-rpc-types-engine/serde",
	"base-common-consensus/serde",
	"base-common-rpc-types-engine/serde",
	"base-common-rpc-types/serde",
]
reth = [ "base-common-rpc-types/reth", "std" ]
