[package]
name = "base-proof-tee-nitro-enclave"
description = "Nitro Enclave runtime, types, and proving logic."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
alloy-chains = { workspace = true }
alloy-signer = { workspace = true }
alloy-primitives = { workspace = true }
base-execution-evm-runtime = { workspace = true }
base-common-client-ethereum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
base-proof = { workspace = true, features = ["std"] }
rand_08 = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true, features = ["default"] }
base-proof-client = { workspace = true, features = ["std"] }
bincode = { workspace = true, features = ["default", "serde"] }
base-proof-witness-preimage = { workspace = true, features = ["serde"] }
base-proof-types-protocol = { workspace = true, features = ["serde"] }
aws-nitro-enclaves-nsm-api = { workspace = true, features = ["default"] }
k256 = { workspace = true, features = ["default", "ecdsa", "arithmetic"] }
tokio = { workspace = true, features = ["default", "rt", "time", "io-util"] }
base-common-chain-config = {workspace = true, features = ["default", "serde"]}

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = { workspace = true }
eyre = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "rt-multi-thread"] }
[dev-dependencies]
serde_json = { workspace = true }
hex = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "macros", "rt"] }

[package.metadata.cargo-udeps.ignore]
normal = ["aws-nitro-enclaves-nsm-api"]
