[package]
name = "base-common-codec-storage"
description = "Commonly used zstd compressors."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
build = false
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
readme = "README.md"

[lib]
name = "base_common_codec_storage"
path = "src/lib.rs"

[dependencies]
zstd = { workspace = true, features = ["default", "experimental"] }

[lints]
workspace = true

[features]
default = ["std"]
std = []
