use std::{fmt, path::Path, time::Duration};

use alloy_primitives::{Address, U256};
use alloy_signer_local::PrivateKeySigner;
use serde::{Deserialize, Deserializer, Serialize, de::Error as SerdeError};
use url::Url;

use super::{
    parsing::validate_swap_amounts,
    precompile::PrecompileTarget,
    real_token::{RealTokenSetupConfig, parse_real_token_setup},
    validity::ValidityConfig,
};
use crate::{
    metrics::ConfigSummary,
    rpc::MAX_BATCH_RPC_SIZE,
    runner::{TxConfig, TxType},
    utils::{BaselineError, Result},
    workload::RealTokenSetup,
};

/// Configuration for a load test, loadable from YAML.
#[derive(Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct TestConfig {
    /// HTTP JSON-RPC endpoints used for transaction submission.
    ///
    /// The first URL is also used for setup transactions such as funding, token distribution, and
    /// draining. A single scalar URL is accepted as a one-entry list.
    #[serde(default, deserialize_with = "deserialize_url_list")]
    pub transaction_submission_rpcs: Vec<Url>,
    /// HTTP JSON-RPC endpoint used for read/query operations.
    ///
    /// Defaults to the first entry in [`Self::transaction_submission_rpcs`] when omitted.
    #[serde(default)]
    pub query_rpc: Option<Url>,
    /// Optional HTTP JSON-RPC endpoints whose txpools should be cleared before a test.
    #[serde(default)]
    pub txpool_nodes: Vec<Url>,
    /// Optional legacy builder flashblocks WebSocket endpoint.
    #[serde(default)]
    pub flashblocks_ws: Option<Url>,

    /// Mnemonic phrase for deriving sender accounts.
    /// If not provided, accounts are generated from seed.
    #[serde(skip_serializing)]
    pub mnemonic: Option<String>,

    /// Amount to fund each sender account (in wei, as string).
    pub funding_amount: String,

    /// Number of sender accounts to create/use.
    pub sender_count: u32,

    /// Offset into mnemonic derivation path (skip first N accounts).
    pub sender_offset: u32,

    /// Maximum in-flight transactions per sender.
    pub in_flight_per_sender: u32,

    /// Optional ceiling on total in-flight transactions across all senders.
    ///
    /// Without this, the aggregate cap is implicitly `in_flight_per_sender *
    /// sender_count`. Set this to bound the open-loop headroom target
    /// independently of sender count, e.g. to protect a shared target node's
    /// mempool regardless of how many senders are configured. Omit for the
    /// previous per-sender-derived behavior.
    #[serde(default)]
    pub max_total_in_flight: Option<u32>,

    /// Optional cap on concurrent outbound submission RPC requests across all
    /// sender workers.
    ///
    /// Use this to throttle request *rate* to the submission endpoint(s)
    /// directly (e.g. to stay under an RPC-side rate limit), independently of
    /// `in_flight_per_sender` / `max_total_in_flight`, which bound unconfirmed
    /// transactions rather than outbound requests. Omit to leave concurrency
    /// bounded only by the sender worker count.
    #[serde(default)]
    pub max_concurrent_submit_requests: Option<u32>,

    /// Maximum number of transactions in each JSON-RPC batch request.
    #[serde(default = "default_batch_size")]
    pub batch_size: u32,

    /// Test duration (e.g., "30s", "5m", "1h").
    pub duration: Option<String>,

    /// Optional measured canonical block window size.
    pub measurement_blocks: Option<u64>,

    /// Optional gas/s target used to size each block's mempool floor.
    #[serde(default)]
    pub target_gps: Option<u64>,

    /// Expected cadence between canonical blocks (for example, "2s" or "200ms").
    #[serde(default = "default_block_time")]
    pub block_time: String,

    /// Seed for deterministic account generation (used if mnemonic not provided).
    ///
    /// Defaults to `12345` for reproducible single-run testing and fund recovery. Concurrent runs
    /// against the same chain without overriding this will derive identical
    /// accounts and collide on nonces.
    pub seed: u64,

    /// Chain ID (if not provided, fetched from RPC).
    pub chain_id: Option<u64>,

    /// Transaction types with weights.
    pub transactions: Vec<WeightedTxType>,

    /// Fraction of transactions that target a freshly derived recipient signing key generated by
    /// the same derivation kind as the sender pool (mnemonic when set, otherwise seed-based).
    /// This forces account-trie fan-out for payloads that honor the runner-supplied `to` address.
    ///
    /// The recipient stream is always positioned with a runtime-random seed/offset (never the
    /// configured `seed`), so repeated runs never regenerate the same "fresh" addresses. The
    /// runner prints recovery instructions directly at startup and writes
    /// `fresh_recipient_count` to the final summary.
    #[serde(default)]
    pub fresh_recipient_ratio: f64,

    /// Address of the precompile looper contract (required when using iterations > 1).
    #[serde(default)]
    pub looper_contract: Option<Address>,

    /// Amount of each swap token to distribute to each sender (in wei, as string).
    /// Only used when swap transaction types are configured.
    #[serde(default = "default_swap_token_amount")]
    pub swap_token_amount: String,

    /// Amount of B-20 tokens to mint per sender during setup (in wei, as string).
    /// Only used when B-20 transaction types are configured.
    #[serde(default = "default_b20_mint_amount")]
    pub b20_mint_amount: String,

    /// Optional real-token setup for mainnet-snapshot bidirectional swap workloads.
    #[serde(default)]
    pub real_token_setup: Option<RealTokenSetupConfig>,

    /// Skip draining native ETH balances back to the funder account after the run.
    ///
    /// Useful for harness-driven runs (e.g. via `base-bench`) that only ever pass a
    /// config file path with no CLI flags, since funder accounts are cheaply
    /// re-funded via deposit rather than reclaimed.
    #[serde(default)]
    pub skip_drain: bool,

    /// Validity (conditional) transaction workload. When `ratio` is `0.0`
    /// (the default), no validity transactions are submitted.
    #[serde(default)]
    pub validity: ValidityConfig,
}

impl Default for TestConfig {
    fn default() -> Self {
        Self {
            transaction_submission_rpcs: vec![
                Url::parse("http://localhost:8545").expect("valid URL"),
            ],
            query_rpc: None,
            txpool_nodes: Vec::new(),
            flashblocks_ws: None,
            mnemonic: None,
            funding_amount: "10000000000000000".to_string(),
            sender_count: 100,
            sender_offset: 0,
            in_flight_per_sender: 16,
            max_total_in_flight: None,
            max_concurrent_submit_requests: None,
            batch_size: default_batch_size(),
            duration: Some("60s".to_string()),
            measurement_blocks: None,
            target_gps: Some(20_000_000),
            block_time: default_block_time(),
            seed: 12345,
            chain_id: None,
            transactions: vec![WeightedTxType { weight: 100, tx_type: TxTypeConfig::Transfer }],
            fresh_recipient_ratio: 0.0,
            looper_contract: None,
            swap_token_amount: default_swap_token_amount(),
            b20_mint_amount: default_b20_mint_amount(),
            real_token_setup: None,
            skip_drain: false,
            validity: ValidityConfig::default(),
        }
    }
}

impl fmt::Debug for TestConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TestConfig")
            .field("transaction_submission_rpcs", &self.transaction_submission_rpcs)
            .field("query_rpc", &self.query_rpc)
            .field("txpool_nodes", &self.txpool_nodes)
            .field("flashblocks_ws", &self.flashblocks_ws)
            .field("mnemonic", &self.mnemonic.as_ref().map(|_| "[REDACTED]"))
            .field("funding_amount", &self.funding_amount)
            .field("sender_count", &self.sender_count)
            .field("sender_offset", &self.sender_offset)
            .field("in_flight_per_sender", &self.in_flight_per_sender)
            .field("max_total_in_flight", &self.max_total_in_flight)
            .field("max_concurrent_submit_requests", &self.max_concurrent_submit_requests)
            .field("batch_size", &self.batch_size)
            .field("duration", &self.duration)
            .field("measurement_blocks", &self.measurement_blocks)
            .field("target_gps", &self.target_gps)
            .field("block_time", &self.block_time)
            .field("seed", &self.seed)
            .field("chain_id", &self.chain_id)
            .field("transactions", &self.transactions)
            .field("fresh_recipient_ratio", &self.fresh_recipient_ratio)
            .field("looper_contract", &self.looper_contract)
            .field("swap_token_amount", &self.swap_token_amount)
            .field("b20_mint_amount", &self.b20_mint_amount)
            .field("real_token_setup", &self.real_token_setup)
            .field("skip_drain", &self.skip_drain)
            .field("validity", &self.validity)
            .finish()
    }
}

/// A transaction type with its weight in the mix.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WeightedTxType {
    /// Weight for random selection (higher = more frequent).
    pub weight: u32,

    /// The transaction type configuration.
    #[serde(flatten)]
    pub tx_type: TxTypeConfig,
}

/// Osaka (Base Azul) transaction target.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OsakaTarget {
    /// CLZ opcode (EIP-7939): COUNT LEADING ZEROS — CREATE transaction with CLZ initcode.
    Clz,
    /// P256VERIFY precompile at 0x0100 with Osaka gas pricing 6 900 (EIP-7951).
    #[serde(rename = "p256verify_osaka")]
    P256verifyOsaka,
    /// MODEXP under Osaka rules: 1 024-byte field limit + min gas 500 (EIP-7823 + EIP-7883).
    ModexpOsaka,
}

/// Transaction type configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum TxTypeConfig {
    /// Simple ETH transfer.
    Transfer,

    /// ETH transfer with random calldata.
    Calldata {
        /// Maximum calldata size in bytes.
        #[serde(default = "default_calldata_size")]
        max_size: usize,
        /// Number of times to repeat the random sequence for compressibility.
        #[serde(default = "default_repeat_count")]
        repeat_count: usize,
    },

    /// ERC20 token transfer (requires deployed contract).
    Erc20 {
        /// ERC20 contract address.
        contract: Address,
    },

    /// Storage-heavy contract write (requires deployed contract).
    Storage {
        /// Storage-writer contract address.
        contract: Address,
        /// Number of storage slots to write per transaction.
        #[serde(default = "default_storage_slots_per_tx")]
        slots_per_tx: u32,
    },

    /// Deterministic `DoubleCounter` `increment()` call.
    DoubleCounter {
        /// `DoubleCounter` contract address.
        contract: Address,
    },

    /// Precompile call.
    Precompile {
        /// Target precompile configuration.
        #[serde(flatten)]
        target: PrecompileTarget,
        /// Number of iterations per transaction. Requires `looper_contract` when > 1.
        #[serde(default = "default_iterations")]
        iterations: u32,
    },

    /// Osaka (Base Azul) opcode or precompile transaction.
    Osaka {
        /// Target Osaka feature.
        target: OsakaTarget,
    },
    /// Uniswap V3 style swap.
    UniswapV3 {
        /// Router contract address.
        router: Address,
        /// Input token address.
        token_in: Address,
        /// Output token address.
        token_out: Address,
        /// Fee tier (default 3000 = 0.3%).
        #[serde(default = "default_uniswap_v3_fee")]
        fee: u32,
        /// Minimum swap amount in wei.
        #[serde(default = "default_swap_min_amount")]
        min_amount: U256,
        /// Maximum swap amount in wei.
        #[serde(default = "default_swap_max_amount")]
        max_amount: U256,
        /// Minimum amount when swapping `token_out` to `token_in`.
        #[serde(default)]
        reverse_min_amount: Option<U256>,
        /// Maximum amount when swapping `token_out` to `token_in`.
        #[serde(default)]
        reverse_max_amount: Option<U256>,
    },
    /// B-20 precompile token transfer. Each sender creates and transfers its own token, created
    /// per run during setup.
    B20,

    /// Aerodrome Slipstream (concentrated liquidity) swap.
    AerodromeCl {
        /// CL Router contract address.
        router: Address,
        /// Input token address.
        token_in: Address,
        /// Output token address.
        token_out: Address,
        /// Tick spacing for the pool.
        #[serde(default = "default_aerodrome_tick_spacing")]
        tick_spacing: i32,
        /// Minimum swap amount in wei.
        #[serde(default = "default_swap_min_amount")]
        min_amount: U256,
        /// Maximum swap amount in wei.
        #[serde(default = "default_swap_max_amount")]
        max_amount: U256,
        /// Minimum amount when swapping `token_out` to `token_in`.
        #[serde(default)]
        reverse_min_amount: Option<U256>,
        /// Maximum amount when swapping `token_out` to `token_in`.
        #[serde(default)]
        reverse_max_amount: Option<U256>,
    },
}

const fn default_calldata_size() -> usize {
    128
}

const fn default_repeat_count() -> usize {
    1
}

const fn default_iterations() -> u32 {
    1
}

const fn default_storage_slots_per_tx() -> u32 {
    10
}

/// Upper bound on `slots_per_tx` so the payload's gas limit
/// (`slots_per_tx * 23_000 + 30_000`) stays under the ~30M per-tx block cap.
/// Target RPCs may enforce a lower per-tx ceiling; tune `slots_per_tx` to fit.
const MAX_STORAGE_SLOTS_PER_TX: u32 = 1_300;

fn default_swap_min_amount() -> U256 {
    U256::from(1_000_000_000_000_000u64)
}

fn default_swap_max_amount() -> U256 {
    U256::from(10_000_000_000_000_000u64)
}

const fn default_uniswap_v3_fee() -> u32 {
    3000
}

const fn default_aerodrome_tick_spacing() -> i32 {
    100
}

fn default_block_time() -> String {
    "2s".to_string()
}

const fn default_batch_size() -> u32 {
    MAX_BATCH_RPC_SIZE as u32
}

fn default_swap_token_amount() -> String {
    "1000000000000000000000".to_string() // 1000 tokens (1000e18)
}

fn default_b20_mint_amount() -> String {
    "1000000000000000000000".to_string() // 1000 tokens (1000e18)
}

impl TestConfig {
    /// Loads configuration from a YAML file.
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self> {
        let path = path.as_ref();
        let contents = std::fs::read_to_string(path).map_err(|e| {
            BaselineError::Config(format!("failed to read config file {}: {}", path.display(), e))
        })?;
        Self::from_yaml(&contents)
    }

    /// Parses configuration from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self> {
        let config: Self = serde_yaml::from_str(yaml)
            .map_err(|e| BaselineError::Config(format!("failed to parse YAML: {e}")))?;
        config.validate()?;
        Ok(config)
    }

    /// Validates that all required fields are set and values are sensible.
    pub fn validate(&self) -> Result<()> {
        if self.sender_count == 0 {
            return Err(BaselineError::Config("sender_count must be > 0".into()));
        }
        if self.in_flight_per_sender == 0 {
            return Err(BaselineError::Config("in_flight_per_sender must be > 0".into()));
        }
        if self.batch_size == 0 {
            return Err(BaselineError::Config("batch_size must be > 0".into()));
        }
        if self.parse_duration()? == Some(Duration::ZERO) {
            return Err(BaselineError::Config(
                "duration must be > 0 (or omit for continuous)".into(),
            ));
        }
        if self.measurement_blocks == Some(0) {
            return Err(BaselineError::Config("measurement_blocks must be > 0 when set".into()));
        }

        if self.transaction_submission_rpcs.is_empty() {
            return Err(BaselineError::Config(
                "transaction_submission_rpcs must not be empty".into(),
            ));
        }
        for url in &self.transaction_submission_rpcs {
            Self::validate_http_url(url, "transaction_submission_rpcs")?;
        }

        if let Some(url) = &self.query_rpc {
            Self::validate_http_url(url, "query_rpc")?;
        }
        for url in &self.txpool_nodes {
            Self::validate_http_url(url, "txpool_nodes")?;
        }

        if let Some(flashblocks_ws) = &self.flashblocks_ws {
            Self::validate_ws_url(flashblocks_ws, "flashblocks_ws")?;
        }

        if !(0.0..=1.0).contains(&self.fresh_recipient_ratio) {
            return Err(BaselineError::Config(
                "fresh_recipient_ratio must be between 0.0 and 1.0".into(),
            ));
        }
        if self.parse_block_time()?.is_zero() {
            return Err(BaselineError::Config("block_time must be > 0".into()));
        }

        self.validity.validate()?;

        Ok(())
    }

    /// Returns the first transaction submission endpoint.
    pub fn primary_submission_rpc(&self) -> Result<&Url> {
        self.transaction_submission_rpcs.first().ok_or_else(|| {
            BaselineError::Config("transaction_submission_rpcs must not be empty".into())
        })
    }

    fn validate_http_url(url: &Url, field_name: &str) -> Result<()> {
        match url.scheme() {
            "http" | "https" => Ok(()),
            "ws" => Err(BaselineError::Config(format!(
                "{field_name} uses 'ws://' scheme but requires 'http://' for JSON-RPC requests"
            ))),
            "wss" => Err(BaselineError::Config(format!(
                "{field_name} uses 'wss://' scheme but requires 'https://' for JSON-RPC requests"
            ))),
            scheme => Err(BaselineError::Config(format!(
                "{field_name} has invalid scheme '{scheme}', expected 'http://' or 'https://'"
            ))),
        }
    }

    fn validate_ws_url(url: &Url, field_name: &str) -> Result<()> {
        match url.scheme() {
            "ws" | "wss" => Ok(()),
            "http" => Err(BaselineError::Config(format!(
                "{field_name} uses 'http://' scheme but requires 'ws://' for WebSocket connections"
            ))),
            "https" => Err(BaselineError::Config(format!(
                "{field_name} uses 'https://' scheme but requires 'wss://' for secure WebSocket connections"
            ))),
            scheme => Err(BaselineError::Config(format!(
                "{field_name} has invalid scheme '{scheme}', expected 'ws://' or 'wss://'"
            ))),
        }
    }

    /// Returns the funder key from the `FUNDER_KEY` environment variable.
    pub fn funder_key() -> Result<PrivateKeySigner> {
        Self::resolve_funder_key(None)
    }

    /// Resolves the funder key from an explicit override string, falling back to the
    /// `FUNDER_KEY` environment variable when no override is provided.
    pub fn resolve_funder_key(override_key: Option<&str>) -> Result<PrivateKeySigner> {
        let key_str = if let Some(s) = override_key {
            s.to_string()
        } else {
            std::env::var("FUNDER_KEY").map_err(|_| {
                BaselineError::Config("FUNDER_KEY environment variable is required".into())
            })?
        };
        key_str.parse().map_err(|e| {
            BaselineError::Config(format!("invalid funder key (expected 0x-prefixed hex): {e}"))
        })
    }

    /// Returns the checksummed funder address string, if the key resolves successfully.
    ///
    /// Checks the override first, then falls back to `FUNDER_KEY` env var.
    pub fn funder_key_address(override_key: Option<&str>) -> Option<String> {
        Self::resolve_funder_key(override_key).ok().map(|s| s.address().to_string())
    }

    /// Parses the duration string into a Duration.
    pub fn parse_duration(&self) -> Result<Option<Duration>> {
        self.duration
            .as_ref()
            .map(|d| {
                humantime::parse_duration(d.trim())
                    .map_err(|e| BaselineError::Config(format!("invalid duration '{d}': {e}")))
            })
            .transpose()
    }

    /// Parses the configured canonical block cadence.
    pub fn parse_block_time(&self) -> Result<Duration> {
        humantime::parse_duration(self.block_time.trim()).map_err(|e| {
            BaselineError::Config(format!("invalid block_time '{}': {e}", self.block_time))
        })
    }

    /// Parses the funding amount string into a U256.
    pub fn parse_funding_amount(&self) -> Result<alloy_primitives::U256> {
        self.funding_amount.parse().map_err(|e| {
            BaselineError::Config(format!("invalid funding_amount '{}': {e}", self.funding_amount))
        })
    }

    /// Parses the swap token amount string into a U256.
    pub fn parse_swap_token_amount(&self) -> Result<alloy_primitives::U256> {
        self.swap_token_amount.parse().map_err(|e| {
            BaselineError::Config(format!(
                "invalid swap_token_amount '{}': {e}",
                self.swap_token_amount
            ))
        })
    }

    /// Parses the B-20 mint amount string into a U256.
    pub fn parse_b20_mint_amount(&self) -> Result<alloy_primitives::U256> {
        self.b20_mint_amount.parse().map_err(|e| {
            BaselineError::Config(format!(
                "invalid b20_mint_amount '{}': {e}",
                self.b20_mint_amount
            ))
        })
    }

    /// Parses the optional real-token setup config.
    pub fn parse_real_token_setup(&self, chain_id: u64) -> Result<Option<RealTokenSetup>> {
        parse_real_token_setup(self.real_token_setup.as_ref(), &self.transactions, chain_id)
    }

    /// Returns a summary of the config for JSON output (excludes URLs and secrets).
    pub fn to_summary(&self) -> ConfigSummary {
        ConfigSummary {
            funding_amount: self.funding_amount.clone(),
            sender_count: self.sender_count,
            sender_offset: self.sender_offset,
            in_flight_per_sender: self.in_flight_per_sender,
            max_total_in_flight: self.max_total_in_flight,
            max_concurrent_submit_requests: self.max_concurrent_submit_requests,
            batch_size: self.batch_size,
            duration: self.duration.clone(),
            measurement_blocks: self.measurement_blocks,
            target_gps: self.target_gps,
            block_time: self.block_time.clone(),
            seed: self.seed,
            chain_id: self.chain_id,
            transactions: serde_json::to_value(&self.transactions)
                .inspect_err(|e| {
                    tracing::warn!(
                        error = %e,
                        "failed to serialize transactions for config summary"
                    );
                })
                .unwrap_or_default(),
            fresh_recipient_ratio: self.fresh_recipient_ratio,
            validity_ratio: self.validity.ratio,
            validity_predicate_count: self.validity.predicates.len(),
            validity_priority_lead_ratio: self.validity.priority_lead_ratio,
            validity_priority_lead_multiplier: self.validity.priority_lead_multiplier,
            validity_priority_fee_divisor: self.validity.priority_fee_divisor,
            looper_contract: self.looper_contract.map(|addr| addr.to_string()),
            swap_token_amount: self.swap_token_amount.clone(),
            b20_mint_amount: self.b20_mint_amount.clone(),
            real_token_setup: self
                .real_token_setup
                .as_ref()
                .filter(|setup| setup.enabled)
                .and_then(|setup| {
                    serde_json::to_value(setup)
                        .inspect_err(|e| {
                            tracing::warn!(
                                error = %e,
                                "failed to serialize real-token setup for config summary"
                            );
                        })
                        .ok()
                }),
        }
    }

    /// Converts this test config into a `LoadConfig` for runtime use.
    pub fn to_load_config(
        &self,
        fallback_chain_id: Option<u64>,
    ) -> Result<crate::runner::LoadConfig> {
        let resolved_chain_id = self.chain_id.or(fallback_chain_id).ok_or_else(|| {
            BaselineError::Config("chain_id must be provided in config or fetched from RPC".into())
        })?;

        let transaction_submission_rpcs = self.transaction_submission_rpcs.clone();
        let primary_submission_rpc = self.primary_submission_rpc()?.clone();
        let query_rpc = self.query_rpc.clone().unwrap_or(primary_submission_rpc);

        let duration = self.parse_duration()?;
        let block_time = self.parse_block_time()?;

        let transactions = if self.transactions.is_empty() {
            vec![TxConfig { weight: 100, tx_type: TxType::Transfer }]
        } else {
            self.transactions.iter().map(|t| self.convert_tx_type(t)).collect::<Result<Vec<_>>>()?
        };

        Ok(crate::runner::LoadConfig {
            transaction_submission_rpcs,
            query_rpc,
            txpool_nodes: self.txpool_nodes.clone(),
            chain_id: resolved_chain_id,
            account_count: self.sender_count as usize,
            seed: self.seed,
            mnemonic: self.mnemonic.clone(),
            sender_offset: self.sender_offset as usize,
            transactions,
            target_gps: self.target_gps,
            block_gas_limit: None,
            block_time,
            separate_setup: None,
            duration,
            measurement_blocks: self.measurement_blocks,
            max_in_flight_per_sender: self.in_flight_per_sender as usize,
            max_total_in_flight: self.max_total_in_flight.map(|max| max as usize),
            max_concurrent_submit_requests: self
                .max_concurrent_submit_requests
                .map(|max| max as usize),
            batch_size: self.batch_size as usize,
            max_gas_price: crate::runner::DEFAULT_MAX_GAS_PRICE,
            flashblocks_ws: self.flashblocks_ws.clone(),
            fresh_recipient_ratio: self.fresh_recipient_ratio,
            validity_ratio: self.validity.ratio,
            validity_predicates: self.validity.to_templates()?,
            validity_priority_lead_ratio: self.validity.priority_lead_ratio,
            validity_priority_lead_multiplier: self.validity.priority_lead_multiplier,
            validity_priority_fee_divisor: self.validity.priority_fee_divisor,
        })
    }

    fn convert_tx_type(&self, weighted: &WeightedTxType) -> Result<TxConfig> {
        let tx_type = match &weighted.tx_type {
            TxTypeConfig::Transfer => TxType::Transfer,
            TxTypeConfig::Calldata { max_size, repeat_count } => {
                TxType::Calldata { max_size: *max_size, repeat_count: *repeat_count }
            }
            TxTypeConfig::Erc20 { contract } => TxType::Erc20 { contract: *contract },
            TxTypeConfig::Storage { contract, slots_per_tx } => {
                if !(1..=MAX_STORAGE_SLOTS_PER_TX).contains(slots_per_tx) {
                    return Err(BaselineError::Config(format!(
                        "storage slots_per_tx must be 1..={MAX_STORAGE_SLOTS_PER_TX}"
                    )));
                }
                TxType::Storage { contract: *contract, slots_per_tx: *slots_per_tx }
            }
            TxTypeConfig::DoubleCounter { contract } => {
                TxType::DoubleCounter { contract: *contract }
            }
            TxTypeConfig::Precompile { target, iterations } => {
                let looper_contract = if *iterations > 1 {
                    Some(self.looper_contract.ok_or_else(|| {
                        BaselineError::Config(
                            "looper_contract required when precompile iterations > 1".into(),
                        )
                    })?)
                } else {
                    None
                };
                TxType::Precompile {
                    target: target.to_precompile_id(),
                    blake2f_rounds: target.blake2f_rounds(),
                    iterations: *iterations,
                    looper_contract,
                }
            }
            TxTypeConfig::B20 => TxType::B20,
            TxTypeConfig::Osaka { target } => TxType::Osaka { target: target.clone() },
            TxTypeConfig::UniswapV3 {
                router,
                token_in,
                token_out,
                fee,
                min_amount,
                max_amount,
                reverse_min_amount,
                reverse_max_amount,
            } => {
                let max_u24: u32 = (1 << 24) - 1;
                if *fee > max_u24 {
                    return Err(BaselineError::Config(format!(
                        "uniswap_v3 fee {fee} exceeds u24 max ({max_u24})"
                    )));
                }
                validate_swap_amounts(*min_amount, *max_amount, "uniswap_v3")?;
                let reverse_min_amount = reverse_min_amount.unwrap_or(*min_amount);
                let reverse_max_amount = reverse_max_amount.unwrap_or(*max_amount);
                validate_swap_amounts(
                    reverse_min_amount,
                    reverse_max_amount,
                    "uniswap_v3 reverse",
                )?;
                TxType::UniswapV3 {
                    router: *router,
                    token_in: *token_in,
                    token_out: *token_out,
                    fee: *fee,
                    min_amount: *min_amount,
                    max_amount: *max_amount,
                    reverse_min_amount,
                    reverse_max_amount,
                }
            }
            TxTypeConfig::AerodromeCl {
                router,
                token_in,
                token_out,
                tick_spacing,
                min_amount,
                max_amount,
                reverse_min_amount,
                reverse_max_amount,
            } => {
                validate_swap_amounts(*min_amount, *max_amount, "aerodrome_cl")?;
                let reverse_min_amount = reverse_min_amount.unwrap_or(*min_amount);
                let reverse_max_amount = reverse_max_amount.unwrap_or(*max_amount);
                validate_swap_amounts(
                    reverse_min_amount,
                    reverse_max_amount,
                    "aerodrome_cl reverse",
                )?;
                if !(-8_388_608..=8_388_607).contains(tick_spacing) {
                    return Err(BaselineError::Config(format!(
                        "aerodrome_cl tick_spacing {tick_spacing} exceeds i24 range"
                    )));
                }
                TxType::AerodromeCl {
                    router: *router,
                    token_in: *token_in,
                    token_out: *token_out,
                    tick_spacing: *tick_spacing,
                    min_amount: *min_amount,
                    max_amount: *max_amount,
                    reverse_min_amount,
                    reverse_max_amount,
                }
            }
        };
        Ok(TxConfig { weight: weighted.weight, tx_type })
    }
}

/// Deserializes a URL field that may be written as either a scalar string or a list.
fn deserialize_url_list<'de, D>(deserializer: D) -> std::result::Result<Vec<Url>, D::Error>
where
    D: Deserializer<'de>,
{
    let value = serde_yaml::Value::deserialize(deserializer)?;
    match value {
        serde_yaml::Value::Null => Ok(Vec::new()),
        serde_yaml::Value::String(url) => Ok(vec![parse_url_for_serde(&url)?]),
        serde_yaml::Value::Sequence(urls) => urls
            .into_iter()
            .map(|value| match value {
                serde_yaml::Value::String(url) => parse_url_for_serde(&url),
                other => Err(D::Error::custom(format!(
                    "expected URL string in transaction_submission_rpcs, got {other:?}"
                ))),
            })
            .collect(),
        other => Err(D::Error::custom(format!(
            "expected URL string or list of URL strings, got {other:?}"
        ))),
    }
}

/// Parses a URL for serde deserialization.
fn parse_url_for_serde<E>(url: &str) -> std::result::Result<Url, E>
where
    E: SerdeError,
{
    Url::parse(url).map_err(|e| E::custom(format!("invalid URL '{url}': {e}")))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_minimal_config() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.primary_submission_rpc().unwrap().host_str(), Some("localhost"));
        assert_eq!(config.sender_count, 100);
        assert!(config.mnemonic.is_none());
        assert!(config.txpool_nodes.is_empty());
        assert_eq!(config.target_gps, None);
        assert_eq!(config.block_time, "2s");
    }

    #[test]
    fn rejects_zero_block_time() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
block_time: 0s
"#;

        let error = TestConfig::from_yaml(yaml).unwrap_err();

        assert!(error.to_string().contains("block_time must be > 0"));
    }

    #[test]
    fn parse_sharded_submission_rpcs() {
        let yaml = r#"
transaction_submission_rpcs:
  - http://localhost:7545
  - http://localhost:7546
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        let load_config = config.to_load_config(Some(1337)).unwrap();
        assert_eq!(load_config.transaction_submission_rpcs.len(), 2);
        assert_eq!(load_config.transaction_submission_rpcs[0].port(), Some(7545));
        assert_eq!(load_config.transaction_submission_rpcs[1].port(), Some(7546));
    }

    #[test]
    fn parse_txpool_nodes() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
txpool_nodes:
  - http://localhost:7545
  - http://localhost:10545
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        let load_config = config.to_load_config(Some(1337)).unwrap();
        assert_eq!(load_config.txpool_nodes.len(), 2);
        assert_eq!(load_config.txpool_nodes[0].port(), Some(7545));
        assert_eq!(load_config.txpool_nodes[1].port(), Some(10545));
    }

    #[test]
    fn parse_full_config() {
        let yaml = r#"
transaction_submission_rpcs: https://sepolia.base.org
flashblocks_ws: wss://sepolia.flashblocks.base.org/ws
mnemonic: "test test test test test test test test test test test junk"
funding_amount: "500000000000000000"
sender_count: 20
sender_offset: 5
in_flight_per_sender: 32
duration: "5m"
target_gps: 2100000
seed: 12345
transactions:
  - weight: 70
    type: transfer
  - weight: 20
    type: calldata
    max_size: 256
  - weight: 10
    type: precompile
    target: sha256
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.sender_count, 20);
        assert_eq!(config.sender_offset, 5);
        assert_eq!(config.transactions.len(), 3);

        let duration = config.parse_duration().unwrap().unwrap();
        assert_eq!(duration, Duration::from_secs(300));
    }

    #[test]
    fn parse_duration_formats() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
duration: "30s"
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.parse_duration().unwrap().unwrap(), Duration::from_secs(30));

        let yaml2 = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
duration: "1h 30m"
"#;
        let config2 = TestConfig::from_yaml(yaml2).unwrap();
        assert_eq!(config2.parse_duration().unwrap().unwrap(), Duration::from_secs(5400));
    }

    #[test]
    fn parse_measurement_blocks_round_trips() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
measurement_blocks: 500
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.measurement_blocks, Some(500));
        assert_eq!(config.to_load_config(Some(1337)).unwrap().measurement_blocks, Some(500));
        assert_eq!(config.to_summary().measurement_blocks, Some(500));
    }

    #[test]
    fn rejects_zero_measurement_blocks() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
measurement_blocks: 0
"#;
        let error = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(error.to_string().contains("measurement_blocks must be > 0 when set"));
    }

    #[test]
    fn parse_precompile_targets() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
funder_key: "0x1234"
transactions:
  - weight: 10
    type: precompile
    target: sha256
  - weight: 10
    type: precompile
    target: blake2f
  - weight: 10
    type: precompile
    target: blake2f
    rounds: 1000
  - weight: 10
    type: precompile
    target: ecrecover
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.transactions.len(), 4);

        match &config.transactions[0].tx_type {
            TxTypeConfig::Precompile { target, iterations } => {
                assert!(matches!(target, PrecompileTarget::Sha256));
                assert_eq!(*iterations, 1);
            }
            _ => panic!("expected Precompile"),
        }

        match &config.transactions[1].tx_type {
            TxTypeConfig::Precompile { target, iterations } => {
                assert!(matches!(target, PrecompileTarget::Blake2f { rounds: None }));
                assert_eq!(*iterations, 1);
            }
            _ => panic!("expected Precompile"),
        }

        match &config.transactions[2].tx_type {
            TxTypeConfig::Precompile { target, iterations } => {
                assert!(matches!(target, PrecompileTarget::Blake2f { rounds: Some(1000) }));
                assert_eq!(*iterations, 1);
            }
            _ => panic!("expected Precompile"),
        }

        match &config.transactions[3].tx_type {
            TxTypeConfig::Precompile { target, iterations } => {
                assert!(matches!(target, PrecompileTarget::Ecrecover));
                assert_eq!(*iterations, 1);
            }
            _ => panic!("expected Precompile"),
        }
    }

    #[test]
    fn parse_precompile_with_iterations() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
funder_key: "0x1234"
looper_contract: "0x1234567890123456789012345678901234567890"
transactions:
  - weight: 10
    type: precompile
    target: sha256
    iterations: 50
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.transactions.len(), 1);

        match &config.transactions[0].tx_type {
            TxTypeConfig::Precompile { target, iterations } => {
                assert!(matches!(target, PrecompileTarget::Sha256));
                assert_eq!(*iterations, 50);
            }
            _ => panic!("expected Precompile"),
        }

        assert!(config.looper_contract.is_some());
    }

    #[test]
    fn parse_storage_config() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
transactions:
  - weight: 100
    type: storage
    contract: "0x1234567890123456789012345678901234567890"
    slots_per_tx: 25
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.transactions.len(), 1);
        match &config.transactions[0].tx_type {
            TxTypeConfig::Storage { contract, slots_per_tx } => {
                assert_eq!(
                    *contract,
                    "0x1234567890123456789012345678901234567890".parse::<Address>().unwrap()
                );
                assert_eq!(*slots_per_tx, 25);
            }
            _ => panic!("expected Storage"),
        }

        let load_config = config.to_load_config(Some(1337)).unwrap();
        assert_eq!(load_config.transactions.len(), 1);
        match &load_config.transactions[0].tx_type {
            TxType::Storage { contract, slots_per_tx } => {
                assert_eq!(
                    *contract,
                    "0x1234567890123456789012345678901234567890".parse::<Address>().unwrap(),
                    "storage contract address must round-trip through conversion"
                );
                assert_eq!(*slots_per_tx, 25, "slots_per_tx must be preserved");
            }
            _ => panic!("expected TxType::Storage after conversion"),
        }
    }

    #[test]
    fn parse_storage_config_defaults_slots_per_tx() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
transactions:
  - weight: 100
    type: storage
    contract: "0x1234567890123456789012345678901234567890"
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        match &config.transactions[0].tx_type {
            TxTypeConfig::Storage { slots_per_tx, .. } => {
                assert_eq!(*slots_per_tx, 10, "slots_per_tx must default to 10");
            }
            _ => panic!("expected Storage"),
        }
    }

    #[test]
    fn storage_config_slots_per_tx_boundaries() {
        // (slots_per_tx, expect_ok): 0 and 1301 are out of range, 1300 is the accepted max.
        let cases = [
            (0u32, false),
            (MAX_STORAGE_SLOTS_PER_TX, true),
            (MAX_STORAGE_SLOTS_PER_TX + 1, false),
        ];

        for (slots_per_tx, expect_ok) in cases {
            let yaml = format!(
                r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
transactions:
  - weight: 100
    type: storage
    contract: "0x1234567890123456789012345678901234567890"
    slots_per_tx: {slots_per_tx}
"#
            );
            let config = TestConfig::from_yaml(&yaml).unwrap();
            let result = config.to_load_config(Some(1337));

            if expect_ok {
                let load_config = result.unwrap_or_else(|e| {
                    panic!("slots_per_tx {slots_per_tx} must be accepted, got: {e}")
                });
                match &load_config.transactions[0].tx_type {
                    TxType::Storage { slots_per_tx: parsed, .. } => {
                        assert_eq!(
                            *parsed, slots_per_tx,
                            "slots_per_tx {slots_per_tx} must be preserved"
                        );
                    }
                    _ => panic!("expected TxType::Storage for slots_per_tx {slots_per_tx}"),
                }
            } else {
                let err = result.unwrap_err();
                assert!(
                    err.to_string().contains("slots_per_tx must be 1..=1300"),
                    "expected range validation error for slots_per_tx {slots_per_tx}, got: {err}"
                );
            }
        }
    }

    #[test]
    fn storage_config_rejects_invalid_contract_address() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
transactions:
  - weight: 100
    type: storage
    contract: "not_an_address"
    slots_per_tx: 5
"#;
        // An invalid address is now rejected eagerly by serde at deserialize time.
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(
            err.to_string().contains("failed to parse YAML"),
            "expected eager deserialize error for invalid address, got: {err}"
        );
    }

    #[test]
    fn rejects_http_scheme_for_flashblocks_ws() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: http://localhost:7111
"#;
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("flashblocks_ws"));
        assert!(err.to_string().contains("ws://"));
    }

    #[test]
    fn query_rpc_accepts_http() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
query_rpc: http://localhost:8546
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.query_rpc.as_ref().unwrap().scheme(), "http");
    }

    #[test]
    fn fresh_recipient_ratio_defaults_to_zero() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.fresh_recipient_ratio, 0.0);
        assert_eq!(config.to_load_config(Some(1337)).unwrap().fresh_recipient_ratio, 0.0);
    }

    #[test]
    fn fresh_recipient_ratio_explicit_one_round_trips() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
fresh_recipient_ratio: 1.0
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.fresh_recipient_ratio, 1.0);
        assert_eq!(config.to_load_config(Some(1337)).unwrap().fresh_recipient_ratio, 1.0);
        assert_eq!(config.to_summary().fresh_recipient_ratio, 1.0);
    }

    #[test]
    fn fresh_recipient_ratio_explicit_half_round_trips() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
fresh_recipient_ratio: 0.5
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.fresh_recipient_ratio, 0.5);
        assert_eq!(config.to_load_config(Some(1337)).unwrap().fresh_recipient_ratio, 0.5);
    }

    #[test]
    fn fresh_recipient_ratio_rejects_values_above_one() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
fresh_recipient_ratio: 1.1
"#;
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("fresh_recipient_ratio"));
    }

    #[test]
    fn query_rpc_rejects_wss() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
query_rpc: wss://localhost:8546
flashblocks_ws: wss://localhost:7111
"#;
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("query_rpc"));
        assert!(err.to_string().contains("https://"));
    }

    #[test]
    fn txpool_nodes_rejects_ws() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
txpool_nodes:
  - ws://localhost:7546
flashblocks_ws: ws://localhost:7111
"#;
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("txpool_nodes"));
        assert!(err.to_string().contains("http://"));
    }

    #[test]
    fn flashblocks_ws_accepts_wss() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: wss://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.flashblocks_ws.as_ref().unwrap().scheme(), "wss");
    }

    #[test]
    fn flashblocks_ws_is_optional() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert!(config.flashblocks_ws.is_none());
        assert!(config.to_load_config(Some(1337)).unwrap().flashblocks_ws.is_none());
    }

    #[test]
    fn flashblocks_ws_is_preserved_for_runtime() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();

        assert_eq!(
            config
                .to_load_config(Some(1337))
                .unwrap()
                .flashblocks_ws
                .as_ref()
                .map(url::Url::as_str),
            Some("ws://localhost:7111/")
        );
    }

    #[test]
    fn parse_uniswap_v3_config() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
transactions:
  - weight: 10
    type: uniswap_v3
    router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    token_in: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    token_out: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    fee: 500
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.transactions.len(), 1);
        match &config.transactions[0].tx_type {
            TxTypeConfig::UniswapV3 { fee, .. } => {
                assert_eq!(*fee, 500);
            }
            _ => panic!("expected UniswapV3"),
        }
    }

    #[test]
    fn validity_defaults_to_disabled() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.validity.ratio, 0.0);
        let load_config = config.to_load_config(Some(1337)).unwrap();
        assert_eq!(load_config.validity_ratio, 0.0);
        assert!(load_config.validity_predicates.is_empty());
        assert_eq!(config.to_summary().validity_ratio, 0.0);
    }

    #[test]
    fn validity_config_round_trips_predicates() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
validity:
  ratio: 0.25
  predicates:
    - type: balance
      address: sender
      op: ">="
      value: "0"
    - type: storage
      address: "0x1234567890123456789012345678901234567890"
      slot:
        kind: mapping
        mapping_slot: "0x0"
        key: sender
      op: ">="
      value: "0x0"
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.validity.ratio, 0.25);
        assert_eq!(config.validity.predicates.len(), 2);

        let load_config = config.to_load_config(Some(1337)).unwrap();
        assert_eq!(load_config.validity_ratio, 0.25);
        assert_eq!(load_config.validity_predicates.len(), 2);

        let summary = config.to_summary();
        assert_eq!(summary.validity_ratio, 0.25);
        assert_eq!(summary.validity_predicate_count, 2);
    }

    #[test]
    fn validity_devnet_example_parses_and_validates() {
        // Guards the committed example against schema drift: it must parse,
        // validate, and lower to a runnable LoadConfig with the validity cohort.
        let yaml = include_str!("../../examples/validity-devnet.yaml");
        let config = TestConfig::from_yaml(yaml).expect("validity-devnet.yaml must parse");
        assert_eq!(config.validity.ratio, 0.5);
        assert_eq!(config.validity.predicates.len(), 1);

        let load_config = config.to_load_config(Some(1337)).expect("must lower to LoadConfig");
        assert_eq!(load_config.validity_ratio, 0.5);
        assert_eq!(load_config.validity_predicates.len(), 1);
    }

    #[test]
    fn validity_rejects_ratio_above_one() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
validity:
  ratio: 1.5
  predicates:
    - type: balance
      op: ">="
      value: "0"
"#;
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("validity.ratio"));
    }

    #[test]
    fn validity_rejects_enabled_without_predicates() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
validity:
  ratio: 0.5
"#;
        let err = TestConfig::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("validity.predicates must be non-empty"));
    }

    #[test]
    fn double_counter_and_validity_priority_round_trip_to_runtime_and_summary() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
transactions:
  - weight: 100
    type: double_counter
    contract: "0x1111111111111111111111111111111111111111"
validity:
  priority_lead_ratio: 0.2
  priority_lead_multiplier: 4
  priority_fee_divisor: 3
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.validity.priority_lead_ratio, 0.2);
        assert_eq!(config.validity.priority_lead_multiplier, 4);
        assert_eq!(config.validity.priority_fee_divisor, 3);
        assert!(matches!(config.transactions[0].tx_type, TxTypeConfig::DoubleCounter { .. }));

        let load = config.to_load_config(Some(1337)).unwrap();
        assert_eq!(load.validity_priority_lead_ratio, 0.2);
        assert_eq!(load.validity_priority_lead_multiplier, 4);
        assert_eq!(load.validity_priority_fee_divisor, 3);
        assert!(matches!(load.transactions[0].tx_type, TxType::DoubleCounter { .. }));
        assert_eq!(config.to_summary().validity_priority_fee_divisor, 3);
        assert_eq!(config.to_summary().validity_priority_lead_ratio, 0.2);
        assert_eq!(config.to_summary().validity_priority_lead_multiplier, 4);
    }

    #[test]
    fn validity_priority_divisor_defaults_to_one_and_rejects_zero() {
        let config =
            TestConfig::from_yaml("transaction_submission_rpcs: http://localhost:8545").unwrap();
        assert_eq!(config.validity.priority_fee_divisor, 1);
        assert_eq!(config.to_load_config(Some(1337)).unwrap().validity_priority_fee_divisor, 1);

        let error = TestConfig::from_yaml(
            "transaction_submission_rpcs: http://localhost:8545\nvalidity:\n  priority_fee_divisor: 0",
        )
        .unwrap_err();
        assert!(error.to_string().contains("priority_fee_divisor must be >= 1"));
    }

    #[test]
    fn validity_priority_lead_settings_reject_out_of_range_values() {
        let error = TestConfig::from_yaml(
            "transaction_submission_rpcs: http://localhost:8545\nvalidity:\n  priority_lead_ratio: 1.1",
        )
        .unwrap_err();
        assert!(error.to_string().contains("priority_lead_ratio must be between 0.0 and 1.0"));

        let error = TestConfig::from_yaml(
            "transaction_submission_rpcs: http://localhost:8545\nvalidity:\n  priority_lead_multiplier: 0",
        )
        .unwrap_err();
        assert!(error.to_string().contains("priority_lead_multiplier must be >= 1"));
    }

    #[test]
    fn parse_aerodrome_cl_config() {
        let yaml = r#"
transaction_submission_rpcs: http://localhost:8545
flashblocks_ws: ws://localhost:7111
transactions:
  - weight: 10
    type: aerodrome_cl
    router: "0xBE6D8f0d05cC4be24d5167a3eF062215bE6D18a5"
    token_in: "0x4200000000000000000000000000000000000006"
    token_out: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    tick_spacing: 200
"#;
        let config = TestConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.transactions.len(), 1);
        match &config.transactions[0].tx_type {
            TxTypeConfig::AerodromeCl { tick_spacing, .. } => {
                assert_eq!(*tick_spacing, 200);
            }
            _ => panic!("expected AerodromeCl"),
        }
    }

    #[test]
    fn batch_size_defaults_to_rpc_limit() {
        let config =
            TestConfig::from_yaml("transaction_submission_rpcs: http://localhost:8545").unwrap();

        assert_eq!(config.batch_size, MAX_BATCH_RPC_SIZE as u32);
        assert_eq!(config.to_load_config(Some(1337)).unwrap().batch_size, MAX_BATCH_RPC_SIZE);
    }

    #[test]
    fn rejects_zero_batch_size() {
        let error = TestConfig::from_yaml(
            "transaction_submission_rpcs: http://localhost:8545\nbatch_size: 0",
        )
        .unwrap_err();

        assert!(error.to_string().contains("batch_size must be > 0"));
    }
}
