[package]
name = "base-precompile-macros"
description = "Procedural macros for type-safe EVM storage abstractions for Base native precompiles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
revm = {workspace = true}
alloy-primitives = { workspace = true }
quote = { workspace = true, features = ["default"] }
proc-macro2 = { workspace = true, features = ["default"] }
syn = { workspace = true, features = ["default", "full", "extra-traits"] }
[dev-dependencies]
alloy-primitives = { workspace = true }
