[package]
name = "base-common-types-payload"
description = "Base RPC types for the `engine` namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
either = { workspace = true }
thiserror = { workspace = true }
snap = { workspace = true, optional = true }
base-common-chain-config = { workspace = true }
base-execution-evm-runtime = { workspace = true }
base-execution-state-types = { workspace = true }
alloy-serde = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
ethereum_ssz = { workspace = true, optional = true }
alloy-eips = { workspace = true, features = ["serde"] }
derive_more = { workspace = true, features = ["display"] }
ethereum_ssz_derive = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync"], optional = true }
rand_08 = { workspace = true, optional = true, features = ["default"] }
futures = { workspace = true, optional = true, features = ["default"] }
arbitrary = { workspace = true, features = ["derive"], optional = true }
serde_with = { workspace = true, features = ["macros"], optional = true }
tracing = { workspace = true, features = ["attributes"], optional = true }
base-common-types-chain = { workspace = true, features = ["serde", "k256"] }
jsonwebtoken = { workspace = true, optional = true, features = ["default"] }
serde = { workspace = true, optional = true, features = ["derive", "alloc"] }
alloy-rlp = { workspace = true, features = ["arrayvec", "derive", "core-net"] }
alloy-primitives = { workspace = true, features = ["rlp", "serde", "map-foldhash"] }
tokio-stream = { workspace = true, features = ["default", "sync"], optional = true }
[dev-dependencies]
arbtest = { workspace = true }
bincode_1_3_3 = { workspace = true }
assert_matches = { workspace = true }
base-common-chain-config = { workspace = true }
base64 = { workspace = true, features = ["default"] }
rand_08 = { workspace = true, features = ["default"] }
arbitrary = { workspace = true, features = ["derive"] }
tempfile = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["alloc", "std"] }
similar-asserts = { workspace = true, features = ["default"] }
jsonwebtoken = { workspace = true, features = ["default", "aws_lc_rs"] }
base-common-types-chain = { workspace = true, features = ["arbitrary", "serde"] }
alloy-primitives = { workspace = true, features = ["arbitrary", "getrandom", "rand", "rlp", "serde", "map-foldhash"] }

[features]
default = ["serde", "std"]
std = [
    "base-common-types-chain/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "ssz",
    "alloy-serde?/std",
    "dep:ethereum_ssz",
    "dep:ethereum_ssz_derive",
    "dep:snap",
    "serde?/std",
    "sha2/std",
    "thiserror/std",
    "derive_more/std",
    "base-execution-state-types/std",
    "serde/std",
    "either/std",
    "serde_json/std",
    "dep:pin-project",
    "dep:tracing",
    "dep:tokio-stream",
    "futures/std",
    "tokio",
]
serde = [
    "base-common-types-chain/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "dep:alloy-serde",
    "dep:serde",
    "rand_08?/serde",
    "base-execution-state-types/serde",
]
k256 = ["base-common-types-chain/k256"]
arbitrary = [
    "base-common-types-chain/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-primitives/rand",
    "alloy-serde?/arbitrary",
    "dep:arbitrary",
    "std",
    "alloy-serde/arbitrary",
]
jwt = ["std", "dep:jsonwebtoken", "dep:rand_08"]
jwt-aws-lc-rs = ["jwt", "jsonwebtoken/aws_lc_rs"]
kzg = ["base-common-types-chain/kzg", "alloy-eips/kzg"]
ssz = ["std", "dep:ethereum_ssz", "dep:ethereum_ssz_derive", "alloy-eips/ssz"]
test-utils = ["std"]
trie-debug = []
serde-bincode-compat = ["base-execution-state-types/serde-bincode-compat", "serde_with", "alloy-eips/serde-bincode-compat"]
