[package]
name = "base-alt-da"
description = "Alt-DA HTTP server and object stores for L3 batch data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
hex.workspace = true
url.workspace = true
rand.workspace = true
base64.workspace = true
thiserror.workspace = true
async-trait.workspace = true
alloy-primitives.workspace = true
reqwest = { workspace = true, features = ["rustls"] }
tracing = { workspace = true, features = ["std"] }
tokio-util = { workspace = true, features = ["rt"] }
base-protocol = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["fs", "io-util", "rt"] }
axum = { workspace = true, features = ["tokio", "http1"] }
aws-config = { workspace = true, features = ["default-https-client", "rt-tokio"] }
aws-sdk-s3 = { workspace = true, features = ["rustls", "default-https-client", "rt-tokio"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
