[package]
name = "base-proof-service-challenger"
description = "Base Challenger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
alloy-rlp = { workspace = true }
humantime = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
base-proof-l1 = { workspace = true }
base-common-l1 = { workspace = true }
base-common-cli = { workspace = true }
alloy-primitives = { workspace = true }
base-proof-types = { workspace = true }
base-proof-client = { workspace = true }
base-consensus-batch = { workspace = true }
base-common-types-chain = { workspace = true }
metrics = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
url = { workspace = true, features = ["default"] }
async-trait = { workspace = true, optional = true }
eyre = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default"] }
alloy-trie = { workspace = true, features = ["std"] }
futures = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
tokio-util = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, optional = true }
rustls = { workspace = true, features = ["default", "ring"] }
base-common-runtime = { workspace = true, features = ["tokio"] }
base-common-http = { workspace = true, features = ["axum-server"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
base-common-client-ethereum = { workspace = true, features = ["default"] }
base-proof-service-protocol = { workspace = true, features = ["default"] }

[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
metrics-util = { workspace = true, features = ["debugging"] }
tokio = { workspace = true, features = ["default", "test-util"] }
base-proof-service-challenger = { workspace = true, features = ["test-utils"] }

[features]
metrics = ["base-common-observability-metrics/metrics", "base-common-l1/metrics", "dep:metrics"]
test-utils = [
    "base-common-types-rpc",
    "async-trait",
    "base-consensus-batch/test-utils",
    "base-common-runtime/test-utils",
    "serde_json",
]
