[package]
name = "base-proof-service-challenger"
description = "Base Challenger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
alloy-rlp = { workspace = true }
humantime = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
base-proof-client-providers = { workspace = true }
alloy-primitives = { workspace = true }
base-proof-l1-submission = {workspace = true}
base-proof-types-protocol = { workspace = true }
base-common-cli-support = { workspace = true }
base-common-types-chain = { workspace = true }
metrics = { workspace = true, optional = true }
base-common-l1-transactions = {workspace = true}
base-consensus-batch-types = { workspace = true }
base-proof-service-client = { workspace = true }
serde_json = { workspace = true, optional = true }
url = { workspace = true, features = ["default"] }
async-trait = { workspace = true, optional = true }
eyre = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default"] }
alloy-trie = { workspace = true, features = ["std"] }
futures = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
tokio-util = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, optional = true }
rustls = { workspace = true, features = ["default", "ring"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
base-common-runtime-tasks = { workspace = true, features = ["tokio"] }
base-common-client-ethereum = {workspace = true, features = ["default"]}
base-proof-service-protocol = { workspace = true, features = ["default"] }
base-common-observability-health = { workspace = true, features = ["axum-server"] }

[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
metrics-util = { workspace = true, features = ["debugging"] }
base-proof-service-challenger = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["default", "test-util"] }

[features]
metrics = ["base-common-observability-metrics/metrics", "base-common-l1-transactions/metrics", "dep:metrics"]
test-utils = ["base-common-types-rpc", "async-trait", "base-consensus-batch-types/test-utils", "base-common-runtime-tasks/test-utils", "serde_json"]
