//! Production [`ThrottleClient`] that calls `miner_setMaxDASize` via jsonrpsee.

use alloy_primitives::U64;
use base_batcher_core::ThrottleClient;
use futures::future::BoxFuture;
use jsonrpsee::{
    http_client::{HttpClient, HttpClientBuilder},
    proc_macros::rpc,
};
use url::Url;

/// Client-side jsonrpsee trait for the miner API extension.
#[rpc(client, namespace = "miner")]
trait MinerApiExt {
    /// Sets the maximum data availability size of any tx allowed in a block, and the total max l1
    /// data size of the block. 0 means no maximum.
    #[method(name = "setMaxDASize")]
    async fn set_max_da_size(&self, max_tx_size: U64, max_block_size: U64) -> RpcResult<bool>;
}

/// Production [`ThrottleClient`] that calls `miner_setMaxDASize` on an L2
/// execution node via a typed jsonrpsee client generated by `#[rpc(client)]`.
///
/// Connects to the standard (unauthenticated) HTTP RPC port. The `miner`
/// namespace must be enabled on the target node (`--http.api=...,miner`).
#[derive(Debug)]
pub struct RpcThrottleClient {
    client: HttpClient,
}

impl RpcThrottleClient {
    /// Build an [`RpcThrottleClient`] targeting `url`.
    pub fn new(url: &Url) -> eyre::Result<Self> {
        let client = HttpClientBuilder::default()
            .build(url.as_str())
            .map_err(|e| eyre::eyre!("failed to build throttle client: {e}"))?;
        Ok(Self { client })
    }
}

impl ThrottleClient for RpcThrottleClient {
    fn set_max_da_size(
        &self,
        max_tx_size: u64,
        max_block_size: u64,
    ) -> BoxFuture<'_, Result<(), Box<dyn std::error::Error + Send + Sync>>> {
        Box::pin(async move {
            let accepted = self
                .client
                .set_max_da_size(U64::from(max_tx_size), U64::from(max_block_size))
                .await?;
            // A node that accepts the call but answers `false` refused the limits.
            if !accepted {
                return Err("miner_setMaxDASize returned false".into());
            }
            Ok(())
        })
    }
}

#[cfg(test)]
mod tests {
    use httpmock::prelude::*;

    use super::*;

    fn json_rpc_response(result: &str) -> String {
        format!(r#"{{"jsonrpc":"2.0","id":0,"result":{result}}}"#)
    }

    /// The limits go out as `miner_setMaxDASize` with the tx and block sizes as hex quantities.
    #[tokio::test]
    async fn set_max_da_size_sends_correct_request() {
        let server = MockServer::start_async().await;
        let mock = server
            .mock_async(|when, then| {
                when.method(POST).path("/").json_body_includes(
                    r#"{"method":"miner_setMaxDASize","params":["0x96","0x4e20"]}"#,
                );
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;

        let client = RpcThrottleClient::new(&server.url("/").parse().unwrap()).unwrap();
        client.set_max_da_size(150, 20_000).await.unwrap();
        mock.assert_async().await;
    }

    /// A node that answers `false` refused the limits, which is an error.
    #[tokio::test]
    async fn set_max_da_size_false_return_is_an_error() {
        let server = MockServer::start_async().await;
        server
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("false"));
            })
            .await;

        let client = RpcThrottleClient::new(&server.url("/").parse().unwrap()).unwrap();
        let error = client.set_max_da_size(150, 20_000).await.unwrap_err();

        assert_eq!(error.to_string(), "miner_setMaxDASize returned false");
    }
}
