[package]
name = "base-execution-network-discovery"
description = "Helpers for working around NAT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
enr = {workspace = true}
thiserror = {workspace = true}
itertools = { workspace = true }
alloy-eip2124 = {workspace = true}
discv5-reth = { workspace = true }
futures-util = { workspace = true }
if-addrs_0_14_0 = { workspace = true }
linked_hash_set = { workspace = true }
serde = {optional = true, workspace = true}
dashmap = { workspace = true, features = ["inline"] }
schnellru = {workspace = true, features = ["default"]}
tracing = {workspace = true, features = ["attributes"]}
tokio-stream = {workspace = true, features = ["default"]}
parking_lot = { workspace = true, features = ["default"] }
data-encoding = { workspace = true, features = ["default"] }
reqwest = { workspace = true, features = ["rustls", "stream"] }
tokio = {workspace = true, features = ["io-util", "net", "time"]}
alloy-rlp = { workspace = true, features = ["core-net", "derive"] }
base-common-runtime-tasks = { workspace = true, features = ["time"] }
rand_08 = { workspace = true, optional = true, features = ["default"] }
serde_with = {workspace = true, optional = true, features = ["macros"]}
hickory-resolver = { workspace = true, features = ["default", "tokio"] }
alloy-primitives = {workspace = true, features = ["map-foldhash", "rand"]}
base-execution-network-types = {workspace = true, features = ["secp256k1", "std"]}
secp256k1 = {workspace = true, features = ["global-context", "recovery", "serde", "std"]}

[dev-dependencies]
alloy-chains = { workspace = true }
assert_matches = { workspace = true }
alloy-hardforks = { workspace = true }
base-common-chain-config = { workspace = true }
rand = { workspace = true, features = ["default"] }
rand_08 = { workspace = true, features = ["default"] }
alloy-rlp = { workspace = true, features = ["core-net"] }
base-common-observability-tracing = {workspace = true, features = ["default"]}
secp256k1 = {workspace = true, features = ["global-context", "rand", "recovery"]}
tokio = {workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync"]}

[features]
default = ["serde"]
serde = [
    "alloy-chains/serde",
    "alloy-primitives/serde",
    "dashmap/serde",
    "dep:serde",
    "dep:serde_with",
    "discv5-reth/serde",
    "enr/serde",
    "hickory-resolver/serde",
    "linked_hash_set/serde",
    "parking_lot/serde",
    "rand/serde",
    "rand_08?/serde",
    "secp256k1/serde",
]
test-utils = ["dep:rand_08"]
