[package]
name = "base-proof-driver"
description = "A no_std derivation pipeline driver"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
alloy-rlp = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
alloy-primitives = { workspace = true }
base-proof-executor = { workspace = true }
base-consensus-derive = { workspace = true }
base-common-types-chain = { workspace = true }
base-common-chain-config = { workspace = true }
base-common-types-payload = { workspace = true }
base-consensus-batch-types = { workspace = true }
base-execution-evm-runtime = { workspace = true }
spin = { workspace = true, features = ["default"] }

[features]
std = [
    "base-common-types-chain/std",
    "base-execution-evm-runtime/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "base-common-chain-config/std",
    "base-common-types-payload/std",
    "base-proof-executor/std",
    "base-consensus-batch-types/std",
    "spin/std",
    "thiserror/std",
    "tracing/std",
]
