[package]
name = "base-execution-state-maintenance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rayon = {workspace = true}
serde = { workspace = true }
tokio = { workspace = true }
metrics = { workspace = true }
thiserror = {workspace = true}
rustc-hash = { workspace = true }
alloy-genesis = { workspace = true }
base-common-io-files = { workspace = true }
boyer-moore-magiclen = { workspace = true }
reth-primitives-traits = {workspace = true}
base-common-runtime-tasks = {workspace = true}
base-common-chain-config = { workspace = true }
base-execution-state-api = { workspace = true }
base-execution-state-memory = {workspace = true}
base-execution-state-trie = { workspace = true }
base-execution-state-database = {workspace = true}
base-execution-state-provider = {workspace = true}
eyre = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["alloc"] }
tempfile = { workspace = true, features = ["default"] }
tracing = {workspace = true, features = ["attributes"]}
reth-exex-types = { workspace = true, features = ["default"] }
base-common-types-chain = {workspace = true, features = ["reth"]}
alloy-primitives = {workspace = true, features = ["map-foldhash"]}
base-execution-state-types = {workspace = true, features = ["std"]}
base-common-observability-metrics = { workspace = true, features = ["metrics"]}
parking_lot = { workspace = true, features = ["default", "send_guard", "arc_lock"] }

[dev-dependencies]
assert_matches = {workspace = true}
reth-testing-utils = {workspace = true}
base-common-chain-config = { workspace = true }
base-common-runtime-tasks = { workspace = true }
tempfile = { workspace = true, features = ["default"] }
reth-primitives-traits = { workspace = true, features = ["arbitrary"] }
base-execution-state-database = { workspace = true, features = ["mdbx"] }
base-execution-state-types = {workspace = true, features = ["arbitrary"]}
base-execution-sync-pipeline = {workspace = true, features = ["test-utils"]}
base-execution-state-provider = { workspace = true, features = ["test-utils"] }
base-common-observability-tracing = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "getrandom"] }

[lints]
workspace = true
