[package]
name = "base-execution-state-maintenance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
url = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
metrics = { workspace = true }
thiserror = { workspace = true }
humantime = { workspace = true }
rustc-hash = { workspace = true }
alloy-genesis = { workspace = true }
base-common-io = { workspace = true }
base-common-runtime = { workspace = true }
boyer-moore-magiclen = { workspace = true }
base-common-chain-config = { workspace = true }
base-execution-state-trie = { workspace = true }
base-execution-evm-runtime = { workspace = true }
tar = { workspace = true, features = ["default"] }
eyre = { workspace = true, features = ["default"] }
zstd = { workspace = true, features = ["default"] }
base-execution-state-database = { workspace = true }
base-execution-state-provider = { workspace = true }
anyhow = { workspace = true, features = ["default"] }
blake3 = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["alloc"] }
tempfile = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["attributes"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"] }
base-execution-state-types = { workspace = true, features = ["std"] }
base-common-types-chain = { features = ["k256", "reth"], workspace = true }
base-common-observability-metrics = { workspace = true, features = ["metrics"] }
parking_lot = { workspace = true, features = ["default", "send_guard", "arc_lock"] }

[dev-dependencies]
assert_matches = { workspace = true }
base-common-runtime = { workspace = true }
base-testing-support = { workspace = true }
base-common-chain-config = { workspace = true }
tempfile = { workspace = true, features = ["default"] }
base-execution-sync = { workspace = true, features = ["test-utils"] }
base-execution-state-database = { workspace = true, features = ["mdbx"] }
base-execution-state-types = { workspace = true, features = ["arbitrary"] }
base-execution-state-provider = { workspace = true, features = ["test-utils"] }
base-common-observability-tracing = { workspace = true, features = ["default"] }
base-common-types-chain = { workspace = true, features = ["arbitrary", "k256"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "getrandom"] }

[lints]
workspace = true
