[package]
name = "base-execution-eip8130"
description = "EIP-8130 native validation, intrinsic gas, and fee helpers"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
thiserror = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
base-execution-evm-precompiles = {workspace = true}
base-execution-evm-macros = { workspace = true }
base64 = { workspace = true, features = ["default"] }
k256 = { workspace = true, features = ["default", "ecdsa"] }
p256 = { workspace = true, features = ["default", "ecdsa"] }
base-common-types-chain = { workspace = true, features = ["k256"] }

[dev-dependencies]
revm-interpreter = { workspace = true }
base-execution-evm-precompiles = { workspace = true, features = ["test-utils"] }

[features]
test-utils = ["base-execution-evm-precompiles/test-utils"]
