[package]
name = "base-common-rpc-types-engine"
description = "Base RPC types for the `engine` namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
thiserror = { workspace = true }
snap = { workspace = true, optional = true }
alloy-serde = {workspace = true, optional = true}
ethereum_ssz = {workspace = true, optional = true}
alloy-eips = {workspace = true, features = ["serde"]}
ethereum_ssz_derive = {workspace = true, optional = true}
derive_more = { workspace = true, features = ["display"] }
base-common-types-chain = {workspace = true, features = ["serde"]}
alloy-rlp = {workspace = true, features = ["arrayvec", "derive"]}
alloy-primitives = {workspace = true, features = ["rlp", "serde"]}
arbitrary = {workspace = true, features = ["derive"], optional = true}
rand_08 = { workspace = true, optional = true, features = ["default"] }
serde = {workspace = true, optional = true, features = ["derive", "alloc"]}
jsonwebtoken = { workspace = true, optional = true, features = ["default"] }
[dev-dependencies]
arbtest = { workspace = true }
assert_matches_1_5 = { workspace = true }
serde_json = {workspace = true, features = ["alloc"]}
arbitrary = {workspace = true, features = ["derive"]}
base64 = { workspace = true, features = ["default"] }
rand_08 = { workspace = true, features = ["default"] }
tempfile = { workspace = true, features = ["default"] }
similar-asserts = { workspace = true, features = ["default"] }
base-common-types-chain = { workspace = true, features = ["arbitrary"] }
jsonwebtoken = { workspace = true, features = ["default", "aws_lc_rs"] }
alloy-primitives = {workspace = true, features = ["arbitrary", "getrandom", "rand", "rlp", "serde"]}

[features]
default = ["serde", "std"]
std = [
    "base-common-types-chain/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "ssz",
    "alloy-serde?/std",
    "dep:ethereum_ssz",
    "dep:ethereum_ssz_derive",
    "dep:snap",
    "serde?/std",
    "sha2/std",
    "thiserror/std",
    "derive_more/std",
]
serde = [
    "base-common-types-chain/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "dep:alloy-serde",
    "dep:serde",
    "rand_08?/serde",
]
k256 = ["base-common-types-chain/k256"]
arbitrary = [
    "base-common-types-chain/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-primitives/rand",
    "alloy-serde?/arbitrary",
    "dep:arbitrary",
    "std",
    "alloy-serde/arbitrary",
]
jwt = ["std", "dep:jsonwebtoken", "dep:rand_08"]
jwt-aws-lc-rs = ["jwt", "jsonwebtoken/aws_lc_rs"]
kzg = ["base-common-types-chain/kzg", "alloy-eips/kzg"]
ssz = ["std", "dep:ethereum_ssz", "dep:ethereum_ssz_derive", "alloy-eips/ssz"]
