[package]
name = "base-proof-client"
description = "Proof client types for the Base proof program"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
base-proof = { workspace = true }
base-protocol = { workspace = true }
alloy-primitives = { workspace = true }
base-evm-context = { workspace = true }
base-proof-driver = { workspace = true }
base-proof-executor = { workspace = true }
base-proof-preimage = { workspace = true }
base-consensus-derive = { workspace = true }
base-common-types-chain = { workspace = true }
base-common-chain-config = { workspace = true }
base-execution-evm-runtime = {workspace = true}
spin = { workspace = true, features = ["default"] }

[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "full"] }

[features]
std = [
    "base-common-types-chain/std",
    "base-execution-evm-runtime/std",
    "alloy-primitives/std",
    "base-common-chain-config/std",
    "base-proof-driver/std",
    "base-proof-executor/std",
    "base-proof-preimage/std",
    "base-proof/std",
    "base-protocol/std",
    "spin/std",
    "thiserror/std",
    "tracing/std",
]
