[package]
name = "base-execution-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Ethereum RPC implementation for Base."

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
tower = { workspace = true }
dyn-clone = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
alloy-serde = { workspace = true }
async-trait = { workspace = true }
pin-project = { workspace = true }
alloy-signer = { workspace = true }
reth-network = { workspace = true }
alloy-eip2124 = { workspace = true }
alloy-genesis = { workspace = true }
reth-provider = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-transport = { workspace = true }
jsonrpsee-types = { workspace = true }
reth-chain-state = { workspace = true }
reth-network-api = { workspace = true }
reth-prune-types = { workspace = true }
base-node-context = { workspace = true }
reth-payload-util = { workspace = true }
reth-storage-errors = {workspace = true}
opentelemetry-http = { workspace = true }
reth-network-types = { workspace = true }
reth-rpc-eth-types = { workspace = true }
base-execution-trie = { workspace = true }
alloy-rpc-types-admin = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
reth-rpc-server-types = { workspace = true }
reth-engine-primitives = { workspace = true }
metrics = { workspace = true, optional = true }
base-observability-events = { workspace = true }
base-execution-evm-machine = { workspace = true }
eyre = { workspace = true, features = ["default"] }
http = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["kzg"]}
futures = { workspace = true, features = ["default"] }
reth-db-common = { workspace = true, optional = true }
serde_json = { workspace = true, features = ["alloc"] }
alloy-eip7928 = { workspace = true, features = ["rlp"] }
base-common-observability-metrics = { workspace = true }
tracing = { workspace = true, features = ["attributes"]}
alloy-rlp = { workspace = true, features = ["core-net"] }
parking_lot = { workspace = true, features = ["default"] }
tokio-stream = { workspace = true, features = ["default"] }
opentelemetry = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "sync"] }
jsonrpsee-core = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
reth-rpc-convert = { workspace = true, features = ["default"] }
reth-storage-api = { workspace = true, features = ["default"] }
jsonrpsee = { workspace = true, features = ["macros", "server"] }
reth-execution-types = { workspace = true, features = ["serde"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"]}
alloy-transport-http = { workspace = true, features = ["default"] }
base-common-network = { workspace = true, features = ["mnemonic"] }
base-common-types-chain = { workspace = true, features = ["reth"] }
reth-network-peers = { workspace = true, features = ["secp256k1"] }
base-execution-txpool = { workspace = true, features = ["default"] }
base-common-chain-config = {features = ["default"], workspace = true}
alloy-dyn-abi = { workspace = true, features = ["default", "eip712"] }
base-common-runtime-tasks = { workspace = true, features = ["rayon"] }
reth-primitives-traits = { workspace = true, features = ["rpc-compat"]}
base-execution-payload-types = { workspace = true, features = ["default"]}
reth-trie-common = { workspace = true, features = ["default", "eip1186"] }
base-common-types-rpc = {workspace = true, features = ["default", "serde"]}
base-execution-evm-inspectors = { workspace = true, features = ["default"] }
base-execution-payload-builder = { workspace = true, features = ["default"] }
base-common-types-payload = {workspace = true, features = ["serde", "std", "kzg"]}
base-execution-evm-blocks = { workspace = true, features = ["default", "witness"] }
base-execution-evm-runtime = { workspace = true, features = ["overrides", "call-util", "optional_block_gas_limit", "optional_eip3607", "optional_no_base_fee", "memory_limit", "optional_fee_charge"] }

[dev-dependencies]
reth-db-api = { workspace = true }
assert_matches = { workspace = true }
reth-db-common = { workspace = true }
reth-testing-utils = { workspace = true }
rand = { workspace = true, features = ["default"] }
jsonrpsee = { workspace = true, features = ["client"] }
alloy-rlp = { workspace = true, features = ["core-net"] }
base-common-types-rpc = { workspace = true, features = [] }
reth-network = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
base-common-types-chain = {workspace = true, features = ["serde"]}
base-common-chain-config = { workspace = true, features = ["std"] }
base-execution-txpool = { workspace = true, features = ["test-utils"]}
reth-engine-primitives = { workspace = true, features = ["test-utils"] }
base-common-runtime-tasks = { workspace = true, features = ["test-utils"] }
base-execution-evm-blocks = { workspace = true, features = ["test-utils"] }
base-execution-payload-builder = { workspace = true, features = ["test-utils"] }

[features]
default = ["metrics"]
client = ["reth-chain-state/serde", "jsonrpsee/async-client", "jsonrpsee/client"]
metrics = [
    "dep:metrics",
    "base-execution-payload-builder/metrics",
    "base-execution-trie/metrics",
    "base-common-observability-metrics/metrics",
    "base-observability-events/metrics",
    "base-execution-evm-blocks/metrics",
]
test-utils = [
    "base-execution-evm-blocks/test-utils",
    "reth-provider/test-utils",
    "reth-network/test-utils",
    "dep:reth-db-common",
]
js-tracer = ["base-execution-evm-inspectors/js-tracer", "reth-rpc-eth-types/js-tracer"]
