#![doc = include_str!("../README.md")]
#![warn(missing_docs)]
#![warn(unreachable_pub)]
#![deny(unused_must_use)]
#![deny(rust_2018_idioms)]

// Lint allows are scoped to this module because it contains protobuf code
// generated by prost/tonic that we cannot modify. The `missing_docs` lint for
// generated types is handled via build.rs `message_attribute`/`enum_attribute`;
// the remaining allows cover impl-block clippy lints and the `unreachable_pub`
// on the generated client sub-module.
#[allow(
    unreachable_pub,
    clippy::clone_on_ref_ptr,
    clippy::doc_markdown,
    clippy::missing_const_for_fn
)]
mod proto {
    tonic::include_proto!("prover");
}
pub use proto::{
    GetProofRequest, GetProofResponse, ProofType, ProveBlockRequest, ProveBlockResponse,
    ReceiptType, get_proof_response::Status as ProofJobStatus,
};

mod client;
pub use client::{ZkProofClient, ZkProofClientConfig, ZkProofProvider};

mod error;
pub use error::ZkProofError;
