//! Command-line launcher for development networks.

use std::{
    net::{IpAddr, Ipv4Addr},
    num::NonZeroU64,
    path::PathBuf,
};

use alloy_primitives::{Address, B256};
use alloy_rpc_types_engine::JwtSecret;
use base_builder_cli::TransactionEventsArgs;
use base_observability_events::GlobalTransactionEventWriter;
use base_upgrade_signal::UpgradeSignalArgs;
use clap::{Args, Parser, Subcommand};
use eyre::{Result, WrapErr};
use serde::Serialize;
use url::Url;

use crate::{
    DevnetBlockInterval, DevnetConfig, DevnetL2State, DevnetPrefund, DevnetSnapshotHead,
    InProcessNodeRuntime, LightGenesisFiles, LightL2Stack, LightL2StackConfig, SequencerStack,
    SequencerStackConfig, SharedL1, SnapshotChainConfig, SnapshotL2Stack, SystemTestPorts,
    SystemTestStackBuilder,
};

/// Local Base development network launcher.
#[derive(Debug, Parser)]
#[command(author, version, about = "Run a local Base development network")]
pub struct DevnetCli {
    /// Development network mode.
    #[command(subcommand)]
    pub command: DevnetCommand,
}

/// Supported development network modes.
#[derive(Debug, Subcommand)]
pub enum DevnetCommand {
    /// Run a fresh builder and sequencer against an existing development L1.
    Fresh(Box<FreshArgs>),
    /// Continue Base snapshot datadirs without an L1.
    Snapshot(SnapshotArgs),
    /// Run a fresh-genesis builder and standalone sequencer without an L1 or Docker.
    Light(LightArgs),
    /// Start a CI-scoped shared L1 and write its runtime manifest.
    SharedL1(SharedL1Args),
}

/// Arguments for a CI-scoped shared L1 fixture.
#[derive(Debug, Args)]
pub struct SharedL1Args {
    /// File written after the shared L1 is ready for consumers.
    #[arg(long)]
    pub runtime_file: PathBuf,
    /// Docker network shared with live L2 deployments.
    #[arg(long)]
    pub network_name: String,
}

/// Arguments for the Docker-backed fresh development network sequencer.
#[derive(Debug, Args)]
pub struct FreshArgs {
    /// Fresh L2 genesis JSON generated by the devnet setup container.
    #[arg(long, default_value = "/genesis/l2/genesis.json")]
    pub l2_genesis: PathBuf,
    /// Rollup configuration generated by the devnet setup container.
    #[arg(long, default_value = "/genesis/l2/rollup.json")]
    pub rollup_config: PathBuf,
    /// L1 execution genesis JSON used by consensus derivation.
    #[arg(long, default_value = "/genesis/el/genesis.json")]
    pub l1_genesis: PathBuf,
    /// JWT secret shared by the embedded execution and consensus nodes.
    #[arg(long, default_value = "/genesis/jwt.hex")]
    pub jwt_secret: PathBuf,
    /// Persistent builder execution datadir.
    #[arg(long, default_value = "/data")]
    pub builder_datadir: PathBuf,
    /// L1 execution RPC endpoint reachable from the launcher.
    #[arg(long)]
    pub l1_rpc_url: Url,
    /// L1 beacon API endpoint reachable from the launcher.
    #[arg(long)]
    pub l1_beacon_url: Url,
    /// L1 slot duration override in seconds.
    #[arg(long, default_value_t = 12)]
    pub l1_slot_duration: u64,
    /// Builder execution and consensus P2P private key.
    #[arg(long, env = "BUILDER_P2P_KEY")]
    pub p2p_key: B256,
    /// Sequencer block-signing private key.
    #[arg(long, env = "SEQUENCER_KEY")]
    pub sequencer_key: B256,
    /// Address used by RPC, metrics, and Flashblocks listeners.
    #[arg(long, default_value = "0.0.0.0")]
    pub rpc_addr: IpAddr,
    /// Fixed container address advertised by execution and consensus P2P.
    #[arg(long, env = "L2_BUILDER_ADVERTISE_IP")]
    pub p2p_addr: IpAddr,
    /// Builder HTTP RPC port.
    #[arg(long, env = "L2_BUILDER_HTTP_PORT", default_value_t = 7545)]
    pub http_port: u16,
    /// Builder WebSocket RPC port.
    #[arg(long, env = "L2_BUILDER_WS_PORT", default_value_t = 7546)]
    pub ws_port: u16,
    /// Builder authenticated Engine API port.
    #[arg(long, env = "L2_BUILDER_AUTH_PORT", default_value_t = 7551)]
    pub auth_port: u16,
    /// Builder execution P2P port.
    #[arg(long, env = "L2_BUILDER_P2P_PORT", default_value_t = 7303)]
    pub p2p_port: u16,
    /// Builder Flashblocks WebSocket port.
    #[arg(long, env = "L2_BUILDER_FLASHBLOCKS_PORT", default_value_t = 7111)]
    pub flashblocks_port: u16,
    /// Builder Prometheus metrics port.
    #[arg(long, env = "L2_BUILDER_METRICS_PORT", default_value_t = 7090)]
    pub metrics_port: u16,
    /// Builder consensus RPC port.
    #[arg(long, env = "L2_BUILDER_CL_RPC_PORT", default_value_t = 7549)]
    pub consensus_rpc_port: u16,
    /// Builder consensus P2P TCP port.
    #[arg(long, env = "L2_BUILDER_CL_P2P_PORT", default_value_t = 7003)]
    pub consensus_p2p_port: u16,
    /// File containing consensus bootnode ENRs.
    #[arg(long, default_value = "/bootnodes/cl-bootnode.enr")]
    pub consensus_bootnodes_file: PathBuf,
    /// Enable the experimental validity transaction RPC and builder support.
    #[arg(long)]
    pub experimental_validity_transactions: bool,
    /// Cut the active payload builder over at Denim.
    #[arg(long)]
    pub payload_builder_cutover: bool,
    /// Pending/basefee/queued transaction count limit.
    #[arg(long, default_value_t = 200_000)]
    pub txpool_max_transactions: usize,
    /// Pending/basefee/queued transaction size limit in megabytes.
    #[arg(long, default_value_t = 512)]
    pub txpool_max_size_mb: usize,
    /// Maximum number of transaction slots retained per sender.
    #[arg(long, default_value_t = 256)]
    pub txpool_max_account_slots: usize,
    /// L1 upgrade signal configuration.
    #[command(flatten)]
    pub upgrade_signal: UpgradeSignalArgs,
    /// Dedicated builder transaction event journal configuration.
    #[command(flatten)]
    pub transaction_events: TransactionEventsArgs,
    /// Machine-readable endpoint output.
    #[arg(long, default_value = "/tmp/base-devnet-runtime.json")]
    pub runtime_file: PathBuf,
}

/// Machine-readable state emitted by the fresh devnet launcher.
#[derive(Debug, Serialize)]
pub struct FreshRuntime {
    /// Current launcher state.
    pub status: &'static str,
    /// Builder execution JSON-RPC URL.
    pub builder_rpc_url: String,
    /// Builder Flashblocks WebSocket URL.
    pub builder_flashblocks_url: String,
    /// Builder consensus JSON-RPC URL.
    pub builder_consensus_rpc_url: String,
}

/// Arguments for an L1-free Base snapshot network.
#[derive(Debug, Args)]
pub struct SnapshotArgs {
    /// Built-in Base chain name or path to a Base genesis JSON file.
    #[arg(long, default_value = "mainnet")]
    pub chain: String,
    /// Rollup config JSON for a custom chain JSON whose chain ID is not built in.
    #[arg(long)]
    pub rollup_config: Option<PathBuf>,
    /// Writable builder snapshot datadir.
    #[arg(long, env = "BASE_SNAPSHOT_BUILDER_DATADIR")]
    pub builder_datadir: PathBuf,
    /// Writable client snapshot datadir for the same chain.
    #[arg(long, env = "BASE_SNAPSHOT_CLIENT_DATADIR")]
    pub client_datadir: PathBuf,
    /// Bind the stable developer ports instead of allocating free ports.
    #[arg(long)]
    pub stable_ports: bool,
    /// Interval between locally produced blocks.
    #[arg(long, value_enum, default_value_t)]
    pub block_interval: DevnetBlockInterval,
    /// Block gas limit for locally produced descendants. Defaults to 10 Ggas for 2s blocks and
    /// 1 Ggas for 200ms blocks.
    #[arg(long)]
    pub block_gas_limit: Option<NonZeroU64>,
    /// Account to mint ETH to in the first local descendant block.
    #[arg(long)]
    pub prefund_address: Option<Address>,
    /// Amount of wei minted to `--prefund-address`.
    #[arg(long, default_value_t = 1_000_000_000_000_000_000_000_u128)]
    pub prefund_amount: u128,
    /// Expected snapshot boundary block number.
    #[arg(long, requires_all = ["expected_head_hash", "expected_head_timestamp"])]
    pub expected_head_number: Option<u64>,
    /// Expected snapshot boundary block hash.
    #[arg(long, requires_all = ["expected_head_number", "expected_head_timestamp"])]
    pub expected_head_hash: Option<B256>,
    /// Expected snapshot boundary Unix timestamp.
    #[arg(long, requires_all = ["expected_head_number", "expected_head_hash"])]
    pub expected_head_timestamp: Option<u64>,
    /// Machine-readable endpoint and boundary output.
    #[arg(long, default_value = "runtime.json")]
    pub runtime_file: PathBuf,
}

/// Machine-readable state emitted by the snapshot devnet launcher.
#[derive(Debug, Serialize)]
pub struct SnapshotRuntime {
    /// Current launcher state.
    pub status: &'static str,
    /// L2 chain ID.
    pub chain_id: u64,
    /// Snapshot boundary block number.
    pub boundary_number: u64,
    /// Snapshot boundary block hash.
    pub boundary_hash: B256,
    /// Configured interval between local blocks, in milliseconds.
    pub block_interval_ms: u64,
    /// Configured block gas limit for local descendants.
    pub block_gas_limit: u64,
    /// Builder execution JSON-RPC URL.
    pub builder_rpc_url: String,
    /// Builder Flashblocks WebSocket URL.
    pub builder_flashblocks_url: String,
    /// Client execution JSON-RPC URL.
    pub client_rpc_url: String,
}

/// Arguments for an L1-free fresh-genesis light development network.
#[derive(Debug, Args)]
pub struct LightArgs {
    /// Builder execution datadir, which must not hold a database. A temporary directory removed
    /// on exit is used when omitted.
    #[arg(long, env = "BASE_LIGHT_DATADIR")]
    pub datadir: Option<PathBuf>,
    /// Bind the stable developer ports instead of allocating free ports.
    #[arg(long)]
    pub stable_ports: bool,
    /// Interval between locally produced blocks.
    #[arg(long, value_enum, default_value_t)]
    pub block_interval: DevnetBlockInterval,
    /// Block gas limit of the generated chain. Defaults to 60 Mgas for 2s blocks and 6 Mgas for
    /// 200ms blocks. Ignored for a custom `--l2-genesis`, whose gas limit is used.
    #[arg(long, conflicts_with = "l2_genesis")]
    pub block_gas_limit: Option<NonZeroU64>,
    /// Account to mint ETH to in the first block, in addition to the prefunded Anvil accounts.
    #[arg(long)]
    pub prefund_address: Option<Address>,
    /// Amount of wei minted to `--prefund-address`.
    #[arg(long, default_value_t = 1_000_000_000_000_000_000_000_u128)]
    pub prefund_amount: u128,
    /// Fresh L2 genesis JSON replacing the generated chain. Must be stamped within the last hour.
    #[arg(long, requires = "rollup_config")]
    pub l2_genesis: Option<PathBuf>,
    /// Rollup configuration JSON matching `--l2-genesis`.
    #[arg(long, requires = "l2_genesis")]
    pub rollup_config: Option<PathBuf>,
    /// Pending/basefee/queued transaction count limit.
    #[arg(long, default_value_t = 50_000)]
    pub txpool_max_transactions: usize,
    /// Pending/basefee/queued transaction size limit in megabytes.
    #[arg(long, default_value_t = 256)]
    pub txpool_max_size_mb: usize,
    /// Maximum number of transaction slots retained per sender.
    #[arg(long, default_value_t = 1_024)]
    pub txpool_max_account_slots: usize,
    /// Machine-readable endpoint output, written once the chain is advancing.
    #[arg(long)]
    pub runtime_file: Option<PathBuf>,
}

/// Machine-readable state emitted by the light devnet launcher.
#[derive(Debug, Serialize)]
pub struct LightRuntime {
    /// Current launcher state.
    pub status: &'static str,
    /// L2 chain ID.
    pub chain_id: u64,
    /// L2 genesis block hash.
    pub genesis_hash: B256,
    /// Configured interval between local blocks, in milliseconds.
    pub block_interval_ms: u64,
    /// Configured block gas limit.
    pub block_gas_limit: u64,
    /// Builder execution JSON-RPC URL.
    pub builder_rpc_url: String,
    /// Builder execution WebSocket URL.
    pub builder_ws_url: String,
    /// Builder Flashblocks WebSocket URL.
    pub builder_flashblocks_url: String,
    /// Builder Prometheus metrics URL.
    pub builder_metrics_url: String,
    /// Builder execution datadir.
    pub datadir: PathBuf,
}

impl DevnetCli {
    /// Runs the selected development network until interrupted.
    pub async fn run(self) -> Result<()> {
        match self.command {
            DevnetCommand::Fresh(args) => (*args).run().await,
            DevnetCommand::Snapshot(args) => args.run().await,
            DevnetCommand::Light(args) => args.run().await,
            DevnetCommand::SharedL1(args) => args.run().await,
        }
    }

    /// Waits for an interactive interrupt or container termination signal.
    pub async fn shutdown_signal() -> Result<()> {
        #[cfg(unix)]
        {
            let mut terminate =
                tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
                    .wrap_err("failed to listen for SIGTERM")?;
            tokio::select! {
                result = tokio::signal::ctrl_c() => {
                    result.wrap_err("failed to listen for Ctrl-C")?;
                }
                _ = terminate.recv() => {}
            }
            Ok(())
        }

        #[cfg(not(unix))]
        tokio::signal::ctrl_c().await.wrap_err("failed to listen for Ctrl-C")
    }
}

impl FreshArgs {
    /// Starts a fresh builder and sequencer, writes its runtime manifest, and waits for shutdown.
    pub async fn run(self) -> Result<()> {
        let l2_genesis = std::fs::read(&self.l2_genesis)
            .wrap_err_with(|| format!("failed to read L2 genesis {}", self.l2_genesis.display()))?;
        let rollup_config = std::fs::read(&self.rollup_config).wrap_err_with(|| {
            format!("failed to read rollup config {}", self.rollup_config.display())
        })?;
        let l1_genesis = std::fs::read(&self.l1_genesis)
            .wrap_err_with(|| format!("failed to read L1 genesis {}", self.l1_genesis.display()))?;
        let jwt_secret_hex = std::fs::read_to_string(&self.jwt_secret)
            .wrap_err_with(|| format!("failed to read JWT secret {}", self.jwt_secret.display()))?;
        let jwt_secret = JwtSecret::from_hex(jwt_secret_hex.trim())
            .wrap_err("failed to parse builder JWT secret")?;
        let consensus_bootnodes = std::fs::read_to_string(&self.consensus_bootnodes_file)
            .wrap_err_with(|| {
                format!(
                    "failed to read consensus bootnodes {}",
                    self.consensus_bootnodes_file.display()
                )
            })?
            .split([',', '\n'])
            .map(str::trim)
            .filter(|bootnode| !bootnode.is_empty())
            .map(ToOwned::to_owned)
            .collect();

        GlobalTransactionEventWriter::init(Some(self.transaction_events.writer_config()))
            .wrap_err("failed to initialize builder transaction event journal")?;

        let stack = SequencerStack::start(SequencerStackConfig {
            runtime: InProcessNodeRuntime::Host,
            l2_genesis,
            builder_datadir: Some(self.builder_datadir),
            require_existing_datadir: false,
            rollup_config,
            l1_genesis,
            jwt_secret,
            p2p_key: self.p2p_key,
            sequencer_key: self.sequencer_key,
            l1_rpc_url: self.l1_rpc_url,
            l1_beacon_url: self.l1_beacon_url,
            l1_slot_duration: self.l1_slot_duration,
            execution_rpc_addr: self.rpc_addr,
            execution_p2p_addr: self.p2p_addr,
            builder_http_port: Some(self.http_port),
            builder_ws_port: Some(self.ws_port),
            builder_auth_port: Some(self.auth_port),
            builder_p2p_port: Some(self.p2p_port),
            builder_flashblocks_port: Some(self.flashblocks_port),
            builder_metrics_port: Some(self.metrics_port),
            consensus_rpc_addr: self.rpc_addr,
            consensus_p2p_listen_addr: IpAddr::V4(Ipv4Addr::UNSPECIFIED),
            consensus_p2p_advertise_addr: self.p2p_addr,
            consensus_rpc_port: Some(self.consensus_rpc_port),
            consensus_p2p_tcp_port: Some(self.consensus_p2p_port),
            consensus_p2p_udp_port: Some(self.consensus_p2p_port),
            consensus_bootnodes,
            sequencer_stopped: false,
            enable_experimental_validity_transactions: self.experimental_validity_transactions,
            payload_builder_cutover: self.payload_builder_cutover,
            upgrade_signal: self.upgrade_signal.config(),
            extra_builder_extensions: Vec::new(),
            txpool_max_transactions: Some(self.txpool_max_transactions),
            txpool_max_size_mb: Some(self.txpool_max_size_mb),
            txpool_max_account_slots: Some(self.txpool_max_account_slots),
            clear_otel_env: false,
        })
        .await?;
        let runtime = FreshRuntime::ready(&stack)?;
        let encoded = serde_json::to_vec_pretty(&runtime)?;
        std::fs::write(&self.runtime_file, encoded).wrap_err_with(|| {
            format!("failed to write runtime manifest {}", self.runtime_file.display())
        })?;

        println!("fresh devnet sequencer ready");
        println!("builder RPC:   {}", runtime.builder_rpc_url);
        println!("consensus RPC: {}", runtime.builder_consensus_rpc_url);
        println!("runtime:       {}", self.runtime_file.display());
        DevnetCli::shutdown_signal().await?;
        stack.shutdown().await
    }
}

impl FreshRuntime {
    /// Captures ready endpoints from a running fresh sequencer stack.
    pub fn ready(stack: &SequencerStack) -> Result<Self> {
        Ok(Self {
            status: "ready",
            builder_rpc_url: stack.builder().rpc_url()?.to_string(),
            builder_flashblocks_url: stack.builder().flashblocks_url(),
            builder_consensus_rpc_url: stack.consensus().rpc_url().to_string(),
        })
    }
}

impl SharedL1Args {
    /// Starts the fixture, publishes its manifest, and waits for shutdown.
    pub async fn run(self) -> Result<()> {
        let stack = SharedL1::start(self.network_name).await?;
        stack.runtime().write(&self.runtime_file)?;
        println!("shared L1 ready: {}", self.runtime_file.display());
        tokio::signal::ctrl_c().await.wrap_err("failed to listen for Ctrl-C")?;
        stack.shutdown().await
    }
}

impl SnapshotArgs {
    /// Starts a snapshot-backed stack, writes its runtime manifest, and waits for shutdown.
    pub async fn run(self) -> Result<()> {
        let expected_head = match (
            self.expected_head_number,
            self.expected_head_hash,
            self.expected_head_timestamp,
        ) {
            (Some(number), Some(hash), Some(timestamp)) => {
                Some(DevnetSnapshotHead { number, hash, timestamp })
            }
            (None, None, None) => None,
            _ => unreachable!("clap requires all expected-head fields together"),
        };
        let mut config = DevnetConfig::snapshot(
            self.builder_datadir,
            self.client_datadir,
            SnapshotChainConfig { chain: self.chain, rollup_config: self.rollup_config },
        )?;
        config.use_stable_ports = self.stable_ports;
        let DevnetL2State::Snapshot(snapshot) = &mut config.l2_state else {
            unreachable!("snapshot constructor must create snapshot state")
        };
        snapshot.expected_head = expected_head;
        snapshot.block_interval = self.block_interval;
        snapshot.block_gas_limit = self.block_gas_limit.map(NonZeroU64::get);
        snapshot.prefund = self
            .prefund_address
            .map(|address| DevnetPrefund { address, amount: self.prefund_amount });
        config.validate()?;

        let stack =
            SystemTestStackBuilder::new().with_devnet_config(config).build_snapshot().await?;
        let runtime = SnapshotRuntime::ready(&stack)?;
        let encoded = serde_json::to_vec_pretty(&runtime)?;
        std::fs::write(&self.runtime_file, encoded).wrap_err_with(|| {
            format!("failed to write runtime manifest {}", self.runtime_file.display())
        })?;

        println!("snapshot devnet ready");
        println!("builder RPC: {}", runtime.builder_rpc_url);
        println!("client RPC:  {}", runtime.client_rpc_url);
        println!("block gas:   {}", runtime.block_gas_limit);
        println!("runtime:     {}", self.runtime_file.display());
        println!("press Ctrl-C to stop");
        DevnetCli::shutdown_signal().await?;
        stack.shutdown().await?;
        Ok(())
    }
}

impl SnapshotRuntime {
    /// Captures the ready endpoints and immutable boundary from a running stack.
    pub fn ready(stack: &SnapshotL2Stack) -> Result<Self> {
        let boundary = stack.boundary();
        Ok(Self {
            status: "ready",
            chain_id: stack.chain_id(),
            boundary_number: boundary.head.number,
            boundary_hash: boundary.head.hash,
            block_interval_ms: stack.block_interval().duration().as_millis() as u64,
            block_gas_limit: stack.block_gas_limit(),
            builder_rpc_url: stack.builder_rpc_url()?.to_string(),
            builder_flashblocks_url: stack.builder_flashblocks_url()?.to_string(),
            client_rpc_url: stack.client_rpc_url()?.to_string(),
        })
    }
}

impl LightArgs {
    /// Returns the stack configuration selected by these arguments.
    pub fn stack_config(&self) -> LightL2StackConfig {
        let genesis_files = self
            .l2_genesis
            .clone()
            .zip(self.rollup_config.clone())
            .map(|(l2_genesis, rollup_config)| LightGenesisFiles { l2_genesis, rollup_config });
        LightL2StackConfig {
            runtime: InProcessNodeRuntime::Host,
            block_interval: self.block_interval,
            block_gas_limit: self.block_gas_limit.map(NonZeroU64::get),
            datadir: self.datadir.clone(),
            ports: self.stable_ports.then(SystemTestPorts::standard),
            prefund: self
                .prefund_address
                .map(|address| DevnetPrefund { address, amount: self.prefund_amount }),
            genesis_files,
            txpool_max_transactions: self.txpool_max_transactions,
            txpool_max_size_mb: self.txpool_max_size_mb,
            txpool_max_account_slots: self.txpool_max_account_slots,
        }
    }

    /// Starts the light stack, writes its runtime manifest, and waits for shutdown.
    pub async fn run(self) -> Result<()> {
        let mut stack = LightL2Stack::start(self.stack_config()).await?;
        let runtime = LightRuntime::ready(&stack)?;
        if let Some(path) = &self.runtime_file {
            let encoded = serde_json::to_vec_pretty(&runtime)?;
            std::fs::write(path, encoded)
                .wrap_err_with(|| format!("failed to write runtime manifest {}", path.display()))?;
        }

        println!("light devnet ready (no L1: no safe or finalized head, no batcher)");
        println!("chain id:    {}", runtime.chain_id);
        println!("builder RPC: {}", runtime.builder_rpc_url);
        println!("builder WS:  {}", runtime.builder_ws_url);
        println!("flashblocks: {}", runtime.builder_flashblocks_url);
        println!(
            "block:       every {}ms, gas limit {}",
            runtime.block_interval_ms, runtime.block_gas_limit
        );
        println!("datadir:     {}", runtime.datadir.display());
        if let Some(path) = &self.runtime_file {
            println!("runtime:     {}", path.display());
        }
        println!("press Ctrl-C to stop");
        tokio::select! {
            result = DevnetCli::shutdown_signal() => result?,
            error = stack.next_error() => {
                let _ = stack.shutdown().await;
                eyre::bail!("standalone consensus failed: {error}");
            }
        }
        stack.shutdown().await
    }
}

impl LightRuntime {
    /// Captures the ready endpoints from a running light stack.
    pub fn ready(stack: &LightL2Stack) -> Result<Self> {
        Ok(Self {
            status: "ready",
            chain_id: stack.chain_id(),
            genesis_hash: stack.genesis_hash(),
            block_interval_ms: stack.block_interval().duration().as_millis() as u64,
            block_gas_limit: stack.block_gas_limit(),
            builder_rpc_url: stack.builder_rpc_url()?.to_string(),
            builder_ws_url: stack.builder_ws_url()?.to_string(),
            builder_flashblocks_url: stack.builder_flashblocks_url()?.to_string(),
            builder_metrics_url: stack.builder_metrics_url()?.to_string(),
            datadir: stack.datadir().to_path_buf(),
        })
    }
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroU64;

    use clap::Parser;

    use super::{DevnetCli, DevnetCommand};
    use crate::DevnetBlockInterval;

    #[test]
    fn parses_fresh_command() {
        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "fresh",
            "--l1-rpc-url",
            "http://l1-el:4545",
            "--l1-beacon-url",
            "http://l1-cl:4052",
            "--p2p-key",
            "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6",
            "--sequencer-key",
            "0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba",
            "--p2p-addr",
            "172.30.0.20",
        ])
        .unwrap();

        let DevnetCommand::Fresh(args) = cli.command else { panic!("expected fresh command") };
        assert_eq!(args.http_port, 7545);
        assert_eq!(args.consensus_p2p_port, 7003);
        assert_eq!(args.l1_rpc_url.as_str(), "http://l1-el:4545/");
    }

    #[test]
    fn parses_snapshot_command() {
        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "snapshot",
            "--chain",
            "sepolia",
            "--builder-datadir",
            "/tmp/builder",
            "--client-datadir",
            "/tmp/client",
            "--prefund-address",
            "0x0000000000000000000000000000000000000001",
            "--block-interval",
            "200ms",
        ])
        .unwrap();

        let DevnetCommand::Snapshot(args) = cli.command else {
            panic!("expected snapshot command")
        };
        assert_eq!(args.chain, "sepolia");
        assert_eq!(args.builder_datadir.to_str(), Some("/tmp/builder"));
        assert!(args.prefund_address.is_some());
        assert_eq!(args.block_interval, DevnetBlockInterval::TwoHundredMilliseconds);
        assert!(args.block_gas_limit.is_none());
    }

    #[test]
    fn parses_light_command_defaults() {
        let cli = DevnetCli::try_parse_from(["base-devnet", "light"]).unwrap();

        let DevnetCommand::Light(args) = cli.command else { panic!("expected light command") };
        let config = args.stack_config();
        assert!(args.datadir.is_none());
        assert_eq!(config.block_interval, DevnetBlockInterval::TwoSeconds);
        assert!(config.ports.is_none());
        assert!(config.prefund.is_none());
        assert!(config.genesis_files.is_none());
        assert!(config.block_gas_limit.is_none());
        assert!(args.runtime_file.is_none());
    }

    #[test]
    fn parses_light_command() {
        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "light",
            "--datadir",
            "/tmp/light",
            "--block-interval",
            "200ms",
            "--stable-ports",
            "--block-gas-limit",
            "90000000",
            "--prefund-address",
            "0x0000000000000000000000000000000000000001",
            "--prefund-amount",
            "7",
            "--runtime-file",
            "/tmp/light.json",
            "--txpool-max-account-slots",
            "8",
        ])
        .unwrap();

        let DevnetCommand::Light(args) = cli.command else { panic!("expected light command") };
        let config = args.stack_config();
        assert_eq!(config.datadir.as_deref().and_then(|path| path.to_str()), Some("/tmp/light"));
        assert_eq!(config.block_interval, DevnetBlockInterval::TwoHundredMilliseconds);
        assert_eq!(config.ports.unwrap().l2_builder_http, 7545);
        assert_eq!(config.block_gas_limit, Some(90_000_000));
        assert_eq!(config.prefund.unwrap().amount, 7);
        assert_eq!(config.txpool_max_account_slots, 8);
        assert_eq!(
            args.runtime_file.as_deref().and_then(|path| path.to_str()),
            Some("/tmp/light.json")
        );
    }

    #[test]
    fn light_genesis_files_must_be_paired() {
        assert!(
            DevnetCli::try_parse_from(["base-devnet", "light", "--l2-genesis", "/tmp/g.json"])
                .is_err()
        );
        assert!(
            DevnetCli::try_parse_from(["base-devnet", "light", "--rollup-config", "/tmp/r.json"])
                .is_err()
        );

        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "light",
            "--l2-genesis",
            "/tmp/g.json",
            "--rollup-config",
            "/tmp/r.json",
        ])
        .unwrap();
        let DevnetCommand::Light(args) = cli.command else { panic!("expected light command") };
        assert!(args.stack_config().genesis_files.is_some());
    }

    #[test]
    fn light_rejects_gas_limit_with_custom_genesis() {
        assert!(
            DevnetCli::try_parse_from([
                "base-devnet",
                "light",
                "--l2-genesis",
                "/tmp/g.json",
                "--rollup-config",
                "/tmp/r.json",
                "--block-gas-limit",
                "1",
            ])
            .is_err()
        );
    }

    #[test]
    fn parses_snapshot_block_gas_limit() {
        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "snapshot",
            "--builder-datadir",
            "/tmp/builder",
            "--client-datadir",
            "/tmp/client",
            "--block-gas-limit",
            "12000000000",
        ])
        .unwrap();

        let DevnetCommand::Snapshot(args) = cli.command else {
            panic!("expected snapshot command")
        };
        assert_eq!(args.block_gas_limit.map(NonZeroU64::get), Some(12_000_000_000));
    }
}
