//! Command-line launcher for development networks.

use std::{
    net::{IpAddr, Ipv4Addr},
    path::PathBuf,
};

use alloy_primitives::{Address, B256};
use alloy_rpc_types_engine::JwtSecret;
use base_builder_cli::TransactionEventsArgs;
use base_observability_events::GlobalTransactionEventWriter;
use base_upgrade_signal::UpgradeSignalArgs;
use clap::{Args, Parser, Subcommand};
use eyre::{Result, WrapErr};
use serde::Serialize;
use url::Url;

use crate::{
    DevnetBlockInterval, DevnetConfig, DevnetL2State, DevnetPrefund, DevnetSnapshotHead,
    SequencerStack, SequencerStackConfig, SnapshotL2Stack, SystemTestStackBuilder,
};

/// Local Base development network launcher.
#[derive(Debug, Parser)]
#[command(author, version, about = "Run a local Base development network")]
pub struct DevnetCli {
    /// Development network mode.
    #[command(subcommand)]
    pub command: DevnetCommand,
}

/// Supported development network modes.
#[derive(Debug, Subcommand)]
pub enum DevnetCommand {
    /// Run a fresh builder and sequencer against an existing development L1.
    Fresh(Box<FreshArgs>),
    /// Continue Base mainnet snapshot datadirs without an L1.
    Snapshot(SnapshotArgs),
}

/// Arguments for the Docker-backed fresh development network sequencer.
#[derive(Debug, Args)]
pub struct FreshArgs {
    /// Fresh L2 genesis JSON generated by the devnet setup container.
    #[arg(long, default_value = "/genesis/l2/genesis.json")]
    pub l2_genesis: PathBuf,
    /// Rollup configuration generated by the devnet setup container.
    #[arg(long, default_value = "/genesis/l2/rollup.json")]
    pub rollup_config: PathBuf,
    /// L1 execution genesis JSON used by consensus derivation.
    #[arg(long, default_value = "/genesis/el/genesis.json")]
    pub l1_genesis: PathBuf,
    /// JWT secret shared by the embedded execution and consensus nodes.
    #[arg(long, default_value = "/genesis/jwt.hex")]
    pub jwt_secret: PathBuf,
    /// Persistent builder execution datadir.
    #[arg(long, default_value = "/data")]
    pub builder_datadir: PathBuf,
    /// L1 execution RPC endpoint reachable from the launcher.
    #[arg(long)]
    pub l1_rpc_url: Url,
    /// L1 beacon API endpoint reachable from the launcher.
    #[arg(long)]
    pub l1_beacon_url: Url,
    /// L1 slot duration override in seconds.
    #[arg(long, default_value_t = 12)]
    pub l1_slot_duration: u64,
    /// Builder execution and consensus P2P private key.
    #[arg(long, env = "BUILDER_P2P_KEY")]
    pub p2p_key: B256,
    /// Sequencer block-signing private key.
    #[arg(long, env = "SEQUENCER_KEY")]
    pub sequencer_key: B256,
    /// Address used by RPC, metrics, and Flashblocks listeners.
    #[arg(long, default_value = "0.0.0.0")]
    pub rpc_addr: IpAddr,
    /// Fixed container address advertised by execution and consensus P2P.
    #[arg(long, env = "L2_BUILDER_ADVERTISE_IP")]
    pub p2p_addr: IpAddr,
    /// Builder HTTP RPC port.
    #[arg(long, env = "L2_BUILDER_HTTP_PORT", default_value_t = 7545)]
    pub http_port: u16,
    /// Builder WebSocket RPC port.
    #[arg(long, env = "L2_BUILDER_WS_PORT", default_value_t = 7546)]
    pub ws_port: u16,
    /// Builder authenticated Engine API port.
    #[arg(long, env = "L2_BUILDER_AUTH_PORT", default_value_t = 7551)]
    pub auth_port: u16,
    /// Builder execution P2P port.
    #[arg(long, env = "L2_BUILDER_P2P_PORT", default_value_t = 7303)]
    pub p2p_port: u16,
    /// Builder Flashblocks WebSocket port.
    #[arg(long, env = "L2_BUILDER_FLASHBLOCKS_PORT", default_value_t = 7111)]
    pub flashblocks_port: u16,
    /// Builder Prometheus metrics port.
    #[arg(long, env = "L2_BUILDER_METRICS_PORT", default_value_t = 7090)]
    pub metrics_port: u16,
    /// Builder consensus RPC port.
    #[arg(long, env = "L2_BUILDER_CL_RPC_PORT", default_value_t = 7549)]
    pub consensus_rpc_port: u16,
    /// Builder consensus P2P TCP port.
    #[arg(long, env = "L2_BUILDER_CL_P2P_PORT", default_value_t = 7003)]
    pub consensus_p2p_port: u16,
    /// File containing consensus bootnode ENRs.
    #[arg(long, default_value = "/bootnodes/cl-bootnode.enr")]
    pub consensus_bootnodes_file: PathBuf,
    /// Enable the experimental validity transaction RPC and builder support.
    #[arg(long)]
    pub experimental_validity_transactions: bool,
    /// Cut the active payload builder over at Denim.
    #[arg(long)]
    pub payload_builder_cutover: bool,
    /// Pending/basefee/queued transaction count limit.
    #[arg(long, default_value_t = 200_000)]
    pub txpool_max_transactions: usize,
    /// Pending/basefee/queued transaction size limit in megabytes.
    #[arg(long, default_value_t = 512)]
    pub txpool_max_size_mb: usize,
    /// Maximum number of transaction slots retained per sender.
    #[arg(long, default_value_t = 256)]
    pub txpool_max_account_slots: usize,
    /// L1 upgrade signal configuration.
    #[command(flatten)]
    pub upgrade_signal: UpgradeSignalArgs,
    /// Dedicated builder transaction event journal configuration.
    #[command(flatten)]
    pub transaction_events: TransactionEventsArgs,
    /// Machine-readable endpoint output.
    #[arg(long, default_value = "/tmp/base-devnet-runtime.json")]
    pub runtime_file: PathBuf,
}

/// Machine-readable state emitted by the fresh devnet launcher.
#[derive(Debug, Serialize)]
pub struct FreshRuntime {
    /// Current launcher state.
    pub status: &'static str,
    /// Builder execution JSON-RPC URL.
    pub builder_rpc_url: String,
    /// Builder Flashblocks WebSocket URL.
    pub builder_flashblocks_url: String,
    /// Builder consensus JSON-RPC URL.
    pub builder_consensus_rpc_url: String,
}

/// Arguments for an L1-free Base mainnet snapshot network.
#[derive(Debug, Args)]
pub struct SnapshotArgs {
    /// Writable builder clone of a Base mainnet datadir.
    #[arg(long, env = "BASE_SNAPSHOT_BUILDER_DATADIR")]
    pub builder_datadir: PathBuf,
    /// Writable client clone of the same Base mainnet datadir.
    #[arg(long, env = "BASE_SNAPSHOT_CLIENT_DATADIR")]
    pub client_datadir: PathBuf,
    /// Bind the stable developer ports instead of allocating free ports.
    #[arg(long)]
    pub stable_ports: bool,
    /// Interval between locally produced blocks.
    #[arg(long, value_enum, default_value_t)]
    pub block_interval: DevnetBlockInterval,
    /// Account to mint ETH to in the first local descendant block.
    #[arg(long)]
    pub prefund_address: Option<Address>,
    /// Amount of wei minted to `--prefund-address`.
    #[arg(long, default_value_t = 1_000_000_000_000_000_000_000_u128)]
    pub prefund_amount: u128,
    /// Expected snapshot boundary block number.
    #[arg(long, requires_all = ["expected_head_hash", "expected_head_timestamp"])]
    pub expected_head_number: Option<u64>,
    /// Expected snapshot boundary block hash.
    #[arg(long, requires_all = ["expected_head_number", "expected_head_timestamp"])]
    pub expected_head_hash: Option<B256>,
    /// Expected snapshot boundary Unix timestamp.
    #[arg(long, requires_all = ["expected_head_number", "expected_head_hash"])]
    pub expected_head_timestamp: Option<u64>,
    /// Machine-readable endpoint and boundary output.
    #[arg(long, default_value = "runtime.json")]
    pub runtime_file: PathBuf,
}

/// Machine-readable state emitted by the snapshot devnet launcher.
#[derive(Debug, Serialize)]
pub struct SnapshotRuntime {
    /// Current launcher state.
    pub status: &'static str,
    /// L2 chain ID.
    pub chain_id: u64,
    /// Snapshot boundary block number.
    pub boundary_number: u64,
    /// Snapshot boundary block hash.
    pub boundary_hash: B256,
    /// Configured interval between local blocks, in milliseconds.
    pub block_interval_ms: u64,
    /// Builder execution JSON-RPC URL.
    pub builder_rpc_url: String,
    /// Builder Flashblocks WebSocket URL.
    pub builder_flashblocks_url: String,
    /// Client execution JSON-RPC URL.
    pub client_rpc_url: String,
}

impl DevnetCli {
    /// Runs the selected development network until interrupted.
    pub async fn run(self) -> Result<()> {
        match self.command {
            DevnetCommand::Fresh(args) => (*args).run().await,
            DevnetCommand::Snapshot(args) => args.run().await,
        }
    }

    /// Waits for an interactive interrupt or container termination signal.
    pub async fn shutdown_signal() -> Result<()> {
        #[cfg(unix)]
        {
            let mut terminate =
                tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
                    .wrap_err("failed to listen for SIGTERM")?;
            tokio::select! {
                result = tokio::signal::ctrl_c() => {
                    result.wrap_err("failed to listen for Ctrl-C")?;
                }
                _ = terminate.recv() => {}
            }
            Ok(())
        }

        #[cfg(not(unix))]
        tokio::signal::ctrl_c().await.wrap_err("failed to listen for Ctrl-C")
    }
}

impl FreshArgs {
    /// Starts a fresh builder and sequencer, writes its runtime manifest, and waits for shutdown.
    pub async fn run(self) -> Result<()> {
        let l2_genesis = std::fs::read(&self.l2_genesis)
            .wrap_err_with(|| format!("failed to read L2 genesis {}", self.l2_genesis.display()))?;
        let rollup_config = std::fs::read(&self.rollup_config).wrap_err_with(|| {
            format!("failed to read rollup config {}", self.rollup_config.display())
        })?;
        let l1_genesis = std::fs::read(&self.l1_genesis)
            .wrap_err_with(|| format!("failed to read L1 genesis {}", self.l1_genesis.display()))?;
        let jwt_secret_hex = std::fs::read_to_string(&self.jwt_secret)
            .wrap_err_with(|| format!("failed to read JWT secret {}", self.jwt_secret.display()))?;
        let jwt_secret = JwtSecret::from_hex(jwt_secret_hex.trim())
            .wrap_err("failed to parse builder JWT secret")?;
        let consensus_bootnodes = std::fs::read_to_string(&self.consensus_bootnodes_file)
            .wrap_err_with(|| {
                format!(
                    "failed to read consensus bootnodes {}",
                    self.consensus_bootnodes_file.display()
                )
            })?
            .split([',', '\n'])
            .map(str::trim)
            .filter(|bootnode| !bootnode.is_empty())
            .map(ToOwned::to_owned)
            .collect();

        GlobalTransactionEventWriter::init(Some(self.transaction_events.writer_config()))
            .wrap_err("failed to initialize builder transaction event journal")?;

        let stack = SequencerStack::start(SequencerStackConfig {
            l2_genesis,
            builder_datadir: Some(self.builder_datadir),
            require_existing_datadir: false,
            rollup_config,
            l1_genesis,
            jwt_secret,
            p2p_key: self.p2p_key,
            sequencer_key: self.sequencer_key,
            l1_rpc_url: self.l1_rpc_url,
            l1_beacon_url: self.l1_beacon_url,
            l1_slot_duration: self.l1_slot_duration,
            execution_rpc_addr: self.rpc_addr,
            execution_p2p_addr: self.p2p_addr,
            builder_http_port: Some(self.http_port),
            builder_ws_port: Some(self.ws_port),
            builder_auth_port: Some(self.auth_port),
            builder_p2p_port: Some(self.p2p_port),
            builder_flashblocks_port: Some(self.flashblocks_port),
            builder_metrics_port: Some(self.metrics_port),
            consensus_rpc_addr: self.rpc_addr,
            consensus_p2p_listen_addr: IpAddr::V4(Ipv4Addr::UNSPECIFIED),
            consensus_p2p_advertise_addr: self.p2p_addr,
            consensus_rpc_port: Some(self.consensus_rpc_port),
            consensus_p2p_tcp_port: Some(self.consensus_p2p_port),
            consensus_p2p_udp_port: Some(self.consensus_p2p_port),
            consensus_bootnodes,
            sequencer_stopped: false,
            enable_experimental_validity_transactions: self.experimental_validity_transactions,
            payload_builder_cutover: self.payload_builder_cutover,
            upgrade_signal: self.upgrade_signal.config(),
            extra_builder_extensions: Vec::new(),
            txpool_max_transactions: Some(self.txpool_max_transactions),
            txpool_max_size_mb: Some(self.txpool_max_size_mb),
            txpool_max_account_slots: Some(self.txpool_max_account_slots),
            clear_otel_env: false,
        })
        .await?;
        let runtime = FreshRuntime::ready(&stack)?;
        let encoded = serde_json::to_vec_pretty(&runtime)?;
        std::fs::write(&self.runtime_file, encoded).wrap_err_with(|| {
            format!("failed to write runtime manifest {}", self.runtime_file.display())
        })?;

        println!("fresh devnet sequencer ready");
        println!("builder RPC:   {}", runtime.builder_rpc_url);
        println!("consensus RPC: {}", runtime.builder_consensus_rpc_url);
        println!("runtime:       {}", self.runtime_file.display());
        DevnetCli::shutdown_signal().await?;
        stack.shutdown().await
    }
}

impl FreshRuntime {
    /// Captures ready endpoints from a running fresh sequencer stack.
    pub fn ready(stack: &SequencerStack) -> Result<Self> {
        Ok(Self {
            status: "ready",
            builder_rpc_url: stack.builder().rpc_url()?.to_string(),
            builder_flashblocks_url: stack.builder().flashblocks_url(),
            builder_consensus_rpc_url: stack.consensus().rpc_url().to_string(),
        })
    }
}

impl SnapshotArgs {
    /// Starts a snapshot-backed stack, writes its runtime manifest, and waits for shutdown.
    pub async fn run(self) -> Result<()> {
        let expected_head = match (
            self.expected_head_number,
            self.expected_head_hash,
            self.expected_head_timestamp,
        ) {
            (Some(number), Some(hash), Some(timestamp)) => {
                Some(DevnetSnapshotHead { number, hash, timestamp })
            }
            (None, None, None) => None,
            _ => unreachable!("clap requires all expected-head fields together"),
        };
        let mut config =
            DevnetConfig::base_mainnet_snapshot(self.builder_datadir, self.client_datadir);
        config.use_stable_ports = self.stable_ports;
        let DevnetL2State::Snapshot(snapshot) = &mut config.l2_state else {
            unreachable!("snapshot constructor must create snapshot state")
        };
        snapshot.expected_head = expected_head;
        snapshot.block_interval = self.block_interval;
        snapshot.prefund = self
            .prefund_address
            .map(|address| DevnetPrefund { address, amount: self.prefund_amount });
        config.validate()?;

        let stack =
            SystemTestStackBuilder::new().with_devnet_config(config).build_snapshot().await?;
        let runtime = SnapshotRuntime::ready(&stack)?;
        let encoded = serde_json::to_vec_pretty(&runtime)?;
        std::fs::write(&self.runtime_file, encoded).wrap_err_with(|| {
            format!("failed to write runtime manifest {}", self.runtime_file.display())
        })?;

        println!("snapshot devnet ready");
        println!("builder RPC: {}", runtime.builder_rpc_url);
        println!("client RPC:  {}", runtime.client_rpc_url);
        println!("runtime:     {}", self.runtime_file.display());
        println!("press Ctrl-C to stop");
        DevnetCli::shutdown_signal().await?;
        stack.shutdown().await?;
        Ok(())
    }
}

impl SnapshotRuntime {
    /// Captures the ready endpoints and immutable boundary from a running stack.
    pub fn ready(stack: &SnapshotL2Stack) -> Result<Self> {
        let boundary = stack.boundary();
        Ok(Self {
            status: "ready",
            chain_id: 8453,
            boundary_number: boundary.head.number,
            boundary_hash: boundary.head.hash,
            block_interval_ms: stack.block_interval().duration().as_millis() as u64,
            builder_rpc_url: stack.builder_rpc_url()?.to_string(),
            builder_flashblocks_url: stack.builder_flashblocks_url()?.to_string(),
            client_rpc_url: stack.client_rpc_url()?.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use clap::Parser;

    use super::{DevnetCli, DevnetCommand};
    use crate::DevnetBlockInterval;

    #[test]
    fn parses_fresh_command() {
        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "fresh",
            "--l1-rpc-url",
            "http://l1-el:4545",
            "--l1-beacon-url",
            "http://l1-cl:4052",
            "--p2p-key",
            "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6",
            "--sequencer-key",
            "0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba",
            "--p2p-addr",
            "172.30.0.20",
        ])
        .unwrap();

        let DevnetCommand::Fresh(args) = cli.command else { panic!("expected fresh command") };
        assert_eq!(args.http_port, 7545);
        assert_eq!(args.consensus_p2p_port, 7003);
        assert_eq!(args.l1_rpc_url.as_str(), "http://l1-el:4545/");
    }

    #[test]
    fn parses_snapshot_command() {
        let cli = DevnetCli::try_parse_from([
            "base-devnet",
            "snapshot",
            "--builder-datadir",
            "/tmp/builder",
            "--client-datadir",
            "/tmp/client",
            "--prefund-address",
            "0x0000000000000000000000000000000000000001",
            "--block-interval",
            "200ms",
        ])
        .unwrap();

        let DevnetCommand::Snapshot(args) = cli.command else {
            panic!("expected snapshot command")
        };
        assert_eq!(args.builder_datadir.to_str(), Some("/tmp/builder"));
        assert!(args.prefund_address.is_some());
        assert_eq!(args.block_interval, DevnetBlockInterval::TwoHundredMilliseconds);
    }
}
