[package]
name = "base-execution-evm-machine"
description = "Base EVM context, journal, and bytecode interpreter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
]

[dependencies]
bitvec = { workspace = true }
cfg-if = { workspace = true }
either = { workspace = true }
auto_impl = { workspace = true }
derive-where = { workspace = true }
alloy-eip2930 = { workspace = true }
base-execution-state-memory = {workspace = true}
base-execution-evm-primitives = {workspace = true}
alloy-eip7702 = { workspace = true, features = ["k256"] }
serde = {features = ["derive", "rc"], optional = true, workspace = true}

[lints]
workspace = true

[dev-dependencies]
serde_json = { workspace = true, features = ["alloc"] }

[[test]]
name = "miri_read_slice_oob"
path = "tests/miri_read_slice_oob.rs"

[features]
default = ["std"]
dev = ["memory_limit", "optional_balance_check", "optional_block_gas_limit", "optional_eip3541", "optional_eip3607", "optional_eip7623", "optional_no_base_fee", "optional_priority_fee_check", "optional_fee_charge"]
map-foldhash = ["base-execution-evm-primitives/map-foldhash", "base-execution-state-memory/map-foldhash"]
memory_limit = []
optional_balance_check = []
optional_block_gas_limit = []
optional_eip3541 = []
optional_eip3607 = []
optional_eip7623 = []
optional_fee_charge = []
optional_no_base_fee = []
optional_priority_fee_check = []
serde = ["dep:serde", "base-execution-evm-primitives/serde", "base-execution-state-memory/serde", "derive-where/serde", "bitvec/serde", "alloy-eip7702/serde", "alloy-eip2930/serde", "either/serde"]
std = ["serde?/std", "base-execution-evm-primitives/std", "base-execution-state-memory/std", "bitvec/std", "alloy-eip7702/std", "alloy-eip2930/std", "either/std", "serde_json/std"]
serde-json = ["serde"]
arbitrary = ["std", "base-execution-evm-primitives/arbitrary"]
hashbrown = ["base-execution-evm-primitives/hashbrown"]

