services:
  base-builder:
    environment:
      BASE_NODE_UPGRADE_SIGNAL_CONTRACT: ${UPGRADE_SIGNAL_CONTRACT:?run etc/scripts/devnet/setup-upgrade-signal.sh first}
      BASE_NODE_UPGRADE_SIGNAL_L1_RPC: ${UPGRADE_SIGNAL_L1_RPC:-http://l1-el:4545}

  base-builder-cl:
    environment:
      BASE_NODE_UPGRADE_SIGNAL_CONTRACT: ${UPGRADE_SIGNAL_CONTRACT:?run etc/scripts/devnet/setup-upgrade-signal.sh first}

  base-client:
    environment:
      BASE_NODE_UPGRADE_SIGNAL_CONTRACT: ${UPGRADE_SIGNAL_CONTRACT:?run etc/scripts/devnet/setup-upgrade-signal.sh first}
      BASE_NODE_UPGRADE_SIGNAL_L1_RPC: ${UPGRADE_SIGNAL_L1_RPC:-http://l1-el:4545}

  base-client-cl:
    environment:
      BASE_NODE_UPGRADE_SIGNAL_CONTRACT: ${UPGRADE_SIGNAL_CONTRACT:?run etc/scripts/devnet/setup-upgrade-signal.sh first}

  base-rpc:
    environment:
      BASE_NODE_UPGRADE_SIGNAL_CONTRACT: ${UPGRADE_SIGNAL_CONTRACT:?run etc/scripts/devnet/setup-upgrade-signal.sh first}
