//! End-to-end test for the conductor SSZ-binary commit client.
//!
//! Skipped unless `BINARY_COMMIT_E2E_URL` and `BINARY_COMMIT_E2E_PAYLOAD` are
//! set, because it requires a running op-conductor (with the binary endpoint)
//! reachable at the URL plus an SSZ payload file generated by op-conductor's
//! eth.ExecutionPayloadEnvelope.MarshalSSZ.
//!
//! Driven from /tmp/oc-smoke/run.sh.

use std::path::PathBuf;

use base_common_rpc_types_engine::BaseExecutionPayloadEnvelope;
use base_consensus_node::{Conductor, ConductorClient};
use ssz::{Decode, Encode};
use url::Url;

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn binary_commit_e2e_against_real_conductor() {
    let Some(url) = env_url("BINARY_COMMIT_E2E_URL") else {
        eprintln!("skip: BINARY_COMMIT_E2E_URL not set");
        return;
    };
    let Some(path) = env_path("BINARY_COMMIT_E2E_PAYLOAD") else {
        eprintln!("skip: BINARY_COMMIT_E2E_PAYLOAD not set");
        return;
    };

    // 1. Load the SSZ bytes that Go produced via eth.ExecutionPayloadEnvelope.MarshalSSZ.
    let go_bytes = std::fs::read(&path).expect("read payload");
    eprintln!("loaded {} bytes of Go-produced SSZ", go_bytes.len());

    // 2. Decode them via Rust ssz::Decode. If the wire format is incompatible
    //    this fails immediately.
    let envelope = BaseExecutionPayloadEnvelope::from_ssz_bytes(&go_bytes)
        .expect("Rust ssz::Decode of Go-encoded envelope failed (wire incompatibility)");

    // 3. Re-encode via Rust ssz::Encode. Byte-equal to the Go-produced bytes
    //    proves Rust's encoder is symmetric with Go's.
    let rust_bytes = envelope.as_ssz_bytes();
    assert_eq!(
        rust_bytes, go_bytes,
        "Rust SSZ re-encode does not match Go SSZ output (wire format drift)"
    );
    eprintln!("Rust SSZ re-encode matches Go output byte-for-byte");

    // 4. Send via the public ConductorClient API with the binary commit path.
    //    This exercises everything: BinaryCommitClient -> reqwest POST ->
    //    op-conductor BinaryCommitHandler -> raft.Apply -> FSM SSZ unmarshal.
    let client = ConductorClient::new_http_with_binary_commit(url)
        .expect("construct ConductorClient with binary commit");

    client
        .commit_unsafe_payload(&envelope)
        .await
        .expect("commit_unsafe_payload via binary endpoint failed");

    eprintln!("commit_unsafe_payload via binary endpoint succeeded");
}

fn env_url(key: &str) -> Option<Url> {
    std::env::var(key).ok().and_then(|s| Url::parse(&s).ok())
}

fn env_path(key: &str) -> Option<PathBuf> {
    std::env::var(key).ok().map(PathBuf::from)
}
