[package]
name = "base-cli-utils"
description = "CLI Utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
metrics = { workspace = true }
dirs-next = { workspace = true }
alloy-genesis = { workspace = true }
reth-node-core = { workspace = true }
tracing-appender = { workspace = true }
opentelemetry_sdk = { workspace = true }
base-common-runtime-tasks = { workspace = true }
eyre = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["alloc"] }
tokio-util = { workspace = true, features = ["default"] }
serde = { workspace = true, features = ["derive", "std"] }
opentelemetry = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["std", "attributes"] }
metrics-process = { workspace = true, features = ["metrics-rs"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
base-common-observability-metrics = { workspace = true, features = ["metrics"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }
base-common-observability-tracing = { workspace = true, optional = true, features = ["otlp"] }
tokio = { workspace = true, features = ["default", "full", "macros", "rt-multi-thread", "signal"] }
tracing-subscriber = { workspace = true, features = ["default", "fmt", "env-filter", "json", "tracing-log"] }

[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true, features = ["default"] }
backtrace = { workspace = true, features = ["default"] }

[features]
otlp = ["dep:base-common-observability-tracing", "reth-node-core/otlp", "base-common-observability-tracing/otlp"]
