[package]
name = "base-cli-utils"
description = "CLI Utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
metrics = { workspace = true }
dirs-next = { workspace = true }
reth-node-core = { workspace = true }
tracing-appender = { workspace = true }
opentelemetry_sdk = { workspace = true }
tracing = { workspace = true, features = ["std"] }
eyre = { workspace = true, features = ["default"] }
tokio-util = { workspace = true, features = ["default"] }
serde = { workspace = true, features = ["derive", "std"] }
base-metrics = { workspace = true, features = ["metrics"] }
opentelemetry = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "full"] }
metrics-process = { workspace = true, features = ["metrics-rs"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }
reth-tracing-otlp = { workspace = true, optional = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = ["default", "fmt", "env-filter", "json", "tracing-log"] }
[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
rstest = { workspace = true, features = ["default"] }
[target.'cfg(unix)'.dependencies]
libc = { workspace = true, features = ["default"] }
backtrace = { workspace = true, features = ["default"] }
[features]
otlp = [
	"dep:reth-tracing-otlp",
	"reth-node-core/otlp",
	"reth-tracing-otlp/otlp",
]
