[package]
name = "audit-archiver-lib"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
jsonrpsee-types = { workspace = true }
metrics = { workspace = true, optional = true }
base-observability-events = { workspace = true }
tracing = { workspace = true, features = ["std"] }
base-execution-payload-types = { workspace = true }
bytes = { workspace = true, features = ["default"] }
thiserror = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
futures = { workspace = true, features = ["default"] }
serde = { workspace = true, features = ["std", "derive"] }
moka = { workspace = true, features = ["default", "sync"] }
anyhow = { workspace = true, features = ["default", "std"] }
tokio = { workspace = true, features = ["default", "full"] }
chrono = { workspace = true, features = ["default", "serde"] }
axum = { workspace = true, features = ["tokio", "http1", "json"] }
base-common-types-chain = { workspace = true, features = ["std"] }
uuid = { workspace = true, features = ["default", "v5", "serde"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
tower-http = { workspace = true, features = ["default", "limit", "timeout"] }
base-common-observability-metrics = { workspace = true, features = ["metrics"] }
jsonrpsee = { workspace = true, features = ["server", "macros", "http-client"] }
aws-sdk-s3 = { workspace = true, features = ["rustls", "default-https-client", "rt-tokio"] }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "chrono", "json", "migrate", "macros", "tls-native-tls"] }

[dev-dependencies]
testcontainers = { workspace = true, features = ["blocking"] }
base-execution-payload-types = { workspace = true, features = ["test-utils"] }
testcontainers-modules = { workspace = true, features = ["postgres", "minio"] }
aws-config = { workspace = true, features = ["default-https-client", "rt-tokio"] }

[features]
default = ["metrics"]
metrics = [
    "base-common-observability-metrics/metrics",
    "base-observability-events/metrics",
    "dep:metrics",
    "tower-http/metrics",
]
