[package]
name = "base-execution-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude = [".github/"]

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
alloy-trie = { workspace = true }
alloy-eips = { workspace = true }
base-protocol = { workspace = true }
alloy-hardforks = { workspace = true }
base-evm-handler = { workspace = true }
reth-storage-errors = { workspace = true }
reth-primitives-traits = { workspace = true }
alloy-eip7928 = { workspace = true, features = ["rlp"] }
reth-storage-api = { workspace = true, features = ["default"] }
reth-trie-common = { workspace = true, features = ["default"] }
base-common-chains = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"]}
base-execution-chainspec = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["reth"], optional = false}
reth-execution-types = { workspace = true, features = ["default"], optional = false}
[dev-dependencies]
reth-trie = { workspace = true }
alloy-chains = { workspace = true }
reth-db-common = { workspace = true }
alloy-hardforks = { workspace = true }
base-common-genesis = { workspace = true }
rand = { workspace = true, features = ["default"] }
reth-provider = { workspace = true, features = ["test-utils"] }
base-execution-evm = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["reth", "serde"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "rand"] }

[features]
default = ["std"]
std = [
    "alloy-chains/std",
    "base-common-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-trie/std",
    "base-common-chains/std",
    "base-common-consensus/std",
    "base-execution-chainspec/std",
    "base-protocol/std",
    "reth-execution-types/std",
    "reth-primitives-traits/std",
    "base-execution-evm/std",
    "reth-storage-api/std",
    "reth-storage-errors/std",
    "reth-trie-common/std",
    "base-evm-handler/std",
    "thiserror/std",
    "tracing/std",
    "alloy-eip7928/std",
]
test-utils = [
    "std",
    "reth-primitives-traits/test-utils",
]
