//! `StorableType`, `FromWord`, and `StorageKey` implementations for single-word primitives.
//!
//! Covers Rust integers, Alloy integers, Alloy fixed bytes, `bool`, and `Address`.

use alloy_primitives::{Address, U256};

use crate::{
    provider::{
        FromWord, Layout, LayoutCtx, Packable, StorableType, StorageKey, sealed::OnlyPrimitives,
    },
    types::Slot,
};

// Rust integers: (u)int8, (u)int16, (u)int32, (u)int64, (u)int128
base_precompile_macros::storable_rust_ints!();
// Alloy integers: U8, I8, U16, I16, U32, I32, U64, I64, U128, I128, U256, I256
base_precompile_macros::storable_alloy_ints!();
// Alloy fixed bytes: FixedBytes<1> .. FixedBytes<32>
base_precompile_macros::storable_alloy_bytes!();

// -- BOOL ---------------------------------------------------------------------

impl StorableType for bool {
    const LAYOUT: Layout = Layout::Bytes(1);
    type Handler<'a> = Slot<'a, Self>;
    fn handle<'a>(
        slot: U256,
        ctx: LayoutCtx,
        address: Address,
        storage: crate::StorageCtx<'a>,
    ) -> Self::Handler<'a> {
        Slot::new_with_ctx(slot, ctx, address, storage)
    }
}

impl OnlyPrimitives for bool {}
impl Packable for bool {}

impl FromWord for bool {
    #[inline]
    fn to_word(&self) -> U256 {
        if *self { U256::ONE } else { U256::ZERO }
    }
    #[inline]
    fn from_word(word: U256) -> crate::error::Result<Self> {
        Ok(!word.is_zero())
    }
}

impl StorageKey for bool {
    #[inline]
    fn as_storage_bytes(&self) -> impl AsRef<[u8]> {
        if *self { [1u8] } else { [0u8] }
    }
}

// -- ADDRESS ------------------------------------------------------------------

impl StorableType for Address {
    const LAYOUT: Layout = Layout::Bytes(20);
    type Handler<'a> = Slot<'a, Self>;
    fn handle<'a>(
        slot: U256,
        ctx: LayoutCtx,
        address: Address,
        storage: crate::StorageCtx<'a>,
    ) -> Self::Handler<'a> {
        Slot::new_with_ctx(slot, ctx, address, storage)
    }
}

impl OnlyPrimitives for Address {}
impl Packable for Address {}

impl FromWord for Address {
    #[inline]
    fn to_word(&self) -> U256 {
        // Left-pad 20-byte address to 32 bytes (right-aligned in the word)
        let mut bytes = [0u8; 32];
        bytes[12..].copy_from_slice(self.as_slice());
        U256::from_be_bytes(bytes)
    }
    #[inline]
    fn from_word(word: U256) -> crate::error::Result<Self> {
        // Take the low 20 bytes (right-aligned)
        Ok(Self::from_slice(&word.to_be_bytes::<32>()[12..]))
    }
}

impl StorageKey for Address {
    #[inline]
    fn as_storage_bytes(&self) -> impl AsRef<[u8]> {
        // Return the raw bytes as a fixed-size array (no unsized dereference)
        let mut arr = [0u8; 20];
        arr.copy_from_slice(self.as_slice());
        arr
    }
}

// B256 = FixedBytes<32>: StorageKey and OnlyPrimitives are generated by storable_alloy_bytes!()
// We only need to add the type alias mapping here so that B256 can be used as a mapping key.
// (storable_alloy_bytes!() generates impls for FixedBytes<N>, and B256 = FixedBytes<32>)

#[cfg(test)]
mod tests {
    use proptest::prelude::*;

    use super::*;
    use crate::{
        hashmap::setup_storage,
        provider::{Handler, LayoutCtx},
        storage_ctx::StorageCtx,
    };

    fn arb_safe_slot() -> impl Strategy<Value = U256> {
        any::<[u64; 4]>()
            .prop_map(|limbs| U256::from_limbs(limbs) % (U256::MAX - U256::from(10000u64)))
    }

    fn arb_address() -> impl Strategy<Value = Address> {
        any::<[u8; 20]>().prop_map(Address::from)
    }

    // Generate property tests for all primitive storage types
    base_precompile_macros::gen_storable_tests!();

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(500))]

        #[test]
        fn test_address(addr in arb_address(), base_slot in arb_safe_slot()) {
            let (mut storage, address) = setup_storage();
            StorageCtx::enter(&mut storage, |ctx| {
                let mut slot = Address::handle(base_slot, LayoutCtx::FULL, address, ctx);

                slot.write(addr).unwrap();
                let loaded = slot.read().unwrap();
                assert_eq!(addr, loaded, "Address roundtrip failed");

                slot.delete().unwrap();
                let after_delete = slot.read().unwrap();
                assert_eq!(after_delete, Address::ZERO, "Address not zero after delete");

                let word = addr.to_word();
                let recovered = <Address as FromWord>::from_word(word).unwrap();
                assert_eq!(addr, recovered, "Address EVM word roundtrip failed");
            });
        }

        #[test]
        fn test_bool_values(b in any::<bool>(), base_slot in arb_safe_slot()) {
            let (mut storage, address) = setup_storage();
            StorageCtx::enter(&mut storage, |ctx| {
                let mut slot = bool::handle(base_slot, LayoutCtx::FULL, address, ctx);

                slot.write(b).unwrap();
                let loaded = slot.read().unwrap();
                assert_eq!(b, loaded, "Bool roundtrip failed for value: {b}");

                slot.delete().unwrap();
                let after_delete = slot.read().unwrap();
                assert!(!after_delete, "Bool not false after delete");

                let word = b.to_word();
                let recovered = <bool as FromWord>::from_word(word).unwrap();
                assert_eq!(b, recovered, "Bool EVM word roundtrip failed");
            });
        }
    }
}
