[package]
name = "base-proof-tee-registrar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
aws-sdk-ec2 = { workspace = true }
alloy-signer = { workspace = true }
base-proof-l1 = { workspace = true }
base-common-l1 = { workspace = true }
alloy-sol-types = { workspace = true }
base-common-cli = { workspace = true }
alloy-primitives = { workspace = true }
metrics = { workspace = true, optional = true }
hex = { workspace = true, features = ["default"] }
url = { workspace = true, features = ["default"] }
base-proof-tee-nitro-verifier = { workspace = true }
aws-sdk-elasticloadbalancingv2 = { workspace = true }
futures = { workspace = true, features = ["default"] }
reqwest = { workspace = true, features = ["default"] }
ciborium = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
tokio-util = { workspace = true, features = ["default"] }
x509-parser = { workspace = true, features = ["default"] }
k256 = { workspace = true, features = ["default", "ecdsa"] }
rustls = { workspace = true, features = ["default", "ring"] }
base-proof-types = { workspace = true, features = ["rpc-client"] }
base-common-http = { workspace = true, features = ["axum-server"] }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
base-common-client-ethereum = { workspace = true, features = ["default"] }
p384 = { workspace = true, features = ["default", "ecdsa", "expose-field"] }
aws-config = { workspace = true, features = ["default-https-client", "rt-tokio"] }
tokio = { workspace = true, features = ["default", "rt", "sync", "net", "time", "macros"] }

[dev-dependencies]
async-trait = { workspace = true }
hex-literal = { workspace = true }
base-common-types-rpc = { workspace = true }
base-common-types-chain = { workspace = true }
metrics-util = { workspace = true, features = ["debugging"] }
tokio = { workspace = true, features = ["default", "rt", "macros", "test-util"] }

[features]
metrics = ["base-common-observability-metrics/metrics", "base-common-l1/metrics", "dep:metrics"]
