[package]
name = "base-proof-tee-registrar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
aws-sdk-ec2 = { workspace = true }
base-metrics = { workspace = true }
alloy-signer = { workspace = true }
base-cli-utils = { workspace = true }
alloy-sol-types = { workspace = true }
base-tx-manager = { workspace = true }
alloy-primitives = { workspace = true }
base-proof-contracts = { workspace = true }
base-balance-monitor = { workspace = true }
metrics = { workspace = true, optional = true }
url = { workspace = true, features = ["default"] }
hex = { workspace = true, features = ["default"] }
base-proof-tee-nitro-verifier = { workspace = true }
aws-sdk-elasticloadbalancingv2 = { workspace = true }
reqwest = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
ciborium = { workspace = true, features = ["default"] }
tokio-util = { workspace = true, features = ["default"] }
x509-parser = { workspace = true, features = ["default"] }
k256 = { workspace = true, features = ["default", "ecdsa"] }
alloy-provider = { workspace = true, features = ["default"] }
rustls = { workspace = true, features = ["default", "ring"] }
base-health = { workspace = true, features = ["axum-server"] }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
base-proof-primitives = { workspace = true, features = ["rpc-client"] }
p384 = { workspace = true, features = ["default", "ecdsa", "expose-field"] }
aws-config = { workspace = true, features = ["default-https-client", "rt-tokio"] }
tokio = { workspace = true, features = ["default", "rt", "sync", "net", "time", "macros"] }
[dev-dependencies]
hex-literal = { workspace = true }
async-trait = { workspace = true }
alloy-consensus = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
metrics-util = { workspace = true, features = ["debugging"] }
tokio = { workspace = true, features = ["default", "rt", "macros", "test-util"] }
[features]
metrics = [ "base-metrics/metrics", "base-tx-manager/metrics", "dep:metrics" ]
