[package]
name = "base-execution-payload-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
either = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
base-execution-state-types = { workspace = true }
reth-storage-errors = {workspace = true}
reth-execution-types = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-evm-fees = { workspace = true }
base-execution-evm-runtime = {workspace = true}
tokio = { workspace = true, features = ["sync"] }
pin-project = { workspace = true, optional = true}
serde = {features = ["derive", "std"], workspace = true}
alloy-rlp = { workspace = true, features = ["core-net"] }
base-common-network = { workspace = true, optional = true }
uuid = { workspace = true, features = ["default", "v4", "serde"] }
base-common-types-payload = {workspace = true, features = ["serde"]}
tracing = { workspace = true, features = ["attributes"], optional = true}
alloy-primitives = {features = ["map-foldhash", "serde"], workspace = true}
tokio-stream = { workspace = true, features = ["default", "sync"], optional = true}
base-common-types-chain = {features = ["k256", "reth", "serde", "std"], workspace = true}
base-common-types-rpc = { workspace = true, features = ["default", "std"], optional = true }

[dev-dependencies]
assert_matches = { workspace = true }
base-common-network = { workspace = true }
base-common-chain-config = {workspace = true}
serde_json = {features = ["alloc", "std"], workspace = true}
base-common-types-rpc = { workspace = true, features = ["default", "std"] }

[features]
default = ["std"]
std = [
    "base-common-types-payload/std",
    "reth-execution-types/std",
    "base-execution-state-types/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "serde/std",
    "thiserror/std",
    "reth-primitives-traits/std",
    "either/std",
    "base-common-types-chain/std",
    "alloy-rlp/std",
    "serde_json/std",
    "sha2/std",
    "dep:pin-project",
    "dep:tracing",
    "dep:tokio-stream",
]
test-utils = ["dep:base-common-network", "dep:base-common-types-rpc"]
