[package]
name = "base-execution-state-api"
description = "Reth storage provider traits and types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
auto_impl = { workspace = true }
alloy-eips = { workspace = true }
base-common-chain-config = { workspace = true }
base-common-types-chain = {features = ["k256"], workspace = true}
base-execution-state-types = {workspace = true}
base-common-types-payload = { workspace = true }
base-execution-state-memory = {workspace = true}
alloy-hardforks = { workspace = true, optional = true }
alloy-eip7928 = { workspace = true, features = ["rlp"] }
base-common-runtime-tasks = { workspace = true, optional = true }
alloy-primitives = { workspace = true, features = ["map-foldhash"] }
base-execution-state-database = { workspace = true, optional = true }
serde_json = { workspace = true, features = ["alloc"], optional = true }

[dev-dependencies]
mockall = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-stream = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "getrandom"] }

[features]
default = ["std"]
std = ["base-common-types-chain/std", "alloy-eips/std", "alloy-primitives/std", "base-common-types-payload/std", "base-common-types-chain/std", "base-execution-state-types/std", "base-execution-state-memory/std", "serde_json?/std", "dep:base-common-runtime-tasks", "alloy-eip7928/std"]

db-api = ["dep:alloy-hardforks", "dep:base-execution-state-database", "dep:serde_json"]

serde = ["base-execution-state-types/serde", "base-common-types-chain/serde", "base-execution-state-memory/serde", "alloy-eips/serde", "alloy-primitives/serde", "base-common-types-chain/serde", "base-common-types-payload/serde", "alloy-eip7928/serde"]

serde-bincode-compat = ["base-execution-state-types/serde-bincode-compat", "alloy-eips/serde-bincode-compat", "base-common-types-chain/serde-bincode-compat"]
