// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProofRequest is the predicate function for proofrequest builders.
type ProofRequest func(*sql.Selector)
