[package]
name = "base-consensus-upgrades"
version.workspace = true
description = "Consensus upgrade types for Base"

edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
alloy-eips = { workspace = true }
base-common-consensus = { workspace = true }
alloy-primitives = { workspace = true, features = ["rlp"] }
[dev-dependencies]
revm = { workspace = true }
base-common-evm = { workspace = true }
rstest = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["rand", "arbitrary"] }
[features]
default = []
std = [ "alloy-eips/std", "alloy-primitives/std", "base-common-consensus/std" ]
k256 = [ "alloy-primitives/k256", "base-common-consensus/k256" ]
kzg = [ "alloy-eips/kzg", "base-common-consensus/kzg", "std" ]
