//! Postgres integration tests for transaction event ingest.
//!
//! Run with:
//!
//! ```bash
//! DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres \
//!   cargo test -p audit-archiver-lib --test postgres_transaction_events -- --ignored
//! ```

use std::{
    path::PathBuf,
    sync::Arc,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use audit_archiver_lib::{
    AuditArchiverApiServer, AuditArchiverRpc, DEFAULT_TRANSACTION_EVENT_BATCH_PATH,
    DEFAULT_TRANSACTION_EVENT_MAX_BATCH_SIZE, DEFAULT_TRANSACTION_EVENT_MAX_DATA_BYTES,
    DEFAULT_TRANSACTION_EVENT_MAX_EVENT_BYTES, DEFAULT_TRANSACTION_EVENT_MAX_REQUEST_BYTES,
    MAX_TRANSACTION_EVENT_INSERT_BATCH_SIZE, PgTransactionEventSink, RejectedTransactionEventQuery,
    TransactionEventIngestConfig, TransactionEventRecord, TransactionEventRetentionConfig,
    TransactionEventSchemaReadinessError, TransactionEventSink, index_transaction_event_partitions,
};
use axum::{
    body::{Body, to_bytes},
    http::{Request, StatusCode},
};
use base_observability_events::TransactionEvent;
use chrono::{DateTime, Utc};
use serde_json::{Value, json};
use sqlx::{Executor, PgPool, migrate::Migrator, postgres::PgPoolOptions};
use testcontainers::{ImageExt, core::ExecCommand, runners::AsyncRunner};
use testcontainers_modules::postgres::Postgres;
use tower::ServiceExt;

/// Production RDS is Postgres 17. `testcontainers-modules` still defaults to
/// Postgres 11, which lacks the partitioning features the schema relies on.
const POSTGRES_TAG: &str = "17-alpine";

/// Hot class day partitions of the v2 tree, which ingest writes.
const HOT_PARTITIONS_SQL: &str = "SELECT c.relname::text FROM pg_inherits i \
     JOIN pg_class c ON c.oid = i.inhrelid \
     WHERE i.inhparent = 'transaction_events_v2_hot'::regclass \
     ORDER BY c.relname";

/// Day partitions of the legacy tree, across all classes.
const LEGACY_PARTITIONS_SQL: &str = "SELECT c.relname::text FROM pg_inherits i \
     JOIN pg_class c ON c.oid = i.inhrelid \
     WHERE i.inhparent IN ('transaction_events_hot'::regclass, \
         'transaction_events_warm'::regclass, 'transaction_events_cold'::regclass) \
     ORDER BY c.relname";

/// Transaction hash shared by legacy and v2 rows in read-through tests.
const SHARED_TX_HASH: &str = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

/// Block hash shared by legacy and v2 rows in read-through tests.
const SHARED_BLOCK_HASH: &str =
    "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

/// Block number shared by legacy and v2 rows in read-through tests.
const SHARED_BLOCK_NUMBER: u64 = 456;

/// Bundle hash shared by legacy and v2 rows in read-through tests.
const SHARED_BUNDLE_HASH: &str = "0xbundle-shared";

/// Committed schema that the migrations must produce, from any starting state.
const SCHEMA_SNAPSHOT_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/schema.sql");

/// Set to rewrite [`SCHEMA_SNAPSHOT_PATH`] instead of comparing against it.
const UPDATE_SCHEMA_SNAPSHOT_ENV: &str = "UPDATE_SCHEMA_SNAPSHOT";

const SCHEMA_SNAPSHOT_HEADER: &str = "-- Schema produced by crates/infra/audit/migrations, excluding dated day\n\
     -- partitions and _sqlx_migrations. Generated by the postgres_transaction_events\n\
     -- tests; regenerate with UPDATE_SCHEMA_SNAPSHOT=1 instead of editing by hand.\n";

struct PostgresHarness {
    port: u16,
    database_url: String,
    container: testcontainers::ContainerAsync<Postgres>,
}

impl PostgresHarness {
    async fn new() -> anyhow::Result<Self> {
        let container = Postgres::default().with_tag(POSTGRES_TAG).start().await?;
        let port = container.get_host_port_ipv4(5432).await?;
        let database_url = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");
        Ok(Self { port, database_url, container })
    }

    fn url_for(&self, user: &str, password: &str) -> String {
        format!("postgres://{user}:{password}@127.0.0.1:{}/postgres", self.port)
    }

    /// Normalized schema-only `pg_dump` of the database.
    ///
    /// Day partitions are excluded because their names depend on the current
    /// date. sqlx's history table and `pg_dump`'s version-specific preamble are
    /// excluded because they are not part of the audit schema.
    async fn schema_dump(&self) -> anyhow::Result<String> {
        let mut result = self
            .container
            .exec(ExecCommand::new([
                "pg_dump",
                "--username=postgres",
                "--dbname=postgres",
                "--schema-only",
                "--no-owner",
                "--exclude-table=_sqlx_migrations",
                "--exclude-table=transaction_events_*_2*",
            ]))
            .await?;
        let stdout = String::from_utf8(result.stdout_to_vec().await?)?;
        let stderr = String::from_utf8(result.stderr_to_vec().await?)?;
        anyhow::ensure!(result.exit_code().await? == Some(0), "pg_dump failed: {stderr}");

        let mut lines: Vec<&str> = Vec::new();
        for line in stdout.lines() {
            let preamble =
                ["--", "\\restrict", "\\unrestrict", "SET ", "SELECT pg_catalog.set_config"]
                    .iter()
                    .any(|prefix| line.starts_with(prefix));
            let repeated_blank = line.is_empty() && lines.last().is_none_or(|last| last.is_empty());
            if !preamble && !repeated_blank {
                lines.push(line);
            }
        }
        while lines.last().is_some_and(|last| last.is_empty()) {
            lines.pop();
        }
        Ok(format!("{SCHEMA_SNAPSHOT_HEADER}\n{}\n", lines.join("\n")))
    }

    /// Asserts the schema matches the committed snapshot, or rewrites the
    /// snapshot when [`UPDATE_SCHEMA_SNAPSHOT_ENV`] is set.
    async fn assert_schema_matches_snapshot(&self) -> anyhow::Result<()> {
        let dump = self.schema_dump().await?;
        if std::env::var_os(UPDATE_SCHEMA_SNAPSHOT_ENV).is_some() {
            std::fs::write(SCHEMA_SNAPSHOT_PATH, dump)?;
            return Ok(());
        }
        let expected = std::fs::read_to_string(SCHEMA_SNAPSHOT_PATH)?;
        assert_eq!(
            dump, expected,
            "schema differs from crates/infra/audit/schema.sql; if the change is intended, rerun with {UPDATE_SCHEMA_SNAPSHOT_ENV}=1 and review the diff"
        );
        Ok(())
    }

    /// Creates the runtime and extraction roles, so the migrations' grants
    /// appear in the schema.
    async fn create_grantee_roles(&self) -> anyhow::Result<()> {
        let pool = PgPoolOptions::new().max_connections(1).connect(&self.database_url).await?;
        pool.execute("CREATE ROLE audit_archiver NOLOGIN").await?;
        pool.execute("CREATE ROLE datapilot NOLOGIN").await?;
        Ok(())
    }
}

fn unique_event_id() -> String {
    let nanos = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos();
    format!("postgres-integration-{nanos}")
}

fn event(event_id: &str) -> TransactionEvent {
    event_with_type(event_id, "BUILDER_ACCEPTED")
}

fn event_with_type(event_id: &str, event_type: &str) -> TransactionEvent {
    serde_json::from_value(json!({
        "schema_version": "transaction-event/v1",
        "event_id": event_id,
        "event_time": Utc::now(),
        "producer": "base-builder",
        "event_type": event_type,
        "network": "base-mainnet",
        "tx_hash": "0x1111111111111111111111111111111111111111111111111111111111111111",
        "block_hash": null,
        "block_number": 123,
        "payload_id": "payload-1",
        "request_id": "request-1",
        "data": {
            "position": 1
        }
    }))
    .unwrap()
}

fn utc_today_at(hour: u32, minute: u32, second: u32) -> chrono::DateTime<Utc> {
    Utc::now().date_naive().and_hms_opt(hour, minute, second).unwrap().and_utc()
}

async fn cleanup(pool: &PgPool, event_id: &str) {
    let _ = pool
        .execute(
            sqlx::query("DELETE FROM transaction_events_v2 WHERE event_id = $1").bind(event_id),
        )
        .await;
}

async fn event_ids_like(pool: &PgPool, prefix: &str) -> anyhow::Result<Vec<String>> {
    Ok(sqlx::query_scalar(
        "SELECT event_id FROM transaction_events_v2 WHERE event_id LIKE $1 ORDER BY event_id",
    )
    .bind(format!("{prefix}-%"))
    .fetch_all(pool)
    .await?)
}

async fn hot_partitions(pool: &PgPool) -> anyhow::Result<Vec<String>> {
    Ok(sqlx::query_scalar(HOT_PARTITIONS_SQL).fetch_all(pool).await?)
}

async fn legacy_partitions(pool: &PgPool) -> anyhow::Result<Vec<String>> {
    Ok(sqlx::query_scalar(LEGACY_PARTITIONS_SQL).fetch_all(pool).await?)
}

/// Inserts one row into the legacy tree as the previous release wrote it,
/// with the shared hashes and block number. The transaction hash is stored in
/// uppercase hex, as some early legacy rows were.
async fn insert_legacy_row(
    pool: &PgPool,
    event_id: &str,
    event_type: &str,
    retention_class: &str,
    event_time: DateTime<Utc>,
    data: Value,
) -> anyhow::Result<()> {
    sqlx::query(
        "INSERT INTO transaction_events \
         (event_id, schema_version, event_time, event_date, retention_class, producer, \
          event_type, network, tx_hash, block_hash, block_number, data) \
         VALUES ($1, 'transaction-event/v1', $2, ($2 AT TIME ZONE 'UTC')::date, $3, \
                 'base-builder', $4, 'base-mainnet', $5, $6, $7, $8)",
    )
    .bind(event_id)
    .bind(event_time)
    .bind(retention_class)
    .bind(event_type)
    .bind(format!("0x{}", SHARED_TX_HASH[2..].to_ascii_uppercase()))
    .bind(SHARED_BLOCK_HASH)
    .bind(i64::try_from(SHARED_BLOCK_NUMBER)?)
    .bind(data)
    .execute(pool)
    .await?;
    Ok(())
}

/// Writes the legacy pre-partition migrations up to and including
/// `last_version` into a temporary directory, so tests can build a database
/// at an older schema.
fn legacy_migrations_through(last_version: i64) -> anyhow::Result<PathBuf> {
    let source = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("legacy_migrations");
    let target = std::env::temp_dir().join(format!("audit-migrations-{}", unique_event_id()));
    std::fs::create_dir_all(&target)?;
    for entry in std::fs::read_dir(source)? {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().into_owned();
        let version: i64 = name.split('_').next().unwrap_or_default().parse()?;
        if version <= last_version {
            std::fs::copy(entry.path(), target.join(name))?;
        }
    }
    Ok(target)
}

fn default_ingest_config() -> TransactionEventIngestConfig {
    TransactionEventIngestConfig {
        path: DEFAULT_TRANSACTION_EVENT_BATCH_PATH.to_string(),
        max_batch_size: DEFAULT_TRANSACTION_EVENT_MAX_BATCH_SIZE,
        max_event_bytes: DEFAULT_TRANSACTION_EVENT_MAX_EVENT_BYTES,
        max_data_bytes: DEFAULT_TRANSACTION_EVENT_MAX_DATA_BYTES,
        max_request_bytes: DEFAULT_TRANSACTION_EVENT_MAX_REQUEST_BYTES,
    }
}

/// Builds an NDJSON batch of `count` valid events, each padded so the request
/// approximates a full-size Vector payload.
fn ndjson_batch(event_prefix: &str, count: usize, data_padding_len: usize) -> Vec<u8> {
    let padding = "p".repeat(data_padding_len);
    (0..count)
        .map(|index| {
            serde_json::to_string(&json!({
                "schema_version": "transaction-event/v1",
                "event_id": format!("{event_prefix}-{index}"),
                "event_time": Utc::now(),
                "producer": "base-builder",
                "event_type": "BUILDER_ACCEPTED",
                "network": "base-mainnet",
                "tx_hash": "0x1111111111111111111111111111111111111111111111111111111111111111",
                "block_hash": null,
                "block_number": 123,
                "payload_id": "payload-1",
                "request_id": "request-1",
                "data": {
                    "position": 1,
                    "padding": padding,
                }
            }))
            .unwrap()
        })
        .collect::<Vec<_>>()
        .join("\n")
        .into_bytes()
}

async fn post_batch(
    sink: PgTransactionEventSink,
    body: Vec<u8>,
) -> anyhow::Result<(StatusCode, Value)> {
    let app = default_ingest_config().into_router(Arc::new(sink));
    let request = Request::builder()
        .method("POST")
        .uri(DEFAULT_TRANSACTION_EVENT_BATCH_PATH)
        .header("content-type", "application/x-ndjson")
        .body(Body::from(body))?;
    let response = app.oneshot(request).await?;
    let status = response.status();
    let body = to_bytes(response.into_body(), usize::MAX).await?;
    Ok((status, serde_json::from_slice(&body)?))
}

async fn count_events_with_prefix(pool: &PgPool, event_prefix: &str) -> anyhow::Result<i64> {
    let count: (i64,) =
        sqlx::query_as("SELECT COUNT(*) FROM transaction_events_v2 WHERE event_id LIKE $1")
            .bind(format!("{event_prefix}-%"))
            .fetch_one(pool)
            .await?;
    Ok(count.0)
}

#[tokio::test]
async fn transaction_events_unready_before_required_migration() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;

    let err = sink.check_schema_ready().await.unwrap_err();
    assert!(matches!(err, TransactionEventSchemaReadinessError::MigrationTableMissing));
    assert!(err.to_string().contains("audit-archiver migrate up"));

    Ok(())
}

#[tokio::test]
async fn transaction_events_unready_when_migration_version_is_missing() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    pool.execute(sqlx::query(
        "CREATE TABLE _sqlx_migrations (version BIGINT, success BOOLEAN, checksum BYTEA)",
    ))
    .await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let expected_version =
        PgTransactionEventSink::required_migration_version().map_err(anyhow::Error::msg)?;

    let err = sink.check_schema_ready().await.unwrap_err();
    assert!(matches!(
        err,
        TransactionEventSchemaReadinessError::RequiredMigrationMissing {
            required_version
        } if required_version == expected_version
    ));
    assert!(err.to_string().contains("003_transaction_events_v2.sql"));

    Ok(())
}

#[test]
fn transaction_events_migration_version_matches_sqlx_migration_metadata() -> anyhow::Result<()> {
    assert_eq!(
        PgTransactionEventSink::required_migration_version().map_err(anyhow::Error::msg)?,
        3,
        "003_transaction_events_v2.sql should resolve to sqlx migration version 3"
    );
    Ok(())
}

/// Legacy 003 also recorded version 3, so readiness must check the checksum.
#[tokio::test]
async fn transaction_events_unready_on_pre_partition_schema() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    Migrator::new(legacy_migrations_through(4)?).await?.run(&pool).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;

    let err = sink.check_schema_ready().await.unwrap_err();
    assert!(
        matches!(err, TransactionEventSchemaReadinessError::RequiredMigrationMissing { .. }),
        "new pods must not go ready against the unpartitioned table: {err}"
    );

    Ok(())
}

#[tokio::test]
async fn transaction_events_ready_after_required_migration() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;

    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;

    sink.check_schema_ready().await?;

    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let applied: (bool,) =
        sqlx::query_as("SELECT success FROM _sqlx_migrations WHERE version = $1")
            .bind(PgTransactionEventSink::required_migration_version().map_err(anyhow::Error::msg)?)
            .fetch_one(&pool)
            .await?;
    assert!(applied.0);

    Ok(())
}

#[tokio::test]
async fn postgres_partition_migration_discards_pre_partition_rows() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    harness.create_grantee_roles().await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    Migrator::new(legacy_migrations_through(4)?).await?.run(&pool).await?;
    sqlx::query(
        "INSERT INTO transaction_events \
         (event_id, schema_version, event_time, producer, event_type, network, data) \
         VALUES ('legacy-row', 'transaction-event/v1', now(), 'base-builder', \
                 'BUILDER_ACCEPTED', 'base-mainnet', '{}'::jsonb)",
    )
    .execute(&pool)
    .await?;

    PgTransactionEventSink::migrate(&harness.database_url).await?;

    let rows: i64 =
        sqlx::query_scalar("SELECT COUNT(*) FROM transaction_events").fetch_one(&pool).await?;
    assert_eq!(rows, 0, "the reset replaces the table instead of copying rows");
    let versions: Vec<i64> =
        sqlx::query_scalar("SELECT version FROM _sqlx_migrations ORDER BY version")
            .fetch_all(&pool)
            .await?;
    assert_eq!(versions, vec![1, 2, 3], "legacy history is replaced by the new migrations");
    PgTransactionEventSink::connect(&harness.database_url, 1).await?.check_schema_ready().await?;
    harness.assert_schema_matches_snapshot().await?;

    Ok(())
}

#[tokio::test]
async fn postgres_fresh_database_runs_partitioned_migrations() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;

    let grantees: i64 = sqlx::query_scalar(
        "SELECT count(*) FROM pg_roles WHERE rolname IN ('audit_archiver', 'datapilot')",
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(grantees, 0, "migrations apply when the granted roles do not exist");

    let versions: Vec<i64> =
        sqlx::query_scalar("SELECT version FROM _sqlx_migrations ORDER BY version")
            .fetch_all(&pool)
            .await?;
    assert_eq!(versions, vec![1, 2, 3]);

    Ok(())
}

/// Mainnet shape: 003 dropped the rejected index and recorded, then 004's
/// concurrent rebuild was killed before recording. Migrating must not run 004
/// against the old table, and the invalid index must not survive. The result
/// must match a fresh database's schema.
#[tokio::test]
async fn postgres_migrates_past_an_unrecorded_004_with_an_invalid_index() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    harness.create_grantee_roles().await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    Migrator::new(legacy_migrations_through(3)?).await?.run(&pool).await?;
    sqlx::query(
        "INSERT INTO transaction_events \
         (event_id, schema_version, event_time, producer, event_type, network, data) \
         SELECT 'legacy-' || n, 'transaction-event/v1', now(), 'base-builder', \
                'BUILDER_REJECTED', 'base-mainnet', '{}'::jsonb \
         FROM generate_series(1, 2) AS n",
    )
    .execute(&pool)
    .await?;
    // A failed concurrent build leaves an invalid index behind under the name
    // 004 would skip with IF NOT EXISTS.
    let failed = sqlx::query(
        "CREATE UNIQUE INDEX CONCURRENTLY transaction_events_rejected_event_time_idx \
         ON transaction_events (event_type)",
    )
    .execute(&pool)
    .await;
    assert!(failed.is_err(), "duplicate event types make the build fail");
    let invalid: bool = sqlx::query_scalar(
        "SELECT NOT indisvalid FROM pg_index \
         WHERE indexrelid = 'transaction_events_rejected_event_time_idx'::regclass",
    )
    .fetch_one(&pool)
    .await?;
    assert!(invalid);

    PgTransactionEventSink::migrate(&harness.database_url).await?;

    let versions: Vec<i64> =
        sqlx::query_scalar("SELECT version FROM _sqlx_migrations ORDER BY version")
            .fetch_all(&pool)
            .await?;
    assert_eq!(versions, vec![1, 2, 3], "004 is never run, and legacy history is replaced");
    let (valid, partitioned): (bool, bool) = sqlx::query_as(
        "SELECT i.indisvalid, c.relkind = 'I' FROM pg_index i \
         JOIN pg_class c ON c.oid = i.indexrelid \
         WHERE i.indexrelid = 'transaction_events_rejected_event_time_idx'::regclass",
    )
    .fetch_one(&pool)
    .await?;
    assert!(
        valid && partitioned,
        "the index is the baseline's partitioned index, not the leftover"
    );
    PgTransactionEventSink::connect(&harness.database_url, 1).await?.check_schema_ready().await?;
    harness.assert_schema_matches_snapshot().await?;

    Ok(())
}

#[tokio::test]
async fn postgres_migrate_rejects_unknown_applied_migrations() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    sqlx::query(
        "INSERT INTO _sqlx_migrations \
         (version, description, success, checksum, execution_time) \
         VALUES (99, 'from a newer binary', true, '\\x00'::bytea, 0)",
    )
    .execute(&pool)
    .await?;

    let err = PgTransactionEventSink::migrate(&harness.database_url).await.unwrap_err();
    assert!(err.to_string().contains("99"), "{err}");

    Ok(())
}

/// The reset deletes only history it recognizes: a legacy database that also
/// records an unknown migration is left untouched.
#[tokio::test]
async fn postgres_migrate_refuses_to_reset_unrecognized_history() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    Migrator::new(legacy_migrations_through(4)?).await?.run(&pool).await?;
    sqlx::query(
        "INSERT INTO _sqlx_migrations \
         (version, description, success, checksum, execution_time) \
         VALUES (99, 'from a newer binary', true, '\\x00'::bytea, 0)",
    )
    .execute(&pool)
    .await?;

    let err = PgTransactionEventSink::migrate(&harness.database_url).await.unwrap_err();
    assert!(err.to_string().contains("refusing to reset migration history"), "{err}");
    let versions: Vec<i64> =
        sqlx::query_scalar("SELECT version FROM _sqlx_migrations ORDER BY version")
            .fetch_all(&pool)
            .await?;
    assert_eq!(versions, vec![1, 2, 3, 4, 99]);
    let partitioned: bool = sqlx::query_scalar(
        "SELECT relkind = 'p' FROM pg_class WHERE oid = 'transaction_events'::regclass",
    )
    .fetch_one(&pool)
    .await?;
    assert!(!partitioned, "the legacy table is not dropped");

    Ok(())
}

#[tokio::test]
async fn postgres_schema_matches_committed_snapshot() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    harness.create_grantee_roles().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;

    harness.assert_schema_matches_snapshot().await?;

    Ok(())
}

#[tokio::test]
async fn postgres_ingested_at_index_recovers_and_covers_future_days() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;

    let parent_valid: bool = sqlx::query_scalar(
        "SELECT indisvalid FROM pg_index \
         WHERE indexrelid = 'transaction_events_ingested_at_idx'::regclass",
    )
    .fetch_one(&pool)
    .await?;
    assert!(!parent_valid, "parent-only migration does not block on existing days");

    let today = Utc::now().date_naive();
    let during_build = today + chrono::Duration::days(4);
    let created: bool = sqlx::query_scalar("SELECT transaction_events_create_partition('hot', $1)")
        .bind(during_build)
        .fetch_one(&pool)
        .await?;
    assert!(created);
    let during_build_name =
        format!("transaction_events_hot_{}_ingested_at_idx", during_build.format("%Y%m%d"));
    let inherited: bool = sqlx::query_scalar(
        "SELECT i.indisvalid FROM pg_index i WHERE i.indexrelid = to_regclass($1)",
    )
    .bind(format!("public.{during_build_name}"))
    .fetch_one(&pool)
    .await?;
    assert!(inherited, "new days inherit the index even while the parent is invalid");

    let leaf = format!("transaction_events_hot_{}", today.format("%Y%m%d"));
    sqlx::query(&format!(
        "INSERT INTO public.{leaf} \
         (event_id, schema_version, event_time, event_date, retention_class, producer, event_type, data) \
         VALUES ('index-a', 'transaction-event/v1', now(), $1, 'hot', 'base-builder', 'BUILDER_ACCEPTED', '{{}}'), \
                ('index-b', 'transaction-event/v1', now(), $1, 'hot', 'base-builder', 'BUILDER_ACCEPTED', '{{}}')"
    ))
    .bind(today)
    .execute(&pool)
    .await?;

    // A failed concurrent build leaves an INVALID index with the intended
    // name. The index command must not silently skip it with IF NOT EXISTS.
    let index_name = format!("{leaf}_ingested_at_idx");
    let failed = sqlx::query(&format!(
        "CREATE UNIQUE INDEX CONCURRENTLY {index_name} ON public.{leaf} (event_type)"
    ))
    .execute(&pool)
    .await;
    let err = failed.expect_err("duplicate event types must fail the unique build");
    assert_eq!(err.as_database_error().and_then(|error| error.code()).as_deref(), Some("23505"));
    let invalid: bool = sqlx::query_scalar(
        "SELECT NOT indisvalid FROM pg_index WHERE indexrelid = to_regclass($1)",
    )
    .bind(format!("public.{index_name}"))
    .fetch_one(&pool)
    .await?;
    assert!(invalid, "failed concurrent build left an invalid index");

    let built = index_transaction_event_partitions(&harness.database_url).await?;
    assert!(built > 0, "existing day partitions were indexed");
    assert_eq!(index_transaction_event_partitions(&harness.database_url).await?, 0);

    let index_valid: bool = sqlx::query_scalar(
        "SELECT i.indisvalid AND a.amname = 'brin' \
         FROM pg_index i \
         JOIN pg_class c ON c.oid = i.indexrelid \
         JOIN pg_am a ON a.oid = c.relam \
         WHERE c.oid = 'transaction_events_ingested_at_idx'::regclass",
    )
    .fetch_one(&pool)
    .await?;
    assert!(index_valid, "all class and leaf indexes are attached and valid");

    // Daily partition maintenance creates a table and ATTACHes it. The valid
    // parent partitioned index must automatically install the new leaf index.
    let future = today + chrono::Duration::days(5);
    let created: bool = sqlx::query_scalar("SELECT transaction_events_create_partition('hot', $1)")
        .bind(future)
        .fetch_one(&pool)
        .await?;
    assert!(created);
    let future_name = format!("transaction_events_hot_{}_ingested_at_idx", future.format("%Y%m%d"));
    let future_valid: bool = sqlx::query_scalar(
        "SELECT i.indisvalid AND a.amname = 'brin' \
         FROM pg_index i \
         JOIN pg_class c ON c.oid = i.indexrelid \
         JOIN pg_am a ON a.oid = c.relam \
         WHERE c.oid = to_regclass($1)",
    )
    .bind(format!("public.{future_name}"))
    .fetch_one(&pool)
    .await?;
    assert!(future_valid, "new day automatically inherits the usable ingested_at index");

    Ok(())
}

#[tokio::test]
async fn postgres_schema_is_partitioned_by_class_then_day() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;

    let class_partitions = |parent: &'static str| {
        sqlx::query_scalar::<_, String>(
            "SELECT c.relname::text FROM pg_inherits i \
             JOIN pg_class c ON c.oid = i.inhrelid \
             WHERE i.inhparent = $1::regclass \
             ORDER BY c.relname",
        )
        .bind(parent)
        .fetch_all(&pool)
    };
    assert_eq!(
        class_partitions("transaction_events").await?,
        vec!["transaction_events_cold", "transaction_events_hot", "transaction_events_warm"]
    );
    assert_eq!(
        class_partitions("transaction_events_v2").await?,
        vec![
            "transaction_events_v2_cold",
            "transaction_events_v2_hot",
            "transaction_events_v2_warm"
        ]
    );

    // The v2 migration seeds each default retention window (hot is 3 days)
    // through three days ahead.
    let today = Utc::now().date_naive();
    let expected: Vec<String> = (-3..=3)
        .map(|offset| {
            format!(
                "transaction_events_v2_hot_{}",
                (today + chrono::Duration::days(offset)).format("%Y%m%d")
            )
        })
        .collect();
    assert_eq!(hot_partitions(&pool).await?, expected);

    let dropped_indexes: i64 = sqlx::query_scalar(
        "SELECT COUNT(*) FROM pg_indexes \
         WHERE schemaname = 'public' \
           AND indexname IN ( \
             'transaction_events_payload_id_event_time_idx', \
             'transaction_events_producer_event_type_event_time_idx', \
             'transaction_events_event_type_ingested_at_idx' \
           )",
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(dropped_indexes, 0, "unused indexes are not recreated");

    Ok(())
}

#[tokio::test]
async fn postgres_rejected_index_includes_builder_expired() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;

    let indexdefs: Vec<String> = sqlx::query_scalar(
        "SELECT indexdef FROM pg_indexes \
         WHERE schemaname = 'public' \
           AND indexname IN \
               ('transaction_events_rejected_event_time_idx', \
                'transaction_events_v2_rejected_event_time_idx')",
    )
    .fetch_all(&pool)
    .await?;
    assert_eq!(indexdefs.len(), 2, "both trees have the rejected index");
    for indexdef in indexdefs {
        assert!(
            indexdef.contains("BUILDER_EXPIRED"),
            "rejected index should include BUILDER_EXPIRED: {indexdef}"
        );
    }

    Ok(())
}

#[tokio::test]
async fn postgres_sink_chunks_large_direct_inserts() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;

    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let event_count = MAX_TRANSACTION_EVENT_INSERT_BATCH_SIZE + 1;
    let event_prefix = unique_event_id();
    let events =
        (0..event_count).map(|index| event(&format!("{event_prefix}-{index}"))).collect::<Vec<_>>();

    let outcome = sink.insert_events(&events).await?;

    assert_eq!(outcome.inserted_event_ids.len(), event_count);
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let count: (i64,) =
        sqlx::query_as("SELECT COUNT(*) FROM transaction_events_v2 WHERE event_id LIKE $1")
            .bind(format!("{event_prefix}-%"))
            .fetch_one(&pool)
            .await?;
    assert_eq!(count.0, i64::try_from(event_count)?);

    Ok(())
}

#[tokio::test]
async fn postgres_http_ingest_accepts_1000_event_batch() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 2).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let event_prefix = unique_event_id();

    // ~1 KiB per event so the batch exercises a realistic ~1 MiB Vector payload.
    let body = ndjson_batch(&event_prefix, DEFAULT_TRANSACTION_EVENT_MAX_BATCH_SIZE, 550);
    assert!(body.len() > 512 * 1024, "expected a large batch, got {} bytes", body.len());

    let (status, json) = post_batch(sink, body).await?;

    assert_eq!(status, StatusCode::OK);
    assert_eq!(json["status"], "accepted");
    assert_eq!(json["accepted"], 1000);
    assert_eq!(json["duplicate"], 0);
    assert_eq!(json["rejected"], 0);
    assert_eq!(count_events_with_prefix(&pool, &event_prefix).await?, 1000);

    Ok(())
}

#[tokio::test]
async fn builder_rejection_journal_survives_http_ingest_and_rpc_query() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 2).await?;
    sink.check_schema_ready().await?;

    let event_id = unique_event_id();
    let mut rejected = event_with_type(&event_id, "BUILDER_REJECTED");
    rejected.data = json!({
        "rejection_reason": "tx_execution_time_exceeded",
        "tx_execution_time_us": 2000,
        "tx_execution_time_limit_us": 1000,
    })
    .as_object()
    .unwrap()
    .clone();
    let body = serde_json::to_vec(&rejected)?;

    let (status, first) = post_batch(sink.clone(), body.clone()).await?;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(first["accepted"], 1);
    assert_eq!(first["rejected"], 0);
    let (status, retry) = post_batch(sink.clone(), body).await?;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(retry["duplicate"], 1);

    let rpc = AuditArchiverRpc::new(sink);
    let by_hash = rpc
        .get_transaction_events_by_hash(
            "0x1111111111111111111111111111111111111111111111111111111111111111".into(),
            None,
        )
        .await
        .expect("Postgres-backed RPC lookup must work without S3");
    assert_eq!(by_hash.len(), 1);
    assert_eq!(by_hash[0].event.event_id, event_id);
    assert_eq!(by_hash[0].event.data["rejection_reason"], "tx_execution_time_exceeded");

    let rejections = rpc
        .get_rejected_transaction_events(RejectedTransactionEventQuery {
            limit: Some(10),
            ..Default::default()
        })
        .await
        .expect("rejected event RPC must read Postgres without S3");
    assert_eq!(rejections.len(), 1);
    assert_eq!(rejections[0].event.event_id, event_id);
    Ok(())
}

#[tokio::test]
async fn postgres_http_ingest_rejects_1001_event_batch_without_writes() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 2).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let event_prefix = unique_event_id();

    let body = ndjson_batch(&event_prefix, DEFAULT_TRANSACTION_EVENT_MAX_BATCH_SIZE + 1, 0);

    let (status, json) = post_batch(sink, body).await?;

    assert_eq!(status, StatusCode::BAD_REQUEST);
    assert_eq!(json["status"], "rejected");
    assert_eq!(json["results"][0]["reason"], "batch size exceeds maximum 1000");
    assert_eq!(count_events_with_prefix(&pool, &event_prefix).await?, 0);

    Ok(())
}

#[tokio::test]
async fn postgres_sink_dedupes_retried_events_and_routes_by_class() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let event_prefix = unique_event_id();
    let events = [
        event(&format!("{event_prefix}-hot")),
        event_with_type(&format!("{event_prefix}-warm"), "INGRESS_RECEIVED"),
        event_with_type(&format!("{event_prefix}-cold"), "SIMULATION_FAILED"),
    ];

    let first = sink.insert_events(&events).await?;
    assert_eq!(first.inserted_event_ids.len(), 3);
    let retry = sink.insert_events(&events).await?;
    assert!(retry.inserted_event_ids.is_empty(), "retried events must conflict");

    let mut first_in_hour = event(&format!("{}-reemitted", unique_event_id()));
    first_in_hour.event_time = utc_today_at(0, 0, 10);
    let mut later_same_hour = first_in_hour.clone();
    later_same_hour.event_time = utc_today_at(0, 59, 50);
    let mut next_hour = first_in_hour.clone();
    next_hour.event_time = utc_today_at(1, 0, 10);
    assert_eq!(sink.insert_events(&[first_in_hour]).await?.inserted_event_ids.len(), 1);
    assert!(
        sink.insert_events(&[later_same_hour]).await?.inserted_event_ids.is_empty(),
        "an event_id already stored this UTC hour dedupes regardless of event_time"
    );
    assert_eq!(
        sink.insert_events(&[next_hour]).await?.inserted_event_ids.len(),
        1,
        "dedupe is per UTC hour, so a re-emission in another hour stores a row"
    );

    let classes: Vec<(String, String)> = sqlx::query_as(
        "SELECT event_id, tableoid::regclass::text FROM transaction_events_v2 \
         WHERE event_id LIKE $1 ORDER BY event_id",
    )
    .bind(format!("{event_prefix}-%"))
    .fetch_all(&pool)
    .await?;
    let today = Utc::now().date_naive().format("%Y%m%d");
    assert_eq!(
        classes,
        vec![
            (format!("{event_prefix}-cold"), format!("transaction_events_v2_cold_{today}")),
            (format!("{event_prefix}-hot"), format!("transaction_events_v2_hot_{today}")),
            (format!("{event_prefix}-warm"), format!("transaction_events_v2_warm_{today}")),
        ]
    );

    Ok(())
}

#[tokio::test]
async fn postgres_seeded_partitions_accept_every_default_admitted_day() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let event_prefix = unique_event_id();

    // No maintenance pass has run: a pod that goes ready right after the
    // migration must still store delayed events inside the default windows.
    let mut old_hot = event(&format!("{event_prefix}-hot"));
    old_hot.event_time = Utc::now() - chrono::Duration::days(3) + chrono::Duration::minutes(1);
    let mut old_cold = event_with_type(&format!("{event_prefix}-cold"), "SIMULATION_FAILED");
    old_cold.event_time = Utc::now() - chrono::Duration::days(30) + chrono::Duration::minutes(1);
    let mut ahead = event(&format!("{event_prefix}-ahead"));
    ahead.event_time = Utc::now() + chrono::Duration::minutes(59);

    let outcome = sink.insert_events(&[old_hot, old_cold, ahead]).await?;
    assert_eq!(outcome.inserted_event_ids.len(), 3);

    Ok(())
}

#[tokio::test]
async fn postgres_maintenance_backfills_window_and_drops_expired_days() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let now = Utc::now();

    let first = sink.maintain_partitions_at(now).await?;
    assert!(first.lock_acquired);
    assert_eq!(first.partitions_dropped, 0);
    // The migration already seeded the default windows through three days
    // ahead. Only the future-skew hour can reach one more day.
    assert!(first.partitions_created <= 3);
    let second = sink.maintain_partitions_at(now).await?;
    assert_eq!(second.partitions_created, 0, "maintenance is idempotent");
    let next_day = sink.maintain_partitions_at(now + chrono::Duration::days(1)).await?;
    assert!(next_day.partitions_created > 0, "each pass extends the look-ahead");

    let event_prefix = unique_event_id();
    sink.insert_events(&[
        event(&format!("{event_prefix}-hot")),
        event_with_type(&format!("{event_prefix}-warm"), "INGRESS_RECEIVED"),
    ])
    .await?;

    // Five days later, today's hot partition is past its 3-day window plus
    // grace; the warm partition is still inside its 7-day window.
    let later = sink.maintain_partitions_at(now + chrono::Duration::days(5)).await?;
    assert!(later.partitions_dropped > 0);
    assert_eq!(event_ids_like(&pool, &event_prefix).await?, vec![format!("{event_prefix}-warm")]);
    let today_hot = format!("transaction_events_v2_hot_{}", now.date_naive().format("%Y%m%d"));
    assert!(!hot_partitions(&pool).await?.contains(&today_hot));
    let leftover: Option<String> = sqlx::query_scalar("SELECT to_regclass($1)::text")
        .bind(&today_hot)
        .fetch_one(&pool)
        .await?;
    assert_eq!(leftover, None, "dropped partitions are not left detached");

    Ok(())
}

/// The legacy tree gets no new days, and its seeded days drop on the same
/// schedule as v2 days, so it empties without a manual cleanup.
#[tokio::test]
async fn postgres_maintenance_drains_legacy_tree_without_creating_days() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let now = Utc::now();
    insert_legacy_row(&pool, &unique_event_id(), "BUILDER_ACCEPTED", "hot", now, json!({})).await?;
    let seeded = legacy_partitions(&pool).await?;
    assert!(!seeded.is_empty(), "001 seeds legacy day partitions");

    sink.maintain_partitions_at(now + chrono::Duration::days(1)).await?;
    let after_one_day = legacy_partitions(&pool).await?;
    assert!(
        after_one_day.iter().all(|name| seeded.contains(name)),
        "maintenance does not create legacy days"
    );

    // Past the 30-day cold window, every seeded legacy day has aged out.
    sink.maintain_partitions_at(now + chrono::Duration::days(40)).await?;
    assert!(legacy_partitions(&pool).await?.is_empty());
    let legacy_rows: i64 =
        sqlx::query_scalar("SELECT COUNT(*) FROM transaction_events").fetch_one(&pool).await?;
    assert_eq!(legacy_rows, 0);
    sink.check_schema_ready().await?;
    assert!(sink.events_by_block_number(SHARED_BLOCK_NUMBER, 10).await?.is_empty());

    Ok(())
}

#[tokio::test]
async fn postgres_maintenance_drops_leftover_detached_partitions() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let ahead = Utc::now().date_naive() + chrono::Duration::days(3);
    let detached: bool =
        sqlx::query_scalar("SELECT transaction_events_v2_detach_partition('hot', $1)")
            .bind(ahead)
            .fetch_one(&pool)
            .await?;
    assert!(detached);

    let outcome = sink.maintain_partitions().await?;

    assert!(outcome.partitions_dropped >= 1, "leftover detached table is dropped");
    let name = format!("transaction_events_v2_hot_{}", ahead.format("%Y%m%d"));
    assert!(
        hot_partitions(&pool).await?.contains(&name),
        "the in-window day is recreated as an attached partition"
    );

    Ok(())
}

#[tokio::test]
async fn postgres_maintenance_skips_ddl_that_hits_lock_timeout() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1)
        .await?
        .with_retention_config(TransactionEventRetentionConfig {
            partition_lock_timeout_ms: 200,
            ..Default::default()
        })?;
    let pool = PgPoolOptions::new().max_connections(2).connect(&harness.database_url).await?;
    let later = Utc::now() + chrono::Duration::days(10);

    // A long-running reader of the hot class blocks DETACH's ACCESS
    // EXCLUSIVE lock but not ATTACH's SHARE UPDATE EXCLUSIVE lock.
    let mut reader = pool.begin().await?;
    sqlx::query("LOCK TABLE transaction_events_v2_hot IN ACCESS SHARE MODE")
        .execute(&mut *reader)
        .await?;
    let before = hot_partitions(&pool).await?;

    let started = Instant::now();
    let blocked = sink.maintain_partitions_at(later).await?;
    assert!(blocked.lock_timeouts > 0, "blocked detaches are skipped, not fatal");
    assert!(started.elapsed() < Duration::from_secs(10));
    let during = hot_partitions(&pool).await?;
    assert!(before.iter().all(|name| during.contains(name)), "no hot partition was detached");

    reader.rollback().await?;
    let retried = sink.maintain_partitions_at(later).await?;
    assert_eq!(retried.lock_timeouts, 0);
    let after = hot_partitions(&pool).await?;
    assert!(before.iter().all(|name| !after.contains(name)), "the next pass drops them");

    Ok(())
}

#[tokio::test]
async fn postgres_maintenance_does_not_leak_lock_timeout() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let ingest_pool =
        PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let retention_pool =
        PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let sink = PgTransactionEventSink::new_with_retention_pool(ingest_pool, retention_pool.clone());
    sink.maintain_partitions().await?;

    let lock_timeout: String =
        sqlx::query_scalar("SHOW lock_timeout").fetch_one(&retention_pool).await?;
    assert_eq!(
        lock_timeout, "0",
        "SET LOCAL lock_timeout leaked onto the pooled connection: {lock_timeout}"
    );

    Ok(())
}

#[tokio::test]
async fn postgres_maintenance_skips_when_another_replica_holds_lock() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let mut transaction = pool.begin().await?;
    let locked: bool = sqlx::query_scalar("SELECT pg_try_advisory_xact_lock(744697762131337711)")
        .fetch_one(&mut *transaction)
        .await?;
    assert!(locked);

    let outcome = sink.maintain_partitions().await?;
    assert!(!outcome.lock_acquired);
    assert_eq!(outcome.partitions_created, 0);
    assert_eq!(outcome.partitions_dropped, 0);

    transaction.rollback().await?;
    Ok(())
}

#[tokio::test]
async fn postgres_maintenance_uses_retention_pool_when_ingest_is_busy() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let ingest_pool = PgPoolOptions::new()
        .max_connections(1)
        .acquire_timeout(Duration::from_millis(500))
        .connect(&harness.database_url)
        .await?;
    let retention_pool = PgPoolOptions::new()
        .max_connections(1)
        .acquire_timeout(Duration::from_secs(1))
        .connect(&harness.database_url)
        .await?;
    let sink = PgTransactionEventSink::new_with_retention_pool(ingest_pool.clone(), retention_pool);

    let _held = ingest_pool.acquire().await?;
    let outcome =
        tokio::time::timeout(Duration::from_secs(10), sink.maintain_partitions())
            .await
            .expect("maintenance should use the retention pool instead of waiting on ingest")?;
    assert!(outcome.lock_acquired);

    Ok(())
}

/// Mirrors production roles: the migration role owns the schema and tables,
/// and the runtime role only has DML plus EXECUTE on the partition functions.
#[tokio::test]
async fn postgres_runtime_role_maintains_partitions_through_definer_functions() -> anyhow::Result<()>
{
    let harness = PostgresHarness::new().await?;
    let admin = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    for statement in [
        "CREATE ROLE audit_archiver_migration LOGIN PASSWORD 'migration'",
        "CREATE ROLE audit_archiver LOGIN PASSWORD 'runtime'",
        "CREATE ROLE unrelated LOGIN PASSWORD 'unrelated'",
        "ALTER SCHEMA public OWNER TO audit_archiver_migration",
    ] {
        admin.execute(statement).await?;
    }

    PgTransactionEventSink::migrate(&harness.url_for("audit_archiver_migration", "migration"))
        .await?;

    let runtime_url = harness.url_for("audit_archiver", "runtime");
    let sink = PgTransactionEventSink::connect(&runtime_url, 1).await?;
    sink.check_schema_ready().await?;
    assert!(sink.maintain_partitions().await?.lock_acquired);
    let tomorrow = sink.maintain_partitions_at(Utc::now() + chrono::Duration::days(1)).await?;
    assert!(tomorrow.partitions_created > 0, "runtime role can create partitions");

    let event_id = unique_event_id();
    sink.insert_events(&[event(&event_id)]).await?;
    assert_eq!(sink.events_by_block_number(123, 10).await?.len(), 1);

    // The runtime role has no grant on the event_seq identity sequence, which
    // the migration role owns, and inserts through the parent still number
    // their rows. One connection draws from one cached range, so a later
    // insert gets a larger value.
    let later_event_id = unique_event_id();
    sink.insert_events(&[event(&later_event_id)]).await?;
    let runtime = PgPoolOptions::new().max_connections(1).connect(&runtime_url).await?;
    let event_seqs: Vec<i64> = sqlx::query_scalar(
        "SELECT event_seq FROM transaction_events_v2 WHERE event_id = ANY($1) ORDER BY ingested_at",
    )
    .bind([event_id.as_str(), later_event_id.as_str()])
    .fetch_all(&runtime)
    .await?;
    assert_eq!(event_seqs.len(), 2);
    assert!(event_seqs[0] < event_seqs[1], "event_seq follows insertion order: {event_seqs:?}");

    let later = sink.maintain_partitions_at(Utc::now() + chrono::Duration::days(5)).await?;
    assert!(later.partitions_dropped > 0, "runtime role can drop expired partitions");

    let partition = format!(
        "transaction_events_v2_hot_{}",
        (Utc::now().date_naive() + chrono::Duration::days(3)).format("%Y%m%d")
    );
    let direct_drop = runtime.execute(format!("DROP TABLE {partition}").as_str()).await;
    assert!(direct_drop.is_err(), "runtime role must not own partitions");

    let unrelated = PgPoolOptions::new()
        .max_connections(1)
        .connect(&harness.url_for("unrelated", "unrelated"))
        .await?;
    for function in
        ["transaction_events_detach_partition", "transaction_events_v2_detach_partition"]
    {
        let call = sqlx::query(&format!("SELECT {function}('hot', current_date)"))
            .execute(&unrelated)
            .await;
        assert!(call.is_err(), "{function} is not executable by PUBLIC");
    }

    Ok(())
}

/// The `datapilot` warehouse extraction role is read-only: it reads the v2
/// parent, including rows stored in its leaf partitions, with no direct leaf
/// or write privileges.
#[tokio::test]
async fn postgres_datapilot_role_reads_v2_parent() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    let admin = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    admin.execute("CREATE ROLE datapilot LOGIN PASSWORD 'datapilot'").await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let event_id = unique_event_id();
    sink.insert_events(&[event(&event_id)]).await?;

    let datapilot = PgPoolOptions::new()
        .max_connections(1)
        .connect(&harness.url_for("datapilot", "datapilot"))
        .await?;
    let leaf = format!("transaction_events_v2_hot_{}", Utc::now().date_naive().format("%Y%m%d"));
    let stored_in: String = sqlx::query_scalar(
        "SELECT tableoid::regclass::text FROM transaction_events_v2 WHERE event_id = $1",
    )
    .bind(&event_id)
    .fetch_one(&admin)
    .await?;
    assert_eq!(stored_in, leaf);

    let count: i64 =
        sqlx::query_scalar("SELECT count(*) FROM transaction_events_v2 WHERE event_id = $1")
            .bind(&event_id)
            .fetch_one(&datapilot)
            .await?;
    assert_eq!(count, 1, "datapilot reads leaf rows through the v2 parent");

    // DataPilot splits each incremental window into event_seq ranges.
    let event_seq: Option<i64> =
        sqlx::query_scalar("SELECT event_seq FROM transaction_events_v2 WHERE event_id = $1")
            .bind(&event_id)
            .fetch_one(&datapilot)
            .await?;
    assert!(event_seq.is_some(), "rows in function-created leaves get an event_seq");

    let leaf_read = datapilot.execute(format!("SELECT 1 FROM {leaf} LIMIT 1").as_str()).await;
    assert!(leaf_read.is_err(), "datapilot has no grant on leaf partitions");
    let delete = sqlx::query("DELETE FROM transaction_events_v2 WHERE event_id = $1")
        .bind(&event_id)
        .execute(&datapilot)
        .await;
    assert!(delete.is_err(), "datapilot is read-only");

    Ok(())
}

#[tokio::test]
async fn postgres_insert_fails_fast_when_conflicting_row_is_locked() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(2).connect(&harness.database_url).await?;
    let sink = PgTransactionEventSink::new(pool.clone());
    let event_id = unique_event_id();
    let pending = event(&event_id);

    let mut held = pool.begin().await?;
    sqlx::query(
        "INSERT INTO transaction_events_v2 \
         (event_id, schema_version, event_time, event_hour, retention_class, producer, \
          event_type, network, data) \
         VALUES ($1, 'transaction-event/v1', $2, date_trunc('hour', $2, 'UTC'), 'hot', \
                 'base-builder', 'BUILDER_ACCEPTED', 'base-mainnet', '{}'::jsonb)",
    )
    .bind(&event_id)
    .bind(pending.event_time)
    .execute(&mut *held)
    .await?;

    let started = Instant::now();
    let result = tokio::time::timeout(
        Duration::from_secs(15),
        sink.insert_events(std::slice::from_ref(&pending)),
    )
    .await
    .expect("insert should fail lock waits instead of blocking until the test times out");
    assert!(result.is_err(), "conflicting insert should fail after lock_timeout retries");
    assert!(
        started.elapsed() >= Duration::from_secs(2),
        "three lock_timeout attempts should take more than one 1s wait"
    );

    held.rollback().await?;
    sink.insert_events(&[pending]).await?;
    cleanup(&pool, &event_id).await;
    Ok(())
}

#[tokio::test]
async fn postgres_insert_does_not_leak_lock_timeout() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let sink = PgTransactionEventSink::new(pool.clone());
    let event_id = unique_event_id();
    sink.insert_events(&[event(&event_id)]).await?;

    let lock_timeout: String = sqlx::query_scalar("SHOW lock_timeout").fetch_one(&pool).await?;
    assert_ne!(
        lock_timeout, "1s",
        "SET LOCAL lock_timeout leaked onto the pooled connection: {lock_timeout}"
    );

    Ok(())
}

#[tokio::test]
#[ignore = "requires a running Postgres (set DATABASE_URL)"]
async fn postgres_sink_persists_and_dedupes_by_event_id() {
    let database_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let event_id = unique_event_id();
    PgTransactionEventSink::migrate(&database_url).await.unwrap();
    let pool = PgPoolOptions::new().max_connections(2).connect(&database_url).await.unwrap();
    cleanup(&pool, &event_id).await;

    let sink = PgTransactionEventSink::connect(&database_url, 2).await.unwrap();
    let event = event(&event_id);

    let first = sink.insert_events(std::slice::from_ref(&event)).await.unwrap();
    assert!(first.inserted_event_ids.contains(&event_id));

    let second = sink.insert_events(std::slice::from_ref(&event)).await.unwrap();
    assert!(second.inserted_event_ids.is_empty());

    let count: (i64,) =
        sqlx::query_as("SELECT COUNT(*) FROM transaction_events_v2 WHERE event_id = $1")
            .bind(&event_id)
            .fetch_one(&pool)
            .await
            .unwrap();
    assert_eq!(count.0, 1);

    cleanup(&pool, &event_id).await;
}

#[tokio::test]
async fn postgres_query_finds_events_by_normalized_tx_hash() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let event_id = unique_event_id();
    sink.insert_events(&[event(&event_id)]).await?;

    let lowercase = sink
        .events_by_transaction_hash(
            "0x1111111111111111111111111111111111111111111111111111111111111111",
            10,
        )
        .await?;
    assert_eq!(lowercase.len(), 1);
    assert_eq!(lowercase[0].event.event_id, event_id);

    let mixed_case_hash =
        "0x1111111111111111111111111111111111111111111111111111111111111111".to_ascii_uppercase();
    let mixed_case = sink.events_by_transaction_hash(&mixed_case_hash, 10).await?;
    assert_eq!(mixed_case.len(), 1);
    assert_eq!(mixed_case[0].event.event_id, event_id);

    let block_events = sink.events_by_block_number(123, 10).await?;
    assert_eq!(block_events.len(), 1);
    assert_eq!(block_events[0].event.event_id, event_id);

    Ok(())
}

/// Rows written to the legacy tree by the previous release stay readable
/// through every query API until they age out.
#[tokio::test]
async fn postgres_queries_read_through_legacy_rows() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;
    let prefix = unique_event_id();
    let now = Utc::now();
    let legacy_accepted = format!("{prefix}-a-legacy-accepted");
    let legacy_failed = format!("{prefix}-b-legacy-failed");
    let v2_rejected = format!("{prefix}-c-v2-rejected");

    insert_legacy_row(
        &pool,
        &legacy_accepted,
        "BUILDER_ACCEPTED",
        "hot",
        now - chrono::Duration::seconds(20),
        json!({ "bundle_hash": SHARED_BUNDLE_HASH }),
    )
    .await?;
    insert_legacy_row(
        &pool,
        &legacy_failed,
        "SIMULATION_FAILED",
        "cold",
        now - chrono::Duration::seconds(10),
        json!({}),
    )
    .await?;
    let mut current = event_with_type(&v2_rejected, "BUILDER_REJECTED");
    current.event_time = now;
    current.tx_hash = Some(SHARED_TX_HASH.parse()?);
    current.block_hash = Some(SHARED_BLOCK_HASH.parse()?);
    current.block_number = Some(SHARED_BLOCK_NUMBER);
    current.data.insert("bundle_hash".to_string(), json!(SHARED_BUNDLE_HASH));
    sink.insert_events(&[current]).await?;

    let ids = |records: Vec<TransactionEventRecord>| {
        records.into_iter().map(|record| record.event.event_id).collect::<Vec<_>>()
    };
    let oldest_first = vec![legacy_accepted.clone(), legacy_failed.clone(), v2_rejected.clone()];

    let by_tx_hash = sink.events_by_transaction_hash(SHARED_TX_HASH, 10).await?;
    let expected_hash = Some(SHARED_TX_HASH.parse()?);
    assert!(by_tx_hash.iter().all(|record| record.event.tx_hash == expected_hash));
    assert_eq!(ids(by_tx_hash), oldest_first);
    assert_eq!(
        ids(sink.events_by_transaction_hash(&SHARED_TX_HASH.to_ascii_uppercase(), 10).await?),
        oldest_first
    );
    assert_eq!(
        ids(sink.events_by_transaction_hash(SHARED_TX_HASH, 2).await?),
        vec![legacy_accepted.clone(), legacy_failed.clone()],
        "the limit applies to the union of both trees"
    );
    assert_eq!(
        ids(sink.events_by_block_hash(&SHARED_BLOCK_HASH.to_ascii_uppercase(), 10).await?),
        oldest_first
    );
    assert_eq!(ids(sink.events_by_block_number(SHARED_BLOCK_NUMBER, 10).await?), oldest_first);
    assert_eq!(
        ids(sink.events_by_bundle(SHARED_BUNDLE_HASH, 10).await?),
        vec![legacy_accepted.clone(), v2_rejected.clone()]
    );
    assert_eq!(
        ids(sink
            .rejected_transaction_events(RejectedTransactionEventQuery {
                from_block: Some(SHARED_BLOCK_NUMBER),
                ..Default::default()
            })
            .await?),
        vec![v2_rejected, legacy_failed]
    );

    Ok(())
}

#[tokio::test]
async fn postgres_v2_keys_lead_with_event_hour_and_store_canonical_hashes() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let pool = PgPoolOptions::new().max_connections(1).connect(&harness.database_url).await?;

    let key: Vec<String> = sqlx::query_scalar(
        "SELECT a.attname::text FROM pg_index i \
         CROSS JOIN LATERAL unnest(i.indkey::int2[]) WITH ORDINALITY AS k(attnum, ord) \
         JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = k.attnum \
         WHERE i.indrelid = 'transaction_events_v2'::regclass AND i.indisprimary \
         ORDER BY k.ord",
    )
    .fetch_all(&pool)
    .await?;
    assert_eq!(key, vec!["event_hour", "retention_class", "event_id"]);

    // Lookups bind one hash form, so a writer that bypasses audit-archiver
    // must not store another.
    let uppercase_hash = sqlx::query(&format!(
        "INSERT INTO transaction_events_v2 \
         (event_id, schema_version, event_time, event_hour, retention_class, producer, \
          event_type, tx_hash, data) \
         VALUES ('uppercase', 'transaction-event/v1', now(), date_trunc('hour', now(), 'UTC'), \
                 'hot', 'base-builder', 'BUILDER_ACCEPTED', '0x{}', '{{}}'::jsonb)",
        "AB".repeat(32)
    ))
    .execute(&pool)
    .await
    .unwrap_err();
    assert_eq!(
        uppercase_hash.as_database_error().and_then(|err| err.code()).as_deref(),
        Some("23514")
    );

    // The CHECK keeps event_hour consistent with event_time for writers that
    // bypass audit-archiver.
    let mismatched = sqlx::query(
        "INSERT INTO transaction_events_v2 \
         (event_id, schema_version, event_time, event_hour, retention_class, producer, \
          event_type, data) \
         VALUES ('mismatched', 'transaction-event/v1', now(), \
                 date_trunc('hour', now(), 'UTC') + interval '1 hour', 'hot', 'base-builder', \
                 'BUILDER_ACCEPTED', '{}'::jsonb)",
    )
    .execute(&pool)
    .await
    .unwrap_err();
    assert_eq!(mismatched.as_database_error().and_then(|err| err.code()).as_deref(), Some("23514"));

    Ok(())
}

#[tokio::test]
async fn postgres_rejected_query_returns_bounded_newest_first() -> anyhow::Result<()> {
    let harness = PostgresHarness::new().await?;
    PgTransactionEventSink::migrate(&harness.database_url).await?;
    let sink = PgTransactionEventSink::connect(&harness.database_url, 1).await?;
    let event_prefix = unique_event_id();

    let mut older = event_with_type(&format!("{event_prefix}-old"), "SIMULATION_FAILED");
    older.event_time = Utc::now() - chrono::Duration::seconds(30);
    let mut newer = event_with_type(&format!("{event_prefix}-new"), "BUILDER_REJECTED");
    newer.event_time = Utc::now();
    let accepted = event_with_type(&format!("{event_prefix}-ok"), "BUILDER_ACCEPTED");
    sink.insert_events(&[older, newer, accepted]).await?;

    let records = sink
        .rejected_transaction_events(RejectedTransactionEventQuery {
            limit: Some(1),
            ..Default::default()
        })
        .await?;
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].event.event_id, format!("{event_prefix}-new"));
    assert_eq!(records[0].event.event_type.to_string(), "BUILDER_REJECTED");

    Ok(())
}
