[package]
name = "base-evm-handler"
description = "Base EVM execution handlers and inspection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
]

[dependencies]
either = { workspace = true }
auto_impl = { workspace = true }
revm-state = { workspace = true }
derive-where = { workspace = true }
revm-bytecode = { workspace = true }
base-state = { workspace = true }
revm-precompile = { workspace = true }
revm-primitives = { workspace = true }
base-evm-context = { workspace = true }
revm-interpreter = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"], optional = true }
serde_json = { workspace = true, features = [
    "alloc",
    "preserve_order",
], optional = true }
tracing = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
base-common-rpc-types = { workspace = true, optional = true }
base-common-consensus = {workspace = true, features = ["k256"]}
[dev-dependencies]
alloy-signer = { workspace = true }
base-common-network = { workspace = true }
base-state = { workspace = true, features = ["serde"]}
serde_json = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["serde"] }
[lints]
workspace = true

[features]
default = ["std"]
serde = [
    "dep:serde",
    "revm-primitives/serde",
    "revm-state/serde",
    "base-evm-context/serde",
    "revm-bytecode/serde",
    "base-state/serde",
    "base-state/serde",
    "revm-interpreter/serde",
    "derive-where/serde",
    "either/serde",
]
serde-json = ["serde", "tracer"]
std = [
    "serde?/std",
    "revm-bytecode/std",
    "base-evm-context/std",
    "base-state/std",
    "base-state/std",
    "revm-interpreter/std",
    "revm-precompile/std",
    "revm-primitives/std",
    "revm-state/std",
    "serde_json?/std",
    "serde_json?/preserve_order",
    "either/std",
    "alloy-primitives/std",
    "base-common-consensus/std",
    "alloy-eips/std",
    "derive_more/std",
    "thiserror/std",
    "base-common-rpc-types?/std",
    "tracing/std",
]
tracer = ["std", "serde", "dep:serde", "dep:serde_json"]
asm-keccak = ["alloy-primitives/asm-keccak", "revm-primitives/asm-keccak"]
call-util = ["overrides"]
gmp = ["revm-precompile/gmp"]
overrides = ["dep:base-common-rpc-types"]
rpc = ["dep:base-common-rpc-types"]
secp256k1 = ["std", "base-common-consensus/secp256k1"]
