[package]
name = "base-evm-handler"
description = "Base EVM execution handlers and inspection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
]

[dependencies]
either = { workspace = true }
auto_impl = { workspace = true }
revm-state = { workspace = true }
derive-where = { workspace = true }
revm-bytecode = { workspace = true }
base-state-api = { workspace = true }
revm-precompile = { workspace = true }
revm-primitives = { workspace = true }
base-evm-context = { workspace = true }
revm-interpreter = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"], optional = true }
serde_json = { workspace = true, features = [
    "alloc",
    "preserve_order",
], optional = true }
[dev-dependencies]
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
revm-database = { workspace = true, features = ["serde"]}
[lints]
workspace = true

[features]
default = ["std"]
serde = [
    "dep:serde",
    "revm-primitives/serde",
    "revm-state/serde",
    "base-evm-context/serde",
    "revm-bytecode/serde",
    "revm-database/serde",
    "base-state-api/serde",
    "revm-interpreter/serde",
    "derive-where/serde",
    "either/serde",
]
serde-json = ["serde", "tracer"]
std = [
    "serde?/std",
    "revm-bytecode/std",
    "base-evm-context/std",
    "revm-database/std",
    "base-state-api/std",
    "revm-interpreter/std",
    "revm-precompile/std",
    "revm-primitives/std",
    "revm-state/std",
    "serde_json?/std",
    "serde_json?/preserve_order",
    "either/std",
]
tracer = ["std", "serde", "dep:serde", "dep:serde_json"]
