[package]
name = "base-evm-handler"
description = "Base EVM execution handlers and inspection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
]

[dependencies]
either = { workspace = true }
tracing = { workspace = true }
auto_impl = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
base-state = { workspace = true }
revm-state = { workspace = true }
revm-bytecode = { workspace = true }
alloy-hardforks = { workspace = true }
revm-precompile = { workspace = true }
revm-primitives = { workspace = true }
alloy-primitives = { workspace = true }
base-evm-context = { workspace = true }
revm-interpreter = { workspace = true }
base-common-precompiles = {workspace = true}
derive_more = { workspace = true, features = ["full"] }
base-common-types-rpc = { workspace = true, optional = true }
base-common-types-chain = {workspace = true, features = ["k256"]}
serde = { workspace = true, features = ["derive", "rc"], optional = true }
serde_json = { workspace = true, features = [
    "alloc",
    "preserve_order",
], optional = true }

[dev-dependencies]
alloy-signer = { workspace = true }
base-common-network = { workspace = true }
base-state = { workspace = true, features = ["serde"]}
serde_json = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["serde"] }

[lints]
workspace = true

[features]
default = ["std"]
serde = [
    "dep:serde",
    "revm-primitives/serde",
    "revm-state/serde",
    "base-evm-context/serde",
    "revm-bytecode/serde",
    "base-state/serde",
    "revm-interpreter/serde",
    "either/serde",
]
serde-json = ["serde", "tracer"]
std = [
    "serde?/std",
    "revm-bytecode/std",
    "base-evm-context/std",
    "base-state/std",
    "revm-interpreter/std",
    "revm-precompile/std",
    "revm-primitives/std",
    "revm-state/std",
    "serde_json?/std",
    "serde_json?/preserve_order",
    "either/std",
    "alloy-primitives/std",
    "base-common-types-chain/std",
    "alloy-eips/std",
    "derive_more/std",
    "thiserror/std",
    "base-common-types-rpc?/std",
    "tracing/std",
    "base-common-precompiles/std",
]
tracer = [
    "std",
    "serde",
    "dep:serde",
    "dep:serde_json",
]
asm-keccak = ["alloy-primitives/asm-keccak", "revm-primitives/asm-keccak"]
call-util = ["overrides"]
gmp = ["revm-precompile/gmp"]
overrides = ["dep:base-common-types-rpc"]
rpc = ["dep:base-common-types-rpc"]
secp256k1 = ["revm-precompile/secp256k1"]
alloydb = ["base-state/alloydb"]
arbitrary = ["revm-primitives/arbitrary"]
asyncdb = ["base-state/asyncdb"]
blst = ["revm-precompile/blst"]
bn = ["revm-precompile/bn"]
c-kzg = ["revm-precompile/c-kzg"]
dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3541",
    "optional_eip3607",
    "optional_eip7623",
    "optional_no_base_fee",
]
hashbrown = ["revm-interpreter/hashbrown", "revm-precompile/hashbrown"]
map-foldhash = ["revm-primitives/map-foldhash"]
memory_limit = ["base-evm-context/memory_limit", "revm-interpreter/memory_limit"]
optional_balance_check = ["base-evm-context/optional_balance_check"]
optional_block_gas_limit = ["base-evm-context/optional_block_gas_limit"]
optional_eip3541 = ["base-evm-context/optional_eip3541"]
optional_eip3607 = ["base-evm-context/optional_eip3607"]
optional_eip7623 = ["base-evm-context/optional_eip7623"]
optional_fee_charge = ["base-evm-context/optional_fee_charge"]
optional_no_base_fee = ["base-evm-context/optional_no_base_fee"]
optional_priority_fee_check = ["base-evm-context/optional_priority_fee_check"]
p256-aws-lc-rs = ["revm-precompile/p256-aws-lc-rs"]
parse = ["revm-bytecode/parse"]
portable = ["revm-precompile/portable"]
sha3-keccak = ["revm-primitives/sha3-keccak"]
