[package]
name = "base-common-genesis"
version.workspace = true
description = "Base genesis types"

edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
alloy-chains = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true }
base-common-types-chain = { workspace = true }
serde = { workspace = true, optional = true }
spin = { workspace = true, features = ["default"] }
arbitrary = { workspace = true, features = ["derive"], optional = true }
derive_more = { workspace = true, features = ["display", "from", "try_from"] }
[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
rstest = { workspace = true, features = ["default"] }
arbitrary = { workspace = true, features = ["derive"] }
toml = { workspace = true, features = ["parse", "serde"] }
rand = { workspace = true, features = ["default", "thread_rng"] }
alloy-primitives = { workspace = true, features = ["rand", "arbitrary"] }

[features]
default = []
test-utils = []
std = [
    "alloy-chains/std",
    "base-common-types-chain/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-sol-types/std",
    "derive_more/std",
    "serde?/std",
    "spin/std",
    "thiserror/std",
    "tracing/std",
]
arbitrary = [
    "alloy-chains/arbitrary",
    "base-common-types-chain/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-primitives/rand",
    "alloy-sol-types/arbitrary",
    "dep:arbitrary",
    "std",
]
serde = [
    "alloy-chains/serde",
    "base-common-types-chain/serde",
    "alloy-eips/serde",
    "alloy-hardforks/serde",
    "alloy-primitives/serde",
    "dep:serde",
]
