[package]
name = "base-node-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
rayon = { workspace = true }
fdlimit = { workspace = true }
alloy-rlp = { workspace = true }
humantime = { workspace = true }
reth-exex = { workspace = true }
jsonrpsee = { workspace = true }
reth-prune = { workspace = true }
reth-discv5 = { workspace = true }
reth-db-api = { workspace = true }
reth-config = { workspace = true }
reth-stages = { workspace = true }
reth-network = { workspace = true }
alloy-chains = { workspace = true }
reth-fs-util = { workspace = true }
alloy-eip2124 = { workspace = true }
base-metering = { workspace = true }
reth-provider = { workspace = true }
reth-node-core = { workspace = true }
reth-db-common = { workspace = true }
base-txpool-rpc = { workspace = true }
base-common-evm = { workspace = true }
reth-tokio-util = { workspace = true }
reth-chain-state = { workspace = true }
reth-engine-tree = { workspace = true }
reth-engine-util = { workspace = true }
reth-network-api = { workspace = true }
reth-node-events = { workspace = true }
reth-rpc-builder = { workspace = true }
reth-static-file = { workspace = true }
base-node-context = { workspace = true }
reth-engine-local = { workspace = true }
reth-node-metrics = { workspace = true }
base-common-network = {workspace = true}
base-tx-forwarding = { workspace = true }
reth-rpc-eth-types = { workspace = true }
reth-node-ethstats = { workspace = true }
base-shadow-indexer = { workspace = true }
base-txpool-tracing = { workspace = true }
reth-rpc-server-types = { workspace = true }
base-common-types-rpc = { workspace = true }
base-shadow-indexer-db = { workspace = true }
reth-engine-primitives = { workspace = true }
reth-invalid-block-hooks = { workspace = true }
base-execution-eip8130-rpc = { workspace = true }
base-execution-payload-types = {workspace = true}
url = { workspace = true, features = ["default"] }
reth-consensus-debug-client = { workspace = true }
clap = { workspace = true, features = ["default"] }
eyre = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["kzg"]}
reth-tasks = { workspace = true, features = ["rayon"]}
futures = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["attributes"]}
parking_lot = { workspace = true, features = ["default"] }
tokio-stream = { workspace = true, features = ["default"] }
reth-db = { workspace = true, features = ["default", "mdbx"] }
reth-downloaders = { workspace = true, features = ["default"] }
reth-network-p2p = { workspace = true, features = ["default"] }
base-common-types-chain = { workspace = true, features = ["reth"] }
reth-network-peers = { workspace = true, features = ["default"] }
base-common-chains = { workspace = true, features = ["default"] }
reth-storage-overlay = { workspace = true, features = ["rayon"] }
reth-tracing = { workspace = true, features = ["default", "std"] }
base-upgrade-signal = { workspace = true, features = ["default"] }
base-execution-exex = { workspace = true, features = ["metrics"] }
base-execution-trie = { workspace = true, features = ["metrics"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"]}
base-execution-txpool = { workspace = true, features = ["default"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
serde_json = { workspace = true, optional = false, features = ["alloc"]}
base-execution-rpc = { workspace = true, features = ["default", "client"] }
base-execution-payload-builder = { workspace = true, features = ["default"] }
base-execution-consensus = { workspace = true, features = ["default", "std"] }
base-common-types-payload = {workspace = true, features = ["serde", "std"]}
base-execution-evm = { workspace = true, features = ["default", "std", "rpc"] }
reth-primitives-traits = { workspace = true, features = ["secp256k1", "rayon"] }
secp256k1 = { workspace = true, features = ["global-context", "recovery", "std"] }
tokio = { workspace = true, features = ["default", "sync", "macros", "time", "rt-multi-thread"] }
base-evm-handler = { workspace = true, features = ["secp256k1", "blst", "c-kzg", "memory_limit", "p256-aws-lc-rs"] }

[dev-dependencies]
reth-trie = { workspace = true }
reth-db-common = { workspace = true }
alloy-genesis = { workspace = true  }
alloy-hardforks = { workspace = true }
base-common-evm = { workspace = true }
reth-prune-types = { workspace = true }
reth-stages-types = { workspace = true }
reth-payload-util = { workspace = true }
reth-rpc-eth-types = { workspace = true }
base-execution-rpc = { workspace = true }
base-common-genesis = { workspace = true }
base-common-network = { workspace = true }
reth-e2e-test-utils = { workspace = true  }
rstest = { workspace = true, features = ["default"] }
jsonrpsee = { workspace = true, features = ["client"] }
tempfile = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, features = [] }
base-protocol = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-db = { workspace = true, features = ["default", "test-utils"] }
reth-engine-primitives = {workspace = true, features = ["test-utils"]}
criterion = { workspace = true, features = ["default", "html_reports"] }
base-node-core = { workspace = true, features = ["default", "test-utils"] }
base-execution-payload-builder = { workspace = true, features = ["test-utils"] }
base-execution-evm = { workspace = true, features = ["default", "std", "test-utils"] }
base-common-types-chain = { workspace = true, features = ["alloy", "test-utils", "serde", "std"] }
[[bench]]
name = "provider"
harness = false

[[test]]
name = "e2e_testsuite"
path = "tests/e2e-testsuite/main.rs"

[[test]]
name = "engine_tree"
path = "tests/engine-tree/main.rs"
required-features = ["test-utils"]

[[test]]
name = "rocksdb"
path = "tests/rocksdb/main.rs"
required-features = ["test-utils"]

[[test]]
name = "testsuite_framework"
path = "tests/testsuite-framework/main.rs"
required-features = ["test-utils"]

[features]
default = ["reth-codec"]
asm-keccak = ["alloy-primitives/asm-keccak", "reth-node-core/asm-keccak", "base-evm-handler/asm-keccak"]
keccak-cache-global = ["alloy-primitives/keccak-cache-global", "reth-node-core/keccak-cache-global"]
js-tracer = ["reth-rpc-eth-types/js-tracer", "base-execution-rpc/js-tracer"]
test-utils = [
    "base-common-chains/test-utils",
    "base-common-types-chain/arbitrary",
    "base-execution-exex/test-utils",
    "reth-chain-state/test-utils",
    "reth-codec",
    "reth-db-api/test-utils",
    "reth-db/test-utils",
    "reth-network/test-utils",
    "base-execution-payload-builder/test-utils",
    "reth-primitives-traits/test-utils",
    "reth-provider/test-utils",
    "base-execution-evm/test-utils",
    "reth-stages-types/test-utils",
    "reth-tasks/test-utils",
    "base-execution-txpool/test-utils",
    "reth-trie/test-utils",
    "base-execution-consensus/test-utils",
    "reth-engine-tree/test-utils",
    "reth-downloaders/test-utils",
    "reth-network-p2p/test-utils",
    "reth-stages/test-utils",
]
reth-codec = []
trie-debug = ["reth-engine-tree/trie-debug", "reth-engine-primitives/trie-debug", "reth-node-core/trie-debug"]
