default:
  @just --list

# Upgrade the OPSuccinct Fault Dispute Game implementation.
upgrade-fault-dispute-game:
    #!/usr/bin/env bash
    set -euo pipefail

    # cd into contracts directory.
    cd ../contracts

    # Install dependencies.
    forge install
    
    # Run the forge upgrade script.
    if [ "${DRY_RUN}" = "false" ]; then
        forge script script/fp/UpgradeOPSuccinctFDG.s.sol:UpgradeOPSuccinctFDG \
            --rpc-url $L1_RPC \
            --private-key $PRIVATE_KEY \
            --etherscan-api-key $ETHERSCAN_API_KEY \
            --broadcast
    else
        forge script script/fp/UpgradeOPSuccinctFDG.s.sol:UpgradeOPSuccinctFDG \
            --rpc-url $L1_RPC \
            --private-key $PRIVATE_KEY \
            --etherscan-api-key $ETHERSCAN_API_KEY
    fi
