[package]
name = "base-execution-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A payload builder for base-reth that builds Base payloads."

[lints]
workspace = true

[dependencies]
metrics = { workspace = true  }
alloy-rlp = { workspace = true }
jsonrpsee = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
serde = {workspace = true, features = ["std"]}
base-execution-evm-machine = {workspace = true}
base-execution-evm-runtime = {workspace = true}
base-common-runtime-tasks = { workspace = true }
base-execution-state-memory = {workspace = true}
moka = { workspace = true, features = ["sync"] }
base-consensus-batch-types = { workspace = true }
alloy-eips = {workspace = true, features = ["std"]}
eyre = { workspace = true, features = ["default"] }
base-execution-evm-primitives = { workspace = true }
base-execution-state-provider = { workspace = true }
derive_more = {workspace = true, features = ["full"]}
base-common-observability-events = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
futures-core = { workspace = true, features = ["default"] }
tokio-stream = { workspace = true, features = ["default"] }
tracing = {workspace = true, features = ["attributes", "std"]}
alloy-primitives = {workspace = true, features = ["map-foldhash"]}
base-execution-evm-precompiles = {workspace = true, features = ["std"]}
base-execution-state-api = { workspace = true, features = ["default"] }
base-execution-state-tasks = {features = ["default"], workspace = true}
base-execution-state-types = {features = ["default"], workspace = true}
base-execution-txpool-pool = {workspace = true, features = ["default"]}
base-common-types-chain = {features = ["k256", "reth", "std"], workspace = true}
base-execution-payload-types = {workspace = true, features = ["default"]}
base-common-types-payload = {workspace = true, features = ["serde", "std"]}
base-common-chain-config = {workspace = true, features = ["default", "std"]}
base-common-observability-metrics = {features = ["metrics"], workspace = true}
base-execution-evm-blocks = {workspace = true, features = ["default", "std", "witness"]}

[dev-dependencies]
serde_json = { workspace = true }
alloy-sol-types = { workspace = true }
base-common-types-payload = { workspace = true }
base-execution-evm-runtime = { workspace = true }
base-common-client-ethereum = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
url = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default"] }
base-execution-evm-primitives = { workspace = true }
base-execution-state-maintenance = { workspace = true }
alloy-genesis = { workspace = true, features = ["std"] }
base-node-service = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
tokio = {workspace = true, features = ["default", "rt", "sync"]}
base-testing-devnet = { workspace = true, features = ["test-utils"] }
base-common-chain-config = { workspace = true, features = ["std"] }
base-common-types-chain = { workspace = true, features = ["reth"] }
base-testing-support = { workspace = true, features = ["contracts"] }
base-common-types-rpc = {workspace = true, features = ["default", "std"]}
base-execution-txpool-pool = { workspace = true, features = ["test-utils"] }
base-execution-state-provider = { workspace = true, features = ["test-utils"] }
base-common-observability-events = { workspace = true, features = ["test-utils"] }
base-execution-evm-blocks = { workspace = true, features = ["default", "test-utils"] }
base-execution-state-database = { workspace = true, features = ["default", "test-utils"] }

[features]
default = ["metrics"]
metrics = ["base-execution-evm-runtime/metrics", "base-common-observability-metrics/metrics", "base-common-observability-events/metrics", "base-execution-evm-blocks/metrics"]
test-utils = ["base-execution-state-types/test-utils", "base-common-types-chain/test-utils", "tokio/rt", "base-execution-state-tasks/test-utils", "base-execution-state-memory/test-utils"]
