[package]
name = "base-proof-types"
description = "Shared primitive types and traits for the Base proof system"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
alloy-eips = { workspace = true }
async-trait = { workspace = true }
alloy-chains = { workspace = true }
alloy-primitives = { workspace = true }
base-common-chain-config = { workspace = true }
jsonrpsee = { workspace = true, optional = true }
base-proof-witness-preimage = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
hex = { workspace = true, features = ["default"] }
rstest = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }

[features]
default = []
std = [
    "alloy-chains/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "base-common-chain-config/std",
    "base-proof-witness-preimage/std",
    "serde?/std",
    "thiserror/std",
]
serde = [
    "alloy-chains/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "base-common-chain-config/serde",
    "base-proof-witness-preimage/serde",
    "dep:serde",
]
rpc-server = ["dep:jsonrpsee", "jsonrpsee/macros", "jsonrpsee/server", "serde", "std"]
rpc-client = ["dep:jsonrpsee", "jsonrpsee/http-client", "jsonrpsee/macros", "serde", "std"]
