//! Metrics for the derivation pipeline.

base_metrics::define_metrics! {
    base_consensus_derive

    #[describe("The block height of the pipeline l1 origin")]
    pipeline_origin: gauge,

    #[describe("The latest L2 block height that the pipeline stepped on")]
    pipeline_step_block: gauge,

    #[describe("If the batch reader is set")]
    pipeline_batch_reader_set: gauge,

    #[describe("The amount of time it takes to advance the pipeline origin")]
    pipeline_origin_advance: histogram,

    #[describe("The number of frames in the frame queue")]
    pipeline_frame_queue_buffer: gauge,

    #[describe("The memory size of frames held in the frame queue")]
    pipeline_frame_queue_mem: gauge,

    #[describe("The number of channels in the channel assembler stage")]
    pipeline_channel_buffer: gauge,

    #[describe("The memory size of channels held in the channel assembler stage")]
    pipeline_channel_mem: gauge,

    #[describe("The number of blocks until the next channel times out")]
    pipeline_channel_timeout: gauge,

    #[describe("The maximum rlp byte size of a channel")]
    pipeline_max_rlp_bytes: gauge,

    #[describe("The number of batches held in the batch stream stage")]
    pipeline_batch_buffer: gauge,

    #[describe("The memory size of batches held in the batch stream stage")]
    pipeline_batch_mem: gauge,

    #[describe("The read batches")]
    #[label(name = "type", default = ["single", "span"])]
    pipeline_read_batches: gauge,

    #[describe("The total number of pipeline steps on the derivation pipeline")]
    pipeline_steps: gauge,

    #[describe("The total number of prepared attributes generated by the derivation pipeline")]
    pipeline_prepared_attributes: gauge,

    #[describe("Number of times the pipeline has been signalled")]
    #[label(name = "type", default = ["reset", "activation", "flush_channel"])]
    pipeline_signals: gauge,

    #[describe("Earliest l1 blocks height")]
    pipeline_l1_blocks_start: gauge,

    #[describe("Latest l1 blocks height")]
    pipeline_l1_blocks_end: gauge,

    #[describe("The number of payload attributes in the current span")]
    pipeline_derived_span_size: gauge,

    #[describe("The number of transactions in the latest derived payload attributes")]
    pipeline_latest_payload_tx_count: gauge,

    #[describe("The source of pipeline data")]
    #[label(name = "source", default = ["blobs", "calldata"])]
    pipeline_data_availability_provider: gauge,

    #[describe("The validity of the batch being processed")]
    #[label(validity)]
    pipeline_batch_validity: gauge,

    #[describe("The time it takes to validate a span batch")]
    pipeline_check_batch_prefix: histogram,

    #[describe("The time it takes to build payload attributes")]
    pipeline_attributes_build_duration: histogram,

    #[describe("The number of payload attributes buffered in the pipeline")]
    pipeline_payload_attributes_buffer: gauge,

    #[describe("The latest block number for a system config update")]
    pipeline_latest_sys_config_update: gauge,

    #[describe("The block height at which a system config update errored")]
    pipeline_sys_config_update_error: gauge,

    #[describe("The latest decompressed batch size")]
    pipeline_latest_decompressed_batch_size: gauge,

    #[describe("The latest decompressed batch type")]
    pipeline_latest_decompressed_batch_type: gauge,
}
