// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/succinctlabs/op-succinct-go/proposer/db/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/succinctlabs/op-succinct-go/proposer/db/ent/proofrequest"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ProofRequest is the client for interacting with the ProofRequest builders.
	ProofRequest *ProofRequestClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ProofRequest = NewProofRequestClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ProofRequest: NewProofRequestClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ProofRequest: NewProofRequestClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ProofRequest.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ProofRequest.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ProofRequest.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ProofRequestMutation:
		return c.ProofRequest.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ProofRequestClient is a client for the ProofRequest schema.
type ProofRequestClient struct {
	config
}

// NewProofRequestClient returns a client for the ProofRequest from the given config.
func NewProofRequestClient(c config) *ProofRequestClient {
	return &ProofRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `proofrequest.Hooks(f(g(h())))`.
func (c *ProofRequestClient) Use(hooks ...Hook) {
	c.hooks.ProofRequest = append(c.hooks.ProofRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `proofrequest.Intercept(f(g(h())))`.
func (c *ProofRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProofRequest = append(c.inters.ProofRequest, interceptors...)
}

// Create returns a builder for creating a ProofRequest entity.
func (c *ProofRequestClient) Create() *ProofRequestCreate {
	mutation := newProofRequestMutation(c.config, OpCreate)
	return &ProofRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProofRequest entities.
func (c *ProofRequestClient) CreateBulk(builders ...*ProofRequestCreate) *ProofRequestCreateBulk {
	return &ProofRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProofRequestClient) MapCreateBulk(slice any, setFunc func(*ProofRequestCreate, int)) *ProofRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProofRequestCreateBulk{err: fmt.Errorf("calling to ProofRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProofRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProofRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProofRequest.
func (c *ProofRequestClient) Update() *ProofRequestUpdate {
	mutation := newProofRequestMutation(c.config, OpUpdate)
	return &ProofRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProofRequestClient) UpdateOne(pr *ProofRequest) *ProofRequestUpdateOne {
	mutation := newProofRequestMutation(c.config, OpUpdateOne, withProofRequest(pr))
	return &ProofRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProofRequestClient) UpdateOneID(id int) *ProofRequestUpdateOne {
	mutation := newProofRequestMutation(c.config, OpUpdateOne, withProofRequestID(id))
	return &ProofRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProofRequest.
func (c *ProofRequestClient) Delete() *ProofRequestDelete {
	mutation := newProofRequestMutation(c.config, OpDelete)
	return &ProofRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProofRequestClient) DeleteOne(pr *ProofRequest) *ProofRequestDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProofRequestClient) DeleteOneID(id int) *ProofRequestDeleteOne {
	builder := c.Delete().Where(proofrequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProofRequestDeleteOne{builder}
}

// Query returns a query builder for ProofRequest.
func (c *ProofRequestClient) Query() *ProofRequestQuery {
	return &ProofRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProofRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a ProofRequest entity by its id.
func (c *ProofRequestClient) Get(ctx context.Context, id int) (*ProofRequest, error) {
	return c.Query().Where(proofrequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProofRequestClient) GetX(ctx context.Context, id int) *ProofRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProofRequestClient) Hooks() []Hook {
	return c.hooks.ProofRequest
}

// Interceptors returns the client interceptors.
func (c *ProofRequestClient) Interceptors() []Interceptor {
	return c.inters.ProofRequest
}

func (c *ProofRequestClient) mutate(ctx context.Context, m *ProofRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProofRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProofRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProofRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProofRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProofRequest mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ProofRequest []ent.Hook
	}
	inters struct {
		ProofRequest []ent.Interceptor
	}
)
