[package]
name = "base-consensus-providers"
version.workspace = true
description = "Alloy Backed Providers"

edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
c-kzg = { workspace = true }
tower = { workspace = true }
reth-db = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
base-metrics = { workspace = true }
reth-provider = { workspace = true }
base-protocol = { workspace = true }
alloy-genesis = { workspace = true }
reth-rpc-layer = { workspace = true }
alloy-transport = { workspace = true }
reth-storage-api = { workspace = true }
reth-trie-common = { workspace = true }
base-common-network = {workspace = true}
base-common-genesis = { workspace = true }
base-consensus-derive = { workspace = true }
metrics = { workspace = true, optional = true }
serde = { workspace = true, features = ["std"] }
lru = { workspace = true, features = ["default"] }
url = { workspace = true, features = ["default"] }
thiserror = { workspace = true, features = ["std"] }
alloy-serde = { workspace = true, features = ["std"] }
reqwest = { workspace = true, features = ["default"] }
base-common-rpc-types = { workspace = true, features = []}
alloy-primitives = { workspace = true, features = ["map"] }
alloy-eips = { workspace = true, features = ["kzg", "std"] }
tokio = { workspace = true, features = ["default", "time"] }
http-body-util = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["std"]}
alloy-rpc-client = { workspace = true, features = ["default"] }
alloy-provider = { workspace = true, features = ["default", "ws", "reqwest"] }
alloy-transport-http = { workspace = true, features = ["default", "reqwest", "reqwest-rustls-tls", "hyper", "hyper-tls"] }

[dev-dependencies]
reth-db-common = { workspace = true }
base-common-rpc-types = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
httpmock = { workspace = true, features = ["default"] }
reth-provider = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["default", "macros", "test-util"] }

[features]
default = []
metrics = [
	"base-consensus-derive/metrics",
	"base-metrics/metrics",
	"dep:metrics",
]
