[package]
name = "base-execution-txpool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Base Transaction Pool"

[lints]
workspace = true

[dependencies]
revm = { workspace = true }
serde = { workspace = true }
c-kzg = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
derive_more = { workspace = true }
async-trait = { workspace = true }
base-metrics = { workspace = true }
reth-provider = { workspace = true }
alloy-consensus = { workspace = true }
base-common-flz = { workspace = true }
base-common-evm = { workspace = true }
base-evm-context = { workspace = true }
base-common-genesis = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-eip8130 = { workspace = true }
base-precompile-storage = { workspace = true }
base-common-precompiles = { workspace = true }
base-execution-chainspec = { workspace = true }
metrics = { workspace = true, optional = true }
base-observability-events = { workspace = true }
lru = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
parking_lot = { workspace = true, features = ["default"] }
tokio-stream = { workspace = true, features = ["default"] }
reth-storage-api = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["reth"] }
base-common-chains = { workspace = true, features = ["default"] }
base-execution-evm = { workspace = true, features = ["default"] }
reth-eth-wire-types = { workspace = true, features = ["default"] }
reth-execution-types = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"] }
tokio = { workspace = true, features = ["default", "sync", "rt", "time"] }
jsonrpsee = { workspace = true, features = ["http-client", "server", "macros"] }
[dev-dependencies]
reth-tasks = { workspace = true }
alloy-signer = { workspace = true }
alloy-sol-types = { workspace = true }
base-test-utils = { workspace = true }
alloy-signer-local = { workspace = true }
metrics-util = { workspace = true, features = ["debugging"] }
reth-provider = { workspace = true, features = ["test-utils"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["default", "time", "rt-multi-thread", "macros"] }

[features]
default = [ "metrics" ]
metrics = [
    "base-common-evm/metrics",
    "base-metrics/metrics",
    "base-observability-events/metrics",
    "dep:metrics",
]
