//! Conversions between enclave-native and host-side proof types.
//!
//! Both `Proposal` (from `base-proof-primitives`) and `EnclaveProposal` (from
//! `base-proof-tee-nitro-enclave`) are foreign types, so `From` impls are
//! blocked by the orphan rule. Conversions are exposed as methods on a
//! [`Convert`] unit struct instead.

use base_proof_primitives::{ProofResult, Proposal};
use base_proof_tee_nitro_enclave::{Proposal as EnclaveProposal, TeeProofResult};

/// Enclave ↔ host type conversions.
#[derive(Debug)]
pub struct Convert;

impl Convert {
    /// Convert an enclave-native proposal to the host-side primitives type.
    pub fn proposal(p: EnclaveProposal) -> Proposal {
        Proposal {
            output_root: p.output_root,
            signature: p.signature,
            l1_origin_hash: p.l1_origin_hash,
            l1_origin_number: p.l1_origin_number,
            l2_block_number: p.l2_block_number,
            prev_output_root: p.prev_output_root,
            config_hash: p.config_hash,
        }
    }

    /// Convert a [`TeeProofResult`] to a [`ProofResult::Tee`].
    pub fn proof_result(t: TeeProofResult) -> ProofResult {
        ProofResult::Tee {
            aggregate_proposal: Self::proposal(t.aggregate_proposal),
            proposals: t.proposals.into_iter().map(Self::proposal).collect(),
        }
    }
}

#[cfg(test)]
mod tests {
    use alloy_primitives::{B256, U256, address, b256};
    use base_proof_primitives::ProofJournal as PrimitivesJournal;
    use base_proof_tee_nitro_enclave::ProofJournal as EnclaveJournal;

    /// Enclave and primitives `ProofJournal::encode()` must produce identical
    /// bytes for the same inputs. A mismatch means on-chain verification would
    /// reject proofs generated by the enclave.
    #[test]
    fn proof_journal_encode_parity() {
        let enclave = EnclaveJournal {
            proposer: address!("f39Fd6e51aad88F6F4ce6aB8827279cffFb92266"),
            l1_origin_hash: b256!(
                "2222222222222222222222222222222222222222222222222222222222222222"
            ),
            prev_output_root: b256!(
                "3333333333333333333333333333333333333333333333333333333333333333"
            ),
            starting_l2_block: U256::from(999),
            output_root: b256!("4444444444444444444444444444444444444444444444444444444444444444"),
            ending_l2_block: U256::from(1000),
            intermediate_roots: vec![
                b256!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
                b256!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
            ],
            config_hash: b256!("1111111111111111111111111111111111111111111111111111111111111111"),
            tee_image_hash: b256!(
                "5555555555555555555555555555555555555555555555555555555555555555"
            ),
        };

        let primitives = PrimitivesJournal {
            proposer: enclave.proposer,
            l1_origin_hash: enclave.l1_origin_hash,
            prev_output_root: enclave.prev_output_root,
            starting_l2_block: enclave.starting_l2_block,
            output_root: enclave.output_root,
            ending_l2_block: enclave.ending_l2_block,
            intermediate_roots: enclave.intermediate_roots.clone(),
            config_hash: enclave.config_hash,
            tee_image_hash: enclave.tee_image_hash,
        };

        assert_eq!(enclave.encode(), primitives.encode());
    }

    /// Empty intermediate roots must also produce identical bytes.
    #[test]
    fn proof_journal_encode_parity_no_intermediate_roots() {
        let enclave = EnclaveJournal {
            proposer: address!("f39Fd6e51aad88F6F4ce6aB8827279cffFb92266"),
            l1_origin_hash: B256::ZERO,
            prev_output_root: B256::ZERO,
            starting_l2_block: U256::ZERO,
            output_root: B256::ZERO,
            ending_l2_block: U256::ZERO,
            intermediate_roots: vec![],
            config_hash: B256::ZERO,
            tee_image_hash: B256::ZERO,
        };

        let primitives = PrimitivesJournal {
            proposer: enclave.proposer,
            l1_origin_hash: enclave.l1_origin_hash,
            prev_output_root: enclave.prev_output_root,
            starting_l2_block: enclave.starting_l2_block,
            output_root: enclave.output_root,
            ending_l2_block: enclave.ending_l2_block,
            intermediate_roots: enclave.intermediate_roots.clone(),
            config_hash: enclave.config_hash,
            tee_image_hash: enclave.tee_image_hash,
        };

        assert_eq!(enclave.encode(), primitives.encode());
    }
}
