[package]
name = "base-metering"
description = "Metering RPC for Base node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
revm = { workspace = true }
jsonrpsee = { workspace = true }
derive_more = { workspace = true }
base-bundles = { workspace = true }
revm-bytecode = { workspace = true }
reth-provider = { workspace = true }
base-common-evm = { workspace = true }
base-evm-context = { workspace = true }
alloy-primitives = { workspace = true }
base-evm-handler = { workspace = true }
reth-primitives-traits = { workspace = true }
base-common-precompiles = { workspace = true }
serde = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
eyre = { workspace = true, features = ["default"] }
base-execution-payload-builder = { workspace = true }
alloy-eips = { workspace = true, features = ["std"] }
base-common-consensus = { workspace = true, features = ["std"]}
base-execution-evm = { workspace = true, features = ["default"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
[dev-dependencies]
revm = { workspace = true }
serde_json = { workspace = true }
revm-bytecode = { workspace = true }
reth-db-common = { workspace = true }
alloy-sol-types = { workspace = true }
base-common-network = { workspace = true }
url = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default"] }
base-common-rpc-types-engine = { workspace = true }
tokio = { workspace = true, features = ["default"] }
alloy-genesis = { workspace = true, features = ["std"] }
base-node-core = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
base-test-utils = { workspace = true, features = ["contracts"] }
base-common-consensus = { workspace = true, features = ["reth"] }
base-node-runner = { workspace = true, features = ["test-utils"] }
reth-db = { workspace = true, features = ["default", "test-utils"] }
base-execution-txpool = { workspace = true, features = ["test-utils"] }
base-common-rpc-types = {workspace = true, features = ["default", "std"]}
