[package]
name = "base-metering"
description = "Metering RPC for Base node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
jsonrpsee = { workspace = true }
derive_more = { workspace = true }
reth-provider = { workspace = true }
alloy-primitives = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-evm-runtime = {workspace = true}
serde = { workspace = true, features = ["std"] }
base-execution-evm-machine = { workspace = true }
tracing = { workspace = true, features = ["std"] }
base-execution-payload-types = { workspace = true }
eyre = { workspace = true, features = ["default"] }
base-execution-evm-primitives = { workspace = true }
alloy-eips = { workspace = true, features = ["std"] }
base-execution-evm-precompiles = { workspace = true }
base-execution-payload-builder = { workspace = true }
base-common-types-chain = { workspace = true, features = ["std"]}
base-common-chain-config = { workspace = true, features = ["std"] }
base-execution-evm-blocks = { workspace = true, features = ["default"] }

[dev-dependencies]
serde_json = { workspace = true }
reth-db-common = { workspace = true }
alloy-sol-types = { workspace = true }
base-common-types-payload = { workspace = true }
base-execution-evm-runtime = { workspace = true }
base-common-client-ethereum = { workspace = true }
url = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default"] }
base-execution-evm-primitives = { workspace = true }
tokio = { workspace = true, features = ["default"] }
alloy-genesis = { workspace = true, features = ["std"] }
base-node-core = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
base-node-runner = { workspace = true, features = ["test-utils"] }
base-common-types-chain = { workspace = true, features = ["reth"] }
reth-db = { workspace = true, features = ["default", "test-utils"] }
base-testing-support = { workspace = true, features = ["contracts"] }
base-execution-txpool = { workspace = true, features = ["test-utils"] }
base-common-types-rpc = {workspace = true, features = ["default", "std"]}
