[package]
name = "base-execution-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution extensions for Base"

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
reth-exex = { workspace = true }
alloy-eips = { workspace = true }
base-common-types-chain = { workspace = true }
base-execution-state-trie = { workspace = true }
eyre = { workspace = true, features = ["default"] }
base-execution-state-provider = { workspace = true }
tokio = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
base-execution-state-types = { workspace = true, features = ["default"] }
base-execution-state-tasks = { workspace = true, features = ["serde-bincode-compat"] }

[dev-dependencies]
reth-exex-test-utils = { workspace = true }
reth-primitives-traits = { workspace = true }
tempfile = { workspace = true, features = ["default"] }
base-node-core = { workspace = true, features = ["default"] }
base-common-chain-config = { workspace = true, features = ["std"] }
base-common-types-chain = { workspace = true, features = ["reth", "serde", "std"] }
base-execution-state-database = { workspace = true, features = ["default", "test-utils"] }

[package.metadata.cargo-udeps.ignore]
development = [
    "reth-node-builder",
    "base-node-core",
    "base-common-chain-config",
    "tempfile.workspace",
]

[features]
test-utils = [
    "base-node-core/test-utils",
    "base-execution-state-database/test-utils",
    "reth-primitives-traits/test-utils",
    "base-execution-state-provider/test-utils",
    "base-execution-state-trie/test-utils",
]
metrics = ["base-execution-state-tasks/metrics", "base-execution-state-trie/metrics"]
