[package]
name = "base-execution-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution extensions for Base"

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
reth-exex = { workspace = true }
reth-trie = { workspace = true }
alloy-eips = { workspace = true }
reth-provider = { workspace = true }
base-common-consensus = { workspace = true }
eyre = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
reth-execution-types = { workspace = true, features = ["default"] }
base-execution-trie = { workspace = true, features = ["serde-bincode-compat"] }
[dev-dependencies]
reth-exex-test-utils = { workspace = true }
reth-primitives-traits = { workspace = true }
tempfile = { workspace = true, features = ["default"] }
base-node-core = { workspace = true, features = ["default"] }
reth-db = { workspace = true, features = ["default", "test-utils"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["reth", "serde", "std"] }
[package.metadata.cargo-udeps.ignore]
development = [
    "reth-node-builder",
    "base-node-core",
    "base-execution-chainspec",
    "tempfile.workspace",
]

[features]
test-utils = [
    "base-node-core/test-utils",
    "reth-db/test-utils",
    "base-node-core/test-utils",
    "reth-primitives-traits/test-utils",
    "reth-provider/test-utils",
    "reth-trie/test-utils",
]
metrics = ["base-execution-trie/metrics", "reth-trie/metrics"]
