[package]
name = "base-consensus-gossip"
version.workspace = true
description = "Gossip protocol implementation for Base"

edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { workspace = true }
snap = { workspace = true }
serde_repr = { workspace = true }
base-protocol = { workspace = true }
libp2p-stream = { workspace = true }
base-consensus-disc = { workspace = true }
base-common-chain-config = { workspace = true }
metrics = { workspace = true, optional = true }
serde = { workspace = true, features = ["std"] }
lru = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["std"] }
discv5 = { workspace = true, features = ["libp2p"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["std"] }
base-consensus-network-service = { workspace = true }
futures = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
ipnet = { workspace = true, features = ["default", "serde"] }
libp2p-identity = { workspace = true, features = ["secp256k1"] }
alloy-primitives = { workspace = true, features = ["k256", "getrandom"] }
base-common-types-chain = { workspace = true, features = ["k256", "std"] }
base-common-types-payload = {workspace = true, features = ["std", "serde"]}
derive_more = { workspace = true, features = ["display", "deref", "debug"] }
libp2p = { workspace = true, features = ["macros", "tokio", "tcp", "dns", "noise", "gossipsub", "ping", "yamux", "identify"] }

[dev-dependencies]
alloy-rlp = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
alloy-chains = { workspace = true, features = ["std"] }
arbitrary = { workspace = true, features = ["derive"] }
tempfile = { workspace = true, features = ["default"] }
multihash = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["arbitrary"] }
rand = { workspace = true, features = ["default", "thread_rng"] }
base-common-types-chain = { workspace = true, features = ["arbitrary", "k256", "std"] }

[features]
default = []
metrics = [
    "base-consensus-disc/metrics",
    "base-common-observability-metrics/metrics",
    "dep:metrics",
    "libp2p/metrics",
]
