[package]
name = "base-proof-host"
description = "Generic host-side infrastructure for the Base fault proof host."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
ark-ff = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
alloy-rlp = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
alloy-genesis = { workspace = true }
alloy-transport = { workspace = true }
alloy-primitives = { workspace = true }
base-proof-client = { workspace = true }
base-common-runtime = { workspace = true }
base-consensus-batch = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
base-consensus-source = { workspace = true }
base-proof-witness-mpt = { workspace = true }
metrics = { workspace = true, optional = true }
base-common-client-rollup = { workspace = true }
backon = { workspace = true, features = ["default"] }
chrono = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
tokio-util = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, features = [] }
base-proof-execution = { workspace = true, features = ["std"] }
base-common-types-chain = { workspace = true, features = ["std"] }
base-proof-types = { workspace = true, features = ["serde", "std"] }
base-proof-witness-preimage = { workspace = true, features = ["std"] }
base-common-client-ethereum = { workspace = true, features = ["default"] }
base-proof-service-protocol = { workspace = true, features = ["default"] }
base-common-chain-config = { workspace = true, features = ["serde", "std"] }
base-common-types-payload = { workspace = true, features = ["serde", "std"] }
tokio = { features = ["default", "macros", "rt", "sync", "time"], workspace = true }
base-execution-evm-runtime = { features = ["blst", "c-kzg", "portable", "secp256k1", "std"], workspace = true }

[dev-dependencies]
proptest = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "test-util"] }

[features]
metrics = [
    "base-execution-evm-runtime/metrics",
    "base-consensus-source/metrics",
    "base-common-observability-metrics/metrics",
    "dep:metrics",
]
