[package]
name = "base-proof-host"
description = "Generic host-side infrastructure for the Base fault proof host."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
ark-ff = { workspace = true }
tracing = { workspace = true }
alloy-rlp = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
alloy-genesis = { workspace = true }
base-proof-witness-mpt = { workspace = true }
alloy-transport = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
metrics = { workspace = true, optional = true }
base-common-client-rollup = { workspace = true }
base-consensus-batch-types = { workspace = true }
tokio = { workspace = true, features = ["default"] }
base-consensus-source-providers = { workspace = true }
futures = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
base-common-types-rpc = { workspace = true, features = []}
base-proof-client = { workspace = true, features = ["std"] }
base-proof-witness-preimage = { workspace = true, features = ["std"] }
base-common-types-chain = { workspace = true, features = ["std"]}
base-common-client-ethereum = {workspace = true, features = ["default"]}
base-proof-types-protocol = { workspace = true, features = ["serde", "std"] }
base-common-chain-config = { workspace = true, features = ["serde", "std"] }
base-common-types-payload = { workspace = true, features = ["serde", "std"] }
rocksdb = { workspace = true, features = ["snappy", "bindgen-runtime"], optional = true }
base-execution-evm-runtime = {features = ["blst", "c-kzg", "portable", "secp256k1", "std"],  workspace = true}
base-proof-execution-client = { workspace = true, features = ["std"] }

[dev-dependencies]
proptest = { workspace = true, features = ["default"] }

[features]
disk = ["dep:rocksdb"]
metrics = ["base-execution-evm-runtime/metrics", "base-consensus-source-providers/metrics", "base-common-observability-metrics/metrics", "dep:metrics"]
precompiles = []
