[package]
name = "base-proof-host"
description = "Generic host-side infrastructure for the Base fault proof host."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
ark-ff = { workspace = true }
tracing = { workspace = true }
alloy-rlp = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
base-metrics = { workspace = true }
alloy-genesis = { workspace = true }
base-protocol = { workspace = true }
base-proof-mpt = { workspace = true }
alloy-transport = { workspace = true }
base-common-evm = { workspace = true }
alloy-primitives = { workspace = true }
base-optimism-rpc = { workspace = true }
base-common-network = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
base-consensus-providers = { workspace = true }
metrics = { workspace = true, optional = true }
tokio = { workspace = true, features = ["default"] }
base-proof = { workspace = true, features = ["std"] }
futures = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, features = []}
base-proof-client = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["default"] }
base-proof-preimage = { workspace = true, features = ["std"] }
base-common-types-chain = { workspace = true, features = ["std"]}
base-proof-primitives = { workspace = true, features = ["serde", "std"] }
base-common-chain-config = { workspace = true, features = ["serde", "std"] }
base-common-types-payload = { workspace = true, features = ["serde", "std"] }
rocksdb = { workspace = true, features = ["snappy", "bindgen-runtime"], optional = true }
base-evm-handler = { workspace = true, features = ["std", "c-kzg", "secp256k1", "portable", "blst"], optional = true }

[dev-dependencies]
proptest = { workspace = true, features = ["default"] }

[features]
disk = [ "dep:rocksdb" ]
metrics = [
    "base-common-evm/metrics",
    "base-consensus-providers/metrics",
    "base-metrics/metrics",
    "dep:metrics",
]
precompiles = [ "dep:base-evm-handler" ]
