//! Types for the prover module.

use op_enclave_core::Proposal;

use crate::rpc::L2BlockRef;

/// A proposal generated by the prover with associated metadata.
#[derive(Debug, Clone)]
pub struct ProverProposal {
    /// The proposal from the enclave.
    pub output: Proposal,
    /// The first L2 block in the proposal range.
    pub from: L2BlockRef,
    /// The last L2 block in the proposal range.
    pub to: L2BlockRef,
    /// Whether this block contains withdrawals.
    pub has_withdrawals: bool,
}

#[cfg(test)]
pub(crate) mod test_helpers {
    use super::*;
    use crate::rpc::L1BlockId;
    use alloy_primitives::{B256, Bytes, U256};

    /// Creates a test `ProverProposal` with the given from/to block numbers and withdrawal flag.
    pub(crate) fn test_proposal(
        from_number: u64,
        to_number: u64,
        has_withdrawals: bool,
    ) -> ProverProposal {
        ProverProposal {
            output: Proposal {
                output_root: B256::repeat_byte(0x01),
                signature: Bytes::from(vec![0xab; 65]),
                l1_origin_hash: B256::repeat_byte(0x02),
                l2_block_number: U256::from(to_number),
                prev_output_root: B256::repeat_byte(0x03),
                config_hash: B256::repeat_byte(0x04),
            },
            from: L2BlockRef {
                hash: B256::repeat_byte(0x10),
                number: from_number,
                parent_hash: B256::repeat_byte(0x11),
                timestamp: 1_000_000 + from_number,
                l1origin: L1BlockId {
                    hash: B256::repeat_byte(0x20),
                    number: 100 + from_number,
                },
                sequence_number: 0,
            },
            to: L2BlockRef {
                hash: B256::repeat_byte(0x30),
                number: to_number,
                parent_hash: B256::repeat_byte(0x31),
                timestamp: 1_000_000 + to_number,
                l1origin: L1BlockId {
                    hash: B256::repeat_byte(0x40),
                    number: 100 + to_number,
                },
                sequence_number: 0,
            },
            has_withdrawals,
        }
    }
}
