[package]
name = "base-alloy-evm"
description = "EVM implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-evm.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true

# base
base-alloy-flz.workspace = true
base-alloy-chains.workspace = true
base-revm = { workspace = true, features = ["alloy"] }
base-alloy-consensus = { workspace = true, features = ["evm"] }

# revm
revm.workspace = true

# misc
auto_impl.workspace = true
thiserror.workspace = true

# execution (optional)
reth-evm = { workspace = true, optional = true }
reth-chainspec = { workspace = true, optional = true }
reth-storage-errors = { workspace = true, optional = true }
reth-execution-types = { workspace = true, optional = true }
reth-execution-errors = { workspace = true, optional = true }
reth-primitives-traits = { workspace = true, optional = true }
base-execution-chainspec = { workspace = true, optional = true }
base-execution-consensus = { workspace = true, optional = true }
base-execution-primitives = { workspace = true, optional = true }
base-alloy-rpc-types-engine = { workspace = true, optional = true }

[dev-dependencies]
rstest.workspace = true
alloy-genesis.workspace = true
alloy-hardforks.workspace = true
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
reth-chainspec = { workspace = true }
reth-evm = { workspace = true, features = ["test-utils"] }
reth-revm = { workspace = true, features = ["test-utils"] }
base-execution-chainspec.workspace = true
base-execution-primitives = { workspace = true, features = ["arbitrary"] }

[features]
default = [ "std" ]
std = [
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-evm/std",
	"alloy-primitives/std",
	"base-alloy-consensus/std",
	"base-alloy-flz/std",
	"base-alloy-rpc-types-engine?/std",
	"base-execution-chainspec?/std",
	"base-execution-consensus?/std",
	"base-execution-primitives?/std",
	"base-revm/std",
	"reth-chainspec?/std",
	"reth-evm?/std",
	"reth-execution-errors?/std",
	"reth-execution-types?/std",
	"reth-primitives-traits?/std",
	"reth-storage-errors?/std",
	"revm/std",
	"thiserror/std",
]
reth = [ "base-alloy-consensus/reth", "base-revm/reth", "std" ]
execution = [
	"base-revm/execution",
	"dep:base-alloy-rpc-types-engine",
	"dep:base-execution-chainspec",
	"dep:base-execution-consensus",
	"dep:base-execution-primitives",
	"dep:reth-chainspec",
	"dep:reth-evm",
	"dep:reth-execution-errors",
	"dep:reth-execution-types",
	"dep:reth-primitives-traits",
	"dep:reth-storage-errors",
	"reth",
	"std",
]
