[package]
name = "base-comp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Derivation channel compression for Base"

[lints]
workspace = true

[dependencies]
thiserror.workspace = true

brotli = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["debug"], optional = true }
alloy-consensus = { workspace = true, features = ["std"], optional = true }
alloy-eips = { workspace = true, features = ["std"], optional = true }
alloy-primitives = { workspace = true, features = ["std"], optional = true }
alloy-signer = { workspace = true, optional = true }
alloy-signer-local = { workspace = true, optional = true }

[dev-dependencies]
base-protocol = { workspace = true, features = ["std"] }
alloy-primitives = { workspace = true, features = ["std"] }
base-common-genesis = { workspace = true, features = ["std"] }
criterion.workspace = true

[[bin]]
name = "base-compression-benchmark"
path = "src/bin/base_compression_benchmark.rs"
required-features = ["benchmark"]

[[bench]]
name = "incompressible_data"
harness = false
required-features = ["benchmark"]

[features]
default = []
benchmark = [
	"dep:alloy-consensus",
	"dep:alloy-eips",
	"dep:alloy-primitives",
	"dep:alloy-signer",
	"dep:alloy-signer-local",
	"std",
]
std = [
	"alloy-consensus?/std",
	"alloy-eips?/std",
	"alloy-primitives?/std",
	"brotli?/std",
	"dep:brotli",
	"dep:derive_more",
	"derive_more?/std",
	"thiserror/std",
]
