[package]
name = "base-comp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Derivation channel compression for Base"

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
miniz_oxide.workspace = true

brotli = { workspace = true, optional = true }

[dev-dependencies]
base-protocol = { workspace = true, features = ["std"] }
alloy-primitives = { workspace = true, features = ["std"] }
base-common-genesis = { workspace = true, features = ["std"] }

[features]
default = []
std = [
	"brotli/std",
	"miniz_oxide/std",
	"thiserror/std",
]
