[package]
name = "base-execution-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
reth-primitives-traits = { workspace = true }
reth-evm = { workspace = true, features = ["default"] }
base-common-chains = { workspace = true, features = ["default"] }
base-common-evm = { workspace = true, features = ["std", "reth"] }
reth-execution-errors = { workspace = true, features = ["default"] }

[dev-dependencies]
alloy-eips = { workspace = true }
base-protocol = { workspace = true }
alloy-hardforks = { workspace = true }
reth-evm = { workspace = true, features = ["default", "test-utils"] }
base-common-consensus = { workspace = true, features = ["arbitrary"] }
reth-revm = { workspace = true, features = ["default", "test-utils"] }
base-execution-chainspec = { workspace = true, features = ["default"] }

[features]
default = ["metrics", "std"]
metrics = ["base-common-evm/metrics", "reth-evm/metrics"]
std = [
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "base-common-chains/std",
    "base-common-consensus/std",
    "base-common-evm/std",
    "base-execution-chainspec/std",
    "reth-evm/std",
    "reth-execution-errors/std",
    "reth-primitives-traits/std",
    "reth-revm/std",
    "thiserror/std",
]
portable = ["base-common-evm/portable", "reth-revm/portable"]
rpc = ["reth-evm/rpc"]
