[package]
name = "base-execution-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
alloy-eips = { workspace = true }
futures-util = { workspace = true }
base-evm-handler = { workspace = true }

base-evm-context = { workspace = true }
reth-storage-api = { workspace = true }
reth-trie-common = { workspace = true }
reth-storage-errors = { workspace = true }
reth-execution-types = { workspace = true }
reth-primitives-traits = { workspace = true }
rayon = { workspace = true, optional = true }
base-execution-chainspec = { workspace = true }
base-execution-consensus = { workspace = true }
metrics = { workspace = true, optional = true }
reth-trie = { workspace = true, optional = true }
base-execution-payload-types = { workspace = true }
reth-metrics = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["full"] }
alloy-eip7928 = { workspace = true, features = ["rlp"] }
fixed-cache = { workspace = true, features = ["alloc"] }
alloy-rpc-types-debug = { workspace = true, optional = true }
base-common-chains = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["reth"] }
base-common-evm = { workspace = true, features = ["std", "reth"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"]}
base-common-rpc-types-engine = { workspace = true, features = ["serde"] }
alloy-rlp = { workspace = true, features = ["core-net"], optional = true }

[dev-dependencies]
reth-trie = { workspace = true }
alloy-eips = { workspace = true }
base-protocol = { workspace = true }
alloy-genesis = { workspace = true }
alloy-hardforks = { workspace = true }
base-common-genesis = { workspace = true }
base-execution-chainspec = { workspace = true, features = ["default"] }
base-common-consensus = { workspace = true, features = ["arbitrary", "serde"] }

[features]
default = ["metrics", "std"]
metrics = ["base-common-evm/metrics", "std", "dep:metrics", "dep:reth-metrics"]
std = [
    "base-common-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "base-common-chains/std",
    "base-common-evm/std",
    "base-execution-chainspec/std",
    "base-evm-handler/std",
    "reth-primitives-traits/std",
    "thiserror/std",
    "base-execution-consensus/std",
    "base-execution-payload-types/std",
    "dep:rayon",
    "base-evm-handler/std",
    "reth-execution-types/std",
    "reth-storage-errors/std",
    "futures-util/std",
    "derive_more/std",
    "reth-storage-api/std",
    "reth-trie-common/std",
    "alloy-eip7928/std",
    "fixed-cache/std",
    "alloy-rlp?/std",
]
portable = ["base-common-evm/portable", "base-evm-handler/portable"]
rpc = ["base-evm-handler/rpc"]
test-utils = [
    "std",
    "reth-primitives-traits/test-utils",
    "reth-trie-common/test-utils",
    "dep:reth-trie",
    "reth-trie?/test-utils",
]
witness = ["dep:reth-trie", "dep:alloy-rlp", "dep:alloy-rpc-types-debug"]
serde = [
    "base-evm-handler/serde",
    "alloy-primitives/serde",
    "base-common-consensus/serde",
    "reth-trie?/serde",
    "reth-primitives-traits/serde",
    "reth-storage-api/serde",
]
gmp = ["base-evm-handler/gmp"]
optional-balance-check = ["base-evm-handler/optional_balance_check"]
optional-block-gas-limit = ["base-evm-handler/optional_block_gas_limit"]
optional-eip3541 = ["base-evm-handler/optional_eip3541"]
optional-eip3607 = ["base-evm-handler/optional_eip3607"]
optional-no-base-fee = ["base-evm-handler/optional_no_base_fee"]
optional-checks = [
    "optional-balance-check",
    "optional-block-gas-limit",
    "optional-eip3541",
    "optional-eip3607",
    "optional-no-base-fee",
]
memory_limit = ["base-evm-handler/memory_limit"]
