[package]
name = "base-prover-service-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
chrono = { workspace = true, features = ["default", "serde"] }
uuid = { workspace = true, features = ["default", "v4", "serde"] }
base-proof-service-protocol = { workspace = true, features = ["default"] }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "uuid", "chrono", "derive", "tls-native-tls"] }
[dev-dependencies]
alloy-primitives = { workspace = true }
base-proof-types-protocol = { workspace = true }
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread"] }
[lints]
workspace = true
