[package]
name = "base-genesis"
description = "Offline, single-chain Base devnet genesis generation"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-common-consensus.workspace = true
base-execution-chainspec.workspace = true
base-common-genesis = { workspace = true, features = ["std", "serde"] }

# execution
alloy-eips.workspace = true
reth-chainspec.workspace = true
alloy-json-abi.workspace = true
revm = { workspace = true, features = ["std"] }
alloy-genesis = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-dyn-abi = { workspace = true, features = ["std", "eip712"] }
alloy-signer-local = { workspace = true, features = ["mnemonic"] }
alloy-primitives = { workspace = true, features = ["std", "serde", "rand"] }

# beacon
ethereum_ssz.workspace = true
eth2_keystore.workspace = true
lighthouse-types.workspace = true
eth2_key_derivation.workspace = true
lighthouse-state-processing.workspace = true
coins-bip39 = { workspace = true, features = ["english"] }
lighthouse-bls = { workspace = true, features = ["supranational-portable"] }

# misc
eyre.workspace = true
rand.workspace = true
sha2.workspace = true
tracing.workspace = true
tempfile.workspace = true
serde_yaml.workspace = true
serde_json = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "env"] }
serde = { workspace = true, features = ["derive", "std"] }
