//! Core storage provider traits for Base native precompiles.
//!
//! Defines [`PrecompileStorageProvider`] (the EVM access boundary),
//! [`StorageOps`] (per-address slot read/write), and [`ContractStorage`]
//! (generated by the `#[contract]` macro).

use alloy_primitives::{Address, B256, LogData, U256, keccak256};
use revm::{
    context::journaled_state::JournalCheckpoint,
    interpreter::gas::{KECCAK256, KECCAK256WORD},
    state::{AccountInfo, Bytecode},
};

use crate::error::{BasePrecompileError, Result};

/// Low-level storage provider for interacting with the EVM.
///
/// Abstracted over both production EVM journal and test `HashMap` backends.
pub trait PrecompileStorageProvider {
    /// Returns the current chain ID.
    fn chain_id(&self) -> u64;
    /// Returns the current block timestamp.
    fn timestamp(&self) -> U256;
    /// Returns the current block beneficiary (coinbase).
    fn beneficiary(&self) -> Address;
    /// Returns the current block number.
    fn block_number(&self) -> u64;

    /// Sets the bytecode at the given address.
    fn set_code(&mut self, address: Address, code: Bytecode) -> Result<()>;

    /// Executes a closure with access to the account info for the given address.
    fn with_account_info(
        &mut self,
        address: Address,
        f: &mut dyn FnMut(&AccountInfo),
    ) -> Result<()>;

    /// Performs an SLOAD operation (persistent storage read).
    fn sload(&mut self, address: Address, key: U256) -> Result<U256>;
    /// Performs a TLOAD operation (transient storage read).
    fn tload(&mut self, address: Address, key: U256) -> Result<U256>;
    /// Performs an SSTORE operation (persistent storage write).
    fn sstore(&mut self, address: Address, key: U256, value: U256) -> Result<()>;
    /// Performs a TSTORE operation (transient storage write).
    fn tstore(&mut self, address: Address, key: U256, value: U256) -> Result<()>;

    /// Emits an event from the given contract address.
    fn emit_event(&mut self, address: Address, event: LogData) -> Result<()>;

    /// Deducts gas from the remaining gas and returns an error if insufficient.
    fn deduct_gas(&mut self, gas: u64) -> Result<()>;
    /// Deducts state-creating gas (EIP-8037 reservoir model).
    ///
    /// Counts only state-creation operations: new account creation and code deposit.
    /// State gas is tracked separately from regular gas and also deducted from the
    /// regular gas counter when no reservoir is available.
    fn deduct_state_gas(&mut self, gas: u64) -> Result<()>;
    /// Adds a gas refund to the refund counter.
    fn refund_gas(&mut self, gas: i64);
    /// Returns the gas limit for this precompile call.
    fn gas_limit(&self) -> u64;
    /// Returns the gas used so far.
    fn gas_used(&self) -> u64;
    /// Returns the state-creating gas spent so far (EIP-8037).
    ///
    /// Counts only new account creation and code deposit operations.
    fn state_gas_used(&self) -> u64;
    /// Returns the gas refunded so far.
    fn gas_refunded(&self) -> i64;
    /// Returns the remaining EIP-8037 state-gas reservoir.
    ///
    /// State gas is first deducted from this reservoir before spilling into regular gas.
    /// Returns zero when no reservoir was provided at construction time.
    fn reservoir(&self) -> u64;

    /// Returns whether the current call context is static.
    fn is_static(&self) -> bool;

    /// Returns the native value (in wei) attached to this precompile call.
    fn call_value(&self) -> U256;

    /// Returns the address that called this precompile.
    fn caller(&self) -> Address;
    /// Replaces the current caller address and returns the previous caller.
    fn replace_caller(&mut self, caller: Address) -> Address;

    /// Creates a new journal checkpoint for atomic state management.
    fn checkpoint(&mut self) -> JournalCheckpoint;
    /// Commits all state changes since the given checkpoint.
    fn checkpoint_commit(&mut self, checkpoint: JournalCheckpoint);
    /// Reverts all state changes back to the given checkpoint.
    fn checkpoint_revert(&mut self, checkpoint: JournalCheckpoint);

    /// Computes keccak256 and charges the appropriate gas.
    fn keccak256(&mut self, data: &[u8]) -> Result<B256> {
        let num_words =
            u64::try_from(data.len().div_ceil(32)).map_err(|_| BasePrecompileError::OutOfGas)?;
        let price = KECCAK256WORD
            .checked_mul(num_words)
            .and_then(|w| w.checked_add(KECCAK256))
            .ok_or(BasePrecompileError::OutOfGas)?;
        self.deduct_gas(price)?;
        Ok(keccak256(data))
    }
}

/// Storage operations for a given (contract) address.
///
/// Abstracts over persistent (SLOAD/SSTORE) and transient (TLOAD/TSTORE) storage.
pub trait StorageOps {
    /// Stores a value at the provided slot.
    fn store(&mut self, slot: U256, value: U256) -> Result<()>;
    /// Loads a value from the provided slot.
    fn load(&self, slot: U256) -> Result<U256>;
}

/// Trait providing access to a contract's address and storage.
///
/// Automatically implemented by the `#[contract]` macro.
pub trait ContractStorage<'a> {
    /// Contract address.
    fn address(&self) -> Address;
    /// Contract storage accessor.
    fn storage(&self) -> crate::storage_ctx::StorageCtx<'a>;

    /// Returns true if the contract has bytecode deployed at its address.
    fn is_initialized(&self) -> Result<bool> {
        self.storage().with_account_info(self.address(), |info| Ok(!info.is_empty_code_hash()))
    }
}

/// Describes how a type is laid out in EVM storage.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Layout {
    /// Single slot, N bytes (1–32). Can be packed with other fields if N < 32.
    Bytes(usize),
    /// Occupies N full slots. Cannot be packed.
    Slots(usize),
}

impl Layout {
    /// Returns true if this field can be packed with adjacent fields.
    pub const fn is_packable(&self) -> bool {
        match self {
            Self::Bytes(n) => *n < 32,
            Self::Slots(_) => false,
        }
    }

    /// Returns the number of storage slots this type occupies.
    pub const fn slots(&self) -> usize {
        match self {
            Self::Bytes(_) => 1,
            Self::Slots(n) => *n,
        }
    }

    /// Returns the number of bytes this type occupies.
    pub const fn bytes(&self) -> usize {
        match self {
            Self::Bytes(n) => *n,
            Self::Slots(n) => {
                let (mut i, mut result) = (0, 0);
                while i < *n {
                    result += 32;
                    i += 1;
                }
                result
            }
        }
    }
}

/// Describes the context in which a storable value is being loaded or stored.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct LayoutCtx(usize);

impl LayoutCtx {
    /// Load/store the entire value at a given slot.
    pub const FULL: Self = Self(usize::MAX);

    /// Load/store a packed primitive at the given byte offset within a slot.
    pub const fn packed(offset: usize) -> Self {
        debug_assert!(offset < 32);
        Self(offset)
    }

    #[inline]
    /// Returns the packed offset, or `None` for [`Self::FULL`].
    pub const fn packed_offset(&self) -> Option<usize> {
        if self.0 == usize::MAX { None } else { Some(self.0) }
    }
}

/// Compile-time layout information and handler factory for storable types.
pub trait StorableType {
    /// Storage layout descriptor.
    const LAYOUT: Layout;
    /// Whether this type declares its own ERC-7201 storage namespace.
    const HAS_STORAGE_NAMESPACE: bool = false;
    /// ERC-7201 namespace identifier for this type.
    const STORAGE_NAMESPACE_ID: &'static str = "";
    /// ERC-7201 namespace root slot for this type.
    const STORAGE_NAMESPACE_ROOT: U256 = U256::ZERO;
    /// Number of storage slots this type occupies.
    const SLOTS: usize = Self::LAYOUT.slots();
    /// Number of bytes this type occupies.
    const BYTES: usize = Self::LAYOUT.bytes();
    /// Whether this type can be packed with adjacent fields.
    const IS_PACKABLE: bool = Self::LAYOUT.is_packable();
    /// Whether this type stores data outside its base slot (e.g., `String`, `Vec`).
    const IS_DYNAMIC: bool = false;

    /// The handler type that provides storage access for this type.
    type Handler<'a>;

    /// Creates a handler for this type at the given storage location.
    fn handle<'a>(
        slot: U256,
        ctx: LayoutCtx,
        address: Address,
        storage: crate::storage_ctx::StorageCtx<'a>,
    ) -> Self::Handler<'a>;
}

/// Handler trait for read/write/delete operations on a storable value.
pub trait Handler<T: Storable> {
    /// Reads the value from persistent storage.
    fn read(&self) -> Result<T>;
    /// Writes the value to persistent storage.
    fn write(&mut self, value: T) -> Result<()>;
    /// Deletes the value from persistent storage (sets to zero).
    fn delete(&mut self) -> Result<()>;
    /// Reads the value from transient storage.
    fn t_read(&self) -> Result<T>;
    /// Writes the value to transient storage.
    fn t_write(&mut self, value: T) -> Result<()>;
    /// Deletes the value from transient storage.
    fn t_delete(&mut self) -> Result<()>;
}

/// Storage I/O operations for storable types.
pub trait Storable: StorableType + Sized {
    /// Load this type from storage at the given slot.
    fn load<S: StorageOps>(storage: &S, slot: U256, ctx: LayoutCtx) -> Result<Self>;
    /// Store this type to storage at the given slot.
    fn store<S: StorageOps>(&self, storage: &mut S, slot: U256, ctx: LayoutCtx) -> Result<()>;

    /// Delete this type from storage (set to zero).
    fn delete<S: StorageOps>(storage: &mut S, slot: U256, ctx: LayoutCtx) -> Result<()> {
        match ctx.packed_offset() {
            None => {
                for offset in 0..Self::SLOTS {
                    storage.store(slot + U256::from(offset), U256::ZERO)?;
                }
                Ok(())
            }
            Some(offset) => {
                let bytes = Self::BYTES;
                let current = storage.load(slot)?;
                let cleared = crate::packing::delete_from_word(current, offset, bytes)?;
                storage.store(slot, cleared)
            }
        }
    }
}

/// Sealed marker for primitive types that can be packed into EVM storage slots.
pub mod sealed {
    /// Marker trait limiting [`Packable`](super::Packable) to primitive types.
    pub trait OnlyPrimitives {}
}

/// Trait for types that can be packed into EVM storage slots.
pub trait Packable: FromWord + StorableType {}

/// Word-level encoding for primitive types that fit in a single EVM storage slot.
pub trait FromWord: sealed::OnlyPrimitives {
    /// Encodes this value to a right-aligned `U256` word.
    fn to_word(&self) -> U256;
    /// Decodes a value from a right-aligned `U256` word.
    fn from_word(word: U256) -> Result<Self>
    where
        Self: Sized;
}

/// Blanket `Storable` implementation for all `Packable` types.
impl<T: Packable> Storable for T {
    #[inline]
    fn load<S: StorageOps>(storage: &S, slot: U256, ctx: LayoutCtx) -> Result<Self> {
        const { assert!(T::IS_PACKABLE, "Packable requires IS_PACKABLE to be true") };
        match ctx.packed_offset() {
            None => storage.load(slot).and_then(Self::from_word),
            Some(offset) => {
                let slot_value = storage.load(slot)?;
                crate::packing::extract_from_word(slot_value, offset, Self::BYTES)
            }
        }
    }

    #[inline]
    fn store<S: StorageOps>(&self, storage: &mut S, slot: U256, ctx: LayoutCtx) -> Result<()> {
        const { assert!(T::IS_PACKABLE, "Packable requires IS_PACKABLE to be true") };
        match ctx.packed_offset() {
            None => storage.store(slot, self.to_word()),
            Some(offset) => {
                let current = storage.load(slot)?;
                let updated = crate::packing::insert_into_word(current, self, offset, Self::BYTES)?;
                storage.store(slot, updated)
            }
        }
    }
}

/// Trait for types that can be used as storage mapping keys.
pub trait StorageKey: sealed::OnlyPrimitives {
    /// Returns key bytes for storage slot computation (left-padded to 32 bytes).
    fn as_storage_bytes(&self) -> impl AsRef<[u8]>;

    /// Computes `keccak256(lpad32(key) ‖ slot_be32)`.
    ///
    /// The formula is Solidity-compatible for unsigned integers (`u8`..`u256`), `Address`,
    /// `FixedBytes<32>`, and `String`. Signed integers and `FixedBytes<N>` for `N < 32`
    /// intentionally diverge from Solidity's `abi.encode(key, slot)` encoding: signed integers
    /// use raw signed bytes and short `FixedBytes<N>` keys are left-padded from their slice
    /// rather than right-padded as Solidity would. Off-chain tools reconstructing mapping slots
    /// for those key types must use this crate's encoding, not Solidity's.
    ///
    /// See the crate-level README for a full compatibility table.
    fn mapping_slot(&self, slot: U256) -> U256 {
        let key_bytes = self.as_storage_bytes();
        let key_bytes = key_bytes.as_ref();
        debug_assert!(key_bytes.len() <= 32);

        let mut buf = [0u8; 64];
        buf[32 - key_bytes.len()..32].copy_from_slice(key_bytes);
        buf[32..].copy_from_slice(&slot.to_be_bytes::<32>());

        U256::from_be_bytes(keccak256(buf).0)
    }
}
