[package]
name = "base-consensus-engine"
description = "An implementation of the Base engine client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-transport = { workspace = true }
alloy-primitives = { workspace = true }
reth-engine-primitives = { workspace = true }
reth-primitives-traits = { workspace = true }
base-common-chain-config = { workspace = true }
metrics = { workspace = true, optional = true }
serde = { workspace = true, features = ["std"] }
base-execution-state-tasks = { workspace = true }
tracing = { workspace = true, features = ["std"] }
base-execution-network-service = {workspace = true}
base-execution-state-provider = { workspace = true }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["std"] }
base-execution-payload-builder = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
base-consensus-source-providers = { workspace = true }
base-common-observability-metrics = { workspace = true }
base-common-types-chain = { workspace = true, features = ["std"] }
base-common-types-rpc = {workspace = true, features = ["default", "std"]}
base-common-types-payload = {workspace = true, features = ["serde", "std"]}
base-consensus-batch-types = { workspace = true, features = ["serde", "std"] }
derive_more = { workspace = true, features = ["display", "deref", "from_str", "constructor"] }
base-common-client-ethereum = {workspace = true, features = ["default", "reqwest", "reqwest-rustls-tls"]}

[dev-dependencies]
arbitrary = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
rstest = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default", "thread_rng"] }
base-common-chain-config = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, features = ["default", "arbitrary", "k256"] }

[features]
metrics = ["base-consensus-source-providers/metrics", "base-common-observability-metrics/metrics", "dep:metrics"]
test-utils = ["base-common-chain-config/test-utils", "base-consensus-batch-types/test-utils"]
