[package]
name = "base-consensus-engine"
description = "An implementation of the Base engine client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
reth-network = { workspace = true }
base-metrics = { workspace = true }
reth-provider = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-transport = { workspace = true }
reth-network-api = { workspace = true }
alloy-primitives = { workspace = true }
base-execution-trie = { workspace = true }
base-common-genesis = { workspace = true }
base-common-network = { workspace = true }
reth-primitives-traits = { workspace = true }
reth-engine-primitives = { workspace = true }
base-consensus-providers = { workspace = true }
metrics = { workspace = true, optional = true }
serde = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["default"] }
base-execution-payload-builder = { workspace = true }
alloy-eips = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
base-common-consensus = { workspace = true, features = ["std"] }
base-protocol = { workspace = true, features = ["serde", "std"] }
base-common-rpc-types = {workspace = true, features = ["default", "std"]}
base-common-rpc-types-engine = {workspace = true, features = ["serde", "std"]}
derive_more = { workspace = true, features = ["display", "deref", "from_str", "constructor"] }
alloy-provider = { workspace = true, features = ["default", "reqwest", "reqwest-rustls-tls"] }
[dev-dependencies]
arbitrary = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
rstest = { workspace = true, features = ["default"] }
base-common-chains = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default", "thread_rng"] }
base-common-rpc-types = { workspace = true, features = ["default", "arbitrary", "k256"] }

[features]
metrics = [
	"base-consensus-providers/metrics",
	"base-metrics/metrics",
	"dep:metrics",
]
test-utils = [ "base-common-genesis/test-utils", "base-protocol/test-utils" ]
