[package]
name = "base-execution-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "EVM chain spec implementation for Base."

[lints]
workspace = true

[dependencies]
auto_impl = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
alloy-trie = { workspace = true }
serde_json = { workspace = true }
alloy-chains = { workspace = true }
alloy-eip2124 = { workspace = true }
alloy-genesis = { workspace = true }
base-protocol = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true }
serde = { workspace = true, optional = true }
base-common-types-chain = { workspace = true }
reth-network-peers = { workspace = true, features = ["default"] }
base-common-types-rpc = { workspace = true, features = ["default"] }
base-common-chain-config = {workspace = true, features = ["default", "std"]}

[features]
default = [ "std" ]
std = [
    "alloy-chains/std",
    "base-common-types-chain/std",
    "alloy-eips/std",
    "alloy-genesis/std",
    "alloy-primitives/std",
    "base-common-chain-config/std",
    "base-common-types-rpc/std",
    "base-protocol/std",
    "reth-network-peers/std",
    "serde?/std",
    "serde_json/std",
    "thiserror/std",
]
serde = [
    "alloy-chains/serde",
    "base-common-types-chain/serde",
    "alloy-eips/serde",
    "alloy-hardforks/serde",
    "alloy-primitives/serde",
    "base-common-chain-config/serde",
    "base-common-types-rpc/serde",
    "base-protocol/serde",
]
