[package]
name = "base-builder-core"
description = "Block builder for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
revm = { workspace = true }
tower = { workspace = true }
either = { workspace = true }
dashmap = { workspace = true }
reth-cli = { workspace = true }
alloy-evm = { workspace = true }
reth-trie = { workspace = true }
jsonrpsee = { workspace = true }
dirs-next = { workspace = true }
reth-tasks = { workspace = true }
async-trait = { workspace = true }
base-metrics = { workspace = true }
base-bundles = { workspace = true }
reth-rpc-api = { workspace = true }
alloy-signer = { workspace = true }
reth-provider = { workspace = true }
reth-node-api = { workspace = true }
reth-cli-util = { workspace = true }
alloy-network = { workspace = true }
reth-rpc-layer = { workspace = true }
alloy-contract = { workspace = true }
alloy-json-rpc = { workspace = true }
base-common-flz = { workspace = true }
alloy-transport = { workspace = true }
jsonrpsee-types = { workspace = true }
alloy-primitives = { workspace = true }
base-node-runner = { workspace = true }
reth-chain-state = { workspace = true }
reth-payload-util = { workspace = true }
reth-cli-commands = { workspace = true }
reth-rpc-eth-types = { workspace = true }
alloy-signer-local = { workspace = true }
reth-rpc-engine-api = { workspace = true }
base-common-network = { workspace = true }
reth-payload-builder = { workspace = true }
reth-execution-cache = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-eip8130 = { workspace = true }
alloy-rpc-types-beacon = { workspace = true }
rlimit = { workspace = true, optional = true }
nanoid = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }
base-observability-events = { workspace = true }
serde = { workspace = true, features = ["std"] }
reth-ipc = { workspace = true, optional = true }
reth-basic-payload-builder = { workspace = true }
tracing = { workspace = true, features = ["std"] }
url = { workspace = true, features = ["default"] }
hex = { workspace = true, features = ["default"] }
base-common-rpc-types-engine = { workspace = true }
clap = { workspace = true, features = ["default"] }
k256 = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default"] }
sha3 = { workspace = true, features = ["default"] }
time = { workspace = true, features = ["default"] }
http = { workspace = true, features = ["default"] }
eyre = { workspace = true, features = ["default"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["default"] }
alloy-serde = { workspace = true, features = ["std"] }
testcontainers = { workspace = true, optional = true }
reth-db = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
reth-payload-builder-primitives = { workspace = true }
reth-evm = { workspace = true, features = ["default"] }
derive_more = { workspace = true, features = ["debug"] }
reth-revm = { workspace = true, features = ["default"] }
secp256k1 = { workspace = true, features = ["default"] }
tokio-util = { workspace = true, features = ["default"] }
serde_with = { workspace = true, features = ["default"] }
alloy-consensus = { workspace = true, features = ["std"] }
base-common-evm = { workspace = true, features = ["std"] }
parking_lot = { workspace = true, features = ["default"] }
reth-node-core = { workspace = true, features = ["otlp"] }
clap_builder = { workspace = true, features = ["default"] }
base-node-core = { workspace = true, features = ["default"] }
reth-chainspec = { workspace = true, features = ["default"] }
alloy-provider = { workspace = true, features = ["default"] }
jsonrpsee-core = { workspace = true, features = ["default"] }
alloy-rpc-types-eth = { workspace = true, features = ["std"] }
reth-storage-api = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
reth-node-builder = { workspace = true, features = ["default"] }
reth-tracing-otlp = { workspace = true, features = ["default"] }
tokio-tungstenite = { workspace = true, features = ["default"] }
alloy-rpc-types-engine = { workspace = true, features = ["std"] }
base-common-consensus = { workspace = true, features = ["reth"] }
reth-network-peers = { workspace = true, features = ["default"] }
base-execution-evm = { workspace = true, features = ["default"] }
reth-node-ethereum = { workspace = true, features = ["default"] }
base-common-chains = { workspace = true, features = ["default"] }
alloy-sol-types = { workspace = true, features = ["json", "std"] }
reth-execution-types = { workspace = true, features = ["default"] }
alloy-transport-http = { workspace = true, features = ["default"] }
tar = { workspace = true, optional = true, features = ["default"] }
base-execution-txpool = { workspace = true, features = ["default"] }
base-common-rpc-types = { workspace = true, features = ["default"] }
ctor = { workspace = true, optional = true, features = ["default"] }
hyper = { workspace = true, optional = true, features = ["default"] }
reth-payload-primitives = { workspace = true, features = ["default"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
base-execution-consensus = { workspace = true, features = ["default"] }
uuid = { workspace = true, features = ["default", "serde", "v5", "v4"] }
hyper-util = { workspace = true, optional = true, features = ["default"] }
base-execution-rpc = { workspace = true, features = ["default", "client"] }
base-execution-payload-builder = { workspace = true, features = ["default"] }
opentelemetry = { workspace = true, optional = true, features = ["default"] }
http-body-util = { workspace = true, optional = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = ["default", "env-filter", "json"] }
[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { workspace = true, optional = true, features = ["default"] }
[dev-dependencies]
rlimit = { workspace = true }
nanoid = { workspace = true }
reth-ipc = { workspace = true }
base-test-utils = { workspace = true }
base-txpool-rpc = { workspace = true }
reth-testing-utils = { workspace = true }
base-execution-trie = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
ctor = { workspace = true, features = ["default"] }
hyper = { workspace = true, features = ["default"] }
rstest = { workspace = true, features = ["default"] }
tempfile = { workspace = true, features = ["default"] }
hyper-util = { workspace = true, features = ["default"] }
http-body-util = { workspace = true, features = ["default"] }
reth-trie-common = { workspace = true, features = ["default"] }
criterion = { workspace = true, features = ["default", "html_reports"] }
alloy-provider = { workspace = true, features = ["default", "txpool-api"] }
base-builder-core = { workspace = true, features = ["default", "test-utils"] }
reth-node-builder = { workspace = true, features = ["default", "test-utils"] }
[features]
default = [ "jemalloc", "metrics" ]
metrics = [
	"base-common-evm/metrics",
	"base-execution-payload-builder/metrics",
	"base-metrics/metrics",
	"base-observability-events/metrics",
	"dep:metrics",
	"reth-evm/metrics",
	"reth-trie/metrics",
]
jemalloc = [ "dep:tikv-jemallocator", "reth-cli-util/jemalloc" ]
jemalloc-prof = [
	"jemalloc",
	"reth-cli-util/jemalloc-prof",
	"tikv-jemallocator?/profiling",
]
min-error-logs = [ "tracing/release_max_level_error" ]
min-warn-logs = [ "tracing/release_max_level_warn" ]
min-info-logs = [ "tracing/release_max_level_info" ]
min-debug-logs = [ "tracing/release_max_level_debug" ]
min-trace-logs = [ "tracing/release_max_level_trace" ]
test-utils = [
	"base-bundles/test-utils",
	"base-common-chains/test-utils",
	"base-execution-eip8130/test-utils",
	"base-execution-rpc/client",
	"base-node-core/test-utils",
	"base-node-runner/test-utils",
	"base-observability-events/test-utils",
	"ctor",
	"http-body-util",
	"hyper",
	"hyper-util",
	"nanoid",
	"reth-chain-state/test-utils",
	"reth-chainspec/test-utils",
	"reth-db/test-utils",
	"reth-evm/test-utils",
	"reth-execution-cache/test-utils",
	"reth-ipc",
	"reth-node-builder/test-utils",
	"reth-node-ethereum/test-utils",
	"reth-payload-builder/test-utils",
	"reth-primitives-traits/test-utils",
	"reth-provider/test-utils",
	"reth-revm/test-utils",
	"reth-tasks/test-utils",
	"reth-transaction-pool/test-utils",
	"reth-trie/test-utils",
	"rlimit",
	"testcontainers",
]
