[package]
name = "base-builder-core"
description = "Block builder for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tower = { workspace = true }
either = { workspace = true }
dashmap = { workspace = true }
dirs-next = { workspace = true }
jsonrpsee = { workspace = true }
reth-trie = { workspace = true }
async-trait = { workspace = true }
alloy-signer = { workspace = true }
reth-cli-util = { workspace = true }
reth-provider = { workspace = true }
alloy-contract = { workspace = true }
alloy-json-rpc = { workspace = true }
base-cli-utils = { workspace = true }
reth-rpc-layer = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-transport = { workspace = true }
base-txpool-rpc = { workspace = true }
jsonrpsee-types = { workspace = true }
alloy-primitives = { workspace = true }
reth-chain-state = { workspace = true }
base-node-context = { workspace = true }
reth-cli-commands = { workspace = true }
reth-payload-util = { workspace = true }
reth-rpc-eth-types = { workspace = true }
base-common-network = { workspace = true }
reth-execution-cache = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-evm-fees = { workspace = true }
nanoid = { workspace = true, optional = true }
rlimit = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }
base-common-runtime-tasks = { workspace = true }
serde = { workspace = true, features = ["std"] }
hex = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["std"] }
url = { workspace = true, features = ["default"] }
clap = { workspace = true, features = ["default"] }
eyre = { workspace = true, features = ["default"] }
http = { workspace = true, features = ["default"] }
k256 = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default"] }
sha3 = { workspace = true, features = ["default"] }
time = { workspace = true, features = ["default"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }
alloy-serde = { workspace = true, features = ["std"] }
futures = { workspace = true, features = ["default"] }
reth-db = { workspace = true, features = ["default"] }
testcontainers = { workspace = true, optional = true }
base-common-observability-events = { workspace = true }
base-common-observability-metrics = { workspace = true }
base-node-runner = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["debug"] }
secp256k1 = { workspace = true, features = ["default"] }
serde_with = { workspace = true, features = ["default"] }
tokio-util = { workspace = true, features = ["default"] }
parking_lot = { workspace = true, features = ["default"] }
reth-node-core = { workspace = true, features = ["otlp"] }
clap_builder = { workspace = true, features = ["default"] }
base-common-client-ethereum = { workspace = true, features = ["default"] }
base-node-core = { workspace = true, features = ["default"] }
jsonrpsee-core = { workspace = true, features = ["default"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
tokio-tungstenite = { workspace = true, features = ["default"] }
reth-network-peers = { workspace = true, features = ["default"] }
alloy-sol-types = { workspace = true, features = ["json", "std"] }
base-common-types-payload = {workspace = true, features = ["std"]}
alloy-transport-http = { workspace = true, features = ["default"] }
base-execution-evm-runtime = {features = ["std"], workspace = true}
tar = { workspace = true, optional = true, features = ["default"] }
base-execution-txpool = { workspace = true, features = ["default"] }
ctor = { workspace = true, optional = true, features = ["default"] }
hyper = { workspace = true, optional = true, features = ["default"] }
base-execution-state-api = { workspace = true, features = ["default"] }
base-execution-evm-precompiles = { workspace = true, features = ["std"]}
uuid = { workspace = true, features = ["default", "serde", "v5", "v4"] }
base-common-types-rpc = {workspace = true, features = ["default", "std"]}
base-execution-payload-types = {features = ["default"], workspace = true}
base-execution-state-types = { workspace = true, features = ["default"] }
base-common-types-chain = { workspace = true, features = ["reth", "std"] }
hyper-util = { workspace = true, optional = true, features = ["default"] }
base-execution-rpc = { workspace = true, features = ["default", "client"] }
base-common-chain-config = {features = ["default", "std"], workspace = true}
base-common-observability-tracing = { workspace = true, features = ["otlp"] }
base-execution-evm-blocks = {features = ["default", "std"], workspace = true}
base-execution-payload-builder = { workspace = true, features = ["default"] }
opentelemetry = { workspace = true, optional = true, features = ["default"] }
http-body-util = { workspace = true, optional = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = ["default", "env-filter", "json"] }

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { workspace = true, optional = true, features = ["default"] }

[dev-dependencies]
nanoid = { workspace = true }
rlimit = { workspace = true }
base-txpool-rpc = { workspace = true }
reth-testing-utils = { workspace = true }
base-execution-trie = { workspace = true }
base-testing-support = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
ctor = { workspace = true, features = ["default"] }
hyper = { workspace = true, features = ["default"] }
rstest = { workspace = true, features = ["default"] }
tempfile = { workspace = true, features = ["default"] }
hyper-util = { workspace = true, features = ["default"] }
http-body-util = { workspace = true, features = ["default"] }
criterion = { workspace = true, features = ["default", "html_reports"] }
base-execution-state-types = { workspace = true, features = ["default"] }
base-common-client-ethereum = { workspace = true, features = ["default", "txpool-api"] }
base-node-core = { workspace = true, features = ["default", "test-utils"] }
base-builder-core = { workspace = true, features = ["default", "test-utils"] }

[features]
default = ["jemalloc", "metrics"]
metrics = [
    "base-txpool-rpc/metrics",
    "base-execution-evm-runtime/metrics",
    "base-execution-payload-builder/metrics",
    "base-common-observability-metrics/metrics",
    "base-common-observability-events/metrics",
    "dep:metrics",
    "base-execution-evm-blocks/metrics",
    "reth-trie/metrics",
]
jemalloc = ["dep:tikv-jemallocator", "reth-cli-util/jemalloc"]
jemalloc-prof = ["jemalloc", "reth-cli-util/jemalloc-prof", "tikv-jemallocator?/profiling"]
min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]
test-utils = [
    "base-execution-payload-types/test-utils",
    "base-common-chain-config/test-utils",
    "base-execution-evm-precompiles/test-utils",
    "base-execution-rpc/client",
    "base-node-core/test-utils",
    "base-node-runner/test-utils",
    "base-common-observability-events/test-utils",
    "ctor",
    "http-body-util",
    "hyper",
    "hyper-util",
    "nanoid",
    "reth-chain-state/test-utils",
    "reth-db/test-utils",
    "base-execution-evm-blocks/test-utils",
    "reth-execution-cache/test-utils",
    "base-execution-payload-builder/test-utils",
    "reth-primitives-traits/test-utils",
    "reth-provider/test-utils",
    "base-common-runtime-tasks/test-utils",
    "base-execution-txpool/test-utils",
    "reth-trie/test-utils",
    "rlimit",
    "testcontainers",
]
