payloads:
  - name: "Load Test"
    type: load-test
    id: load-test
    sender_count: 10
    transactions:
      - weight: 70
        type: transfer
      - weight: 20
        type: calldata
        max_size: 256
      - weight: 10
        type: precompile
        target: sha256

benchmarks:
  - variables:
      - type: payload
        value: load-test
      - type: node_type
        value: builder
      - type: validator_node_type
        value: base-reth-node
      - type: num_blocks
        value: 10
      - type: gas_limit
        value: 1000000000
