[package]
name = "base-builder-cli"
description = "Base Builder CLI arguments"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
base-common-observability-events = { workspace = true }
eyre = { workspace = true, features = ["default"] }
base-node-core = { workspace = true, features = ["default"] }
base-builder-core = { workspace = true, features = ["default"] }
base-execution-cli = { workspace = true, features = ["default"] }
clap = { workspace = true, features = ["default", "derive", "env"] }

[dev-dependencies]
alloy-primitives = { workspace = true }
base-execution-payload-types = { workspace = true }
rstest = { workspace = true, features = ["default"] }
