//! Protobuf code generation for the transaction ingress protocol.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    let mut prost_config = prost_build::Config::new();
    prost_config.protoc_executable(protoc);

    tonic_prost_build::configure()
        .server_mod_attribute(
            ".",
            "#[expect(clippy::clone_on_ref_ptr, clippy::doc_markdown, \
             clippy::missing_const_for_fn, reason = \"generated by tonic-prost-build\")]",
        )
        .compile_with_config(
            prost_config,
            &["proto/base/tx_ingress/v1/transaction_ingress.proto"],
            &["proto"],
        )?;
    println!("cargo:rerun-if-changed=proto/base/tx_ingress/v1/transaction_ingress.proto");
    Ok(())
}
