[package]
name = "base-state"
description = "Shared Base storage and execution state interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
]

[dependencies]
alloy-eips = { workspace = true, optional = true }
alloy-provider = { workspace = true, optional = true }
alloy-transport = { workspace = true, optional = true }

either = { workspace = true }
thiserror = { workspace = true }
auto_impl = { workspace = true }
alloy-trie = { workspace = true }
revm-state = { workspace = true }
alloy-genesis = { workspace = true }
revm-bytecode = { workspace = true }
revm-primitives = { workspace = true }
alloy-primitives = { workspace = true }
bytes = { workspace = true, optional = true }
modular-bitfield = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["deref", "debug"] }
base-common-types-chain = { workspace = true, features = ["alloy"]}
arbitrary = { workspace = true, optional = true, features = ["derive"]}
serde = { workspace = true, optional = true, features = ["derive", "rc"] }
tokio = { workspace = true, optional = true, features = ["default", "rt-multi-thread", "macros"] }

[dev-dependencies]
serde_json = { workspace = true, features = ["alloc"] }

mockall = { workspace = true }
proptest = { workspace = true }
proptest-arbitrary-interop = { workspace = true }
serde = { workspace = true, features = ["derive"]}
arbitrary = { workspace = true, features = ["derive"]}

[lints]
workspace = true

[features]
asyncdb = ["dep:tokio", "tokio/rt-multi-thread"]
default = ["std"]
serde = [
    "dep:serde",
    "revm-primitives/serde",
    "revm-state/serde",
    "either/serde",
    "alloy-primitives/serde",
    "revm-bytecode/serde",
    "alloy-eips?/serde",
]
std = [
    "serde?/std",
    "revm-primitives/std",
    "revm-state/std",
    "either/std",
    "thiserror/std",
    "base-common-types-chain/std",
    "alloy-genesis/std",
    "alloy-primitives/std",
    "alloy-trie/std",
    "revm-bytecode/std",
    "derive_more/std",
    "alloy-eips?/std",
    "serde_json/std",
]
arbitrary = ["dep:arbitrary", "alloy-primitives/arbitrary"]
reth-codec = ["dep:bytes", "dep:modular-bitfield"]
test-utils = ["arbitrary", "base-common-types-chain/test-utils"]
alloydb = ["std", "asyncdb", "dep:tokio", "dep:alloy-provider", "dep:alloy-eips", "dep:alloy-transport"]
map-foldhash = ["revm-primitives/map-foldhash", "revm-state/map-foldhash"]
