[package]
name = "base-common-cli-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
url = { workspace = true }
cfg-if = { workspace = true }
metrics = { workspace = true }
dirs-next = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
alloy-genesis = { workspace = true }
tracing-appender = { workspace = true }
opentelemetry_sdk = { workspace = true }
base-common-io-files = { workspace = true }
base-common-runtime-tasks = { workspace = true }
eyre = {features = ["default"], workspace = true}
rand_08 = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["alloc"] }
serde = {features = ["derive", "std"], workspace = true}
tokio-util = { workspace = true, features = ["default"] }
opentelemetry = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["std", "attributes"] }
metrics-process = { workspace = true, features = ["metrics-rs"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"] }
clap = {features = ["default", "derive", "env", "string"], workspace = true}
base-common-observability-metrics = { workspace = true, features = ["metrics"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }
secp256k1 = { workspace = true, features = ["global-context", "recovery", "rand"] }
tracy-client = { workspace = true, features = ["default", "demangle"], optional = true }
base-common-observability-tracing = {features = ["default", "otlp", "std"],  workspace = true}
tokio = { workspace = true, features = ["default", "full", "macros", "rt-multi-thread", "signal"] }
tracing-subscriber = { workspace = true, features = ["default", "fmt", "env-filter", "json", "tracing-log"] }

[dev-dependencies]
rand = { workspace = true, features = ["default"] }
rstest = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }

[target.'cfg(unix)'.dependencies]
libc = {features = ["default"], workspace = true}
tikv-jemalloc-sys = { workspace = true, optional = true, features = ["default"] }
tikv-jemallocator = { workspace = true, optional = true, features = ["default"] }
snmalloc-rs = { workspace = true, features = ["default", "build_cc"], optional = true }
backtrace = { workspace = true, features = ["default"] }

[features]
jemalloc = ["dep:tikv-jemallocator", "dep:tikv-jemalloc-sys", "tikv-jemallocator?/override_allocator_on_supported_platforms"]

# Enables jemalloc profiling features
jemalloc-prof = ["jemalloc", "tikv-jemallocator?/profiling"]

# Wraps the selected allocator in the tracy profiling allocator
tracy-allocator = ["dep:tracy-client"]

snmalloc = ["dep:snmalloc-rs"]

# Enables the snmalloc-rs `native-cpu` feature, which optimizes snmalloc for the
# native CPU of the host machine. Not sure why this feature is not derived from
# RUSTFLAGS or enabled when `target-cpu=native`.
snmalloc-native = ["snmalloc", "snmalloc-rs/native-cpu"]
otlp = ["base-common-observability-tracing/otlp"]
otlp-logs = ["base-common-observability-tracing/otlp-logs"]
