//! Pending proof state machine and collection.
//!
//! [`PendingProofs`] tracks in-flight proof sessions keyed by dispute-game
//! address. Each entry moves through a [`ProofPhase`] lifecycle:
//! `AwaitingProof` → `ReadyToSubmit` (on success) or `NeedsRetry` (on failure).
//!
//! Each entry also carries a [`DisputeIntent`] that determines whether the
//! completed proof will be submitted via `challenge()` or `nullify()` on-chain.

use std::{
    collections::HashMap,
    time::{Duration, Instant},
};

use alloy_primitives::{Address, B256, Bytes};
use base_prover_service_client::ProofRequesterProvider;
use base_prover_service_protocol::{GetProofRequest, ProofStatus, SnarkGroth16ProofRequest};
use tracing::warn;

use crate::ChallengerProofAdapter;

/// The kind of proof being generated.
#[derive(Debug, Clone)]
pub enum ProofKind {
    /// A TEE (Trusted Execution Environment) attestation proof.
    ///
    /// Carries an optional pre-built ZK fallback request and intent so the
    /// driver can initiate a ZK proof if the TEE transaction submission fails
    /// on-chain. The fallback is `None` when building the ZK request failed
    /// (e.g. `checkpoint_start_block` error); in that case the driver drops
    /// the entry on TEE submission failure instead of falling back.
    Tee {
        /// Pre-built ZK request for fallback if TEE submission fails.
        /// `None` when the fallback request could not be constructed.
        zk_fallback_request: Option<SnarkGroth16ProofRequest>,
        /// The dispute intent to use for the ZK fallback path.
        /// `None` when the fallback request could not be constructed.
        zk_fallback_intent: Option<DisputeIntent>,
    },
    /// A ZK (zero-knowledge) proof generated by the ZK proving service.
    ///
    /// Carries the original request parameters so the driver can re-initiate
    /// `proveBlockRange` on failure.
    Zk {
        /// Original request parameters for retry.
        prove_request: SnarkGroth16ProofRequest,
    },
}

impl ProofKind {
    /// Returns `true` if this is a TEE proof.
    pub const fn is_tee(&self) -> bool {
        matches!(self, Self::Tee { .. })
    }
}

/// The intended on-chain action for a completed proof.
///
/// A TEE proof always targets `nullify()`. A ZK proof may target either
/// `challenge()` (Path 1: challenging a wrong TEE proposal) or `nullify()`
/// (Path 2: nullifying a fraudulent ZK challenge, Path 3: nullifying a
/// wrong ZK proposal).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DisputeIntent {
    /// Submit via `challenge()` — challenges a TEE proof with a competing ZK proof.
    Challenge,
    /// Submit via `nullify()` — nullifies an existing proof.
    Nullify,
}

/// Phase of a pending proof: awaiting prover service, ready for on-chain
/// submission, or waiting for a retry after failure.
#[derive(Debug, Clone)]
pub enum ProofPhase {
    /// Waiting for the ZK proof service to complete.
    AwaitingProof {
        /// Session ID returned by the ZK proof service.
        session_id: String,
        /// Wall-clock time at which the proof request was initiated.
        started_at: Instant,
    },
    /// Proof obtained — proof bytes are ready for dispute submission.
    ReadyToSubmit {
        /// Type-prefixed proof bytes.
        proof_bytes: Bytes,
    },
    /// Proof job failed — the driver should re-initiate `proveBlockRange`.
    NeedsRetry,
}

/// State for an in-flight proof session.
#[derive(Debug, Clone)]
pub struct PendingProof {
    /// Current phase of this proof lifecycle.
    pub phase: ProofPhase,
    /// The kind of proof (TEE or ZK). For ZK proofs this also carries the
    /// original request parameters needed for retry.
    pub kind: ProofKind,
    /// The index of the invalid intermediate root.
    pub invalid_index: u64,
    /// The expected correct root at that index.
    pub expected_root: B256,
    /// Number of times this proof has been retried after failure.
    pub retry_count: u32,
    /// The intended on-chain dispute action once the proof is ready.
    pub intent: DisputeIntent,
}

impl PendingProof {
    /// Creates a new `PendingProof` in the `AwaitingProof` phase.
    pub fn awaiting(
        session_id: String,
        invalid_index: u64,
        expected_root: B256,
        prove_request: SnarkGroth16ProofRequest,
        intent: DisputeIntent,
    ) -> Self {
        Self {
            phase: ProofPhase::AwaitingProof { session_id, started_at: Instant::now() },
            kind: ProofKind::Zk { prove_request },
            invalid_index,
            expected_root,
            retry_count: 0,
            intent,
        }
    }

    /// Creates a new TEE `PendingProof` in the `AwaitingProof` phase.
    pub fn awaiting_tee(
        session_id: String,
        invalid_index: u64,
        expected_root: B256,
        zk_fallback_request: Option<SnarkGroth16ProofRequest>,
        zk_fallback_intent: Option<DisputeIntent>,
    ) -> Self {
        Self {
            phase: ProofPhase::AwaitingProof { session_id, started_at: Instant::now() },
            kind: ProofKind::Tee { zk_fallback_request, zk_fallback_intent },
            invalid_index,
            expected_root,
            retry_count: 0,
            intent: DisputeIntent::Nullify,
        }
    }

    /// Creates a new ZK `PendingProof` in the `ReadyToSubmit` phase.
    pub const fn ready(
        proof_bytes: Bytes,
        invalid_index: u64,
        expected_root: B256,
        prove_request: SnarkGroth16ProofRequest,
        intent: DisputeIntent,
    ) -> Self {
        Self {
            phase: ProofPhase::ReadyToSubmit { proof_bytes },
            kind: ProofKind::Zk { prove_request },
            invalid_index,
            expected_root,
            retry_count: 0,
            intent,
        }
    }

    /// Returns `true` if the proof is in the `ReadyToSubmit` phase.
    pub const fn is_ready(&self) -> bool {
        matches!(self.phase, ProofPhase::ReadyToSubmit { .. })
    }
}

/// Collection of in-flight proof sessions keyed by dispute-game address.
#[derive(Debug, Default)]
pub struct PendingProofs(HashMap<Address, PendingProof>);

impl PendingProofs {
    /// Creates an empty collection.
    pub fn new() -> Self {
        Self::default()
    }

    /// Inserts a pending proof for the given game address.
    pub fn insert(&mut self, game: Address, proof: PendingProof) {
        self.0.insert(game, proof);
    }

    /// Removes the pending proof for the given game address.
    pub fn remove(&mut self, game: &Address) {
        self.0.remove(game);
    }

    /// Returns a reference to the pending proof for the given game address.
    pub fn get(&self, game: &Address) -> Option<&PendingProof> {
        self.0.get(game)
    }

    /// Returns a mutable reference to the pending proof for the given game address.
    pub fn get_mut(&mut self, game: &Address) -> Option<&mut PendingProof> {
        self.0.get_mut(game)
    }

    /// Returns `true` if there is a pending proof for the given game address.
    pub fn contains_key(&self, game: &Address) -> bool {
        self.0.contains_key(game)
    }

    /// Returns the game addresses with pending proofs.
    pub fn addresses(&self) -> Vec<Address> {
        self.0.keys().copied().collect()
    }

    /// Returns the number of pending proofs.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns `true` if there are no pending proofs.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Polls prover service for an in-flight proof and advances the entry.
    ///
    /// - **`AwaitingProof`** — sends a `GetProofRequest` to prover service
    ///   and transitions the entry based on the response status.
    /// - **`ReadyToSubmit`** — returns [`ProofUpdate::Ready`] immediately.
    /// - **`NeedsRetry`** — returns [`ProofUpdate::NeedsRetry`] immediately
    ///   so the driver can re-initiate `proveBlockRange`.
    ///
    /// Returns `Ok(None)` when `game` has no entry in the collection.
    pub async fn poll<P: ProofRequesterProvider>(
        &mut self,
        game: Address,
        proof_requester: &P,
        max_proof_duration: Duration,
    ) -> eyre::Result<Option<ProofUpdate>> {
        let pending = match self.0.get(&game) {
            Some(p) => p,
            None => return Ok(None),
        };

        let (session_id, started_at) = match &pending.phase {
            ProofPhase::AwaitingProof { session_id, started_at } => {
                (session_id.clone(), *started_at)
            }
            ProofPhase::ReadyToSubmit { proof_bytes } => {
                return Ok(Some(ProofUpdate::Ready(proof_bytes.clone())));
            }
            ProofPhase::NeedsRetry => {
                return Ok(Some(ProofUpdate::NeedsRetry));
            }
        };

        // Check the timeout before the RPC so persistent transport errors
        // don't keep the entry pinned in `AwaitingProof`.
        let elapsed = started_at.elapsed();
        if elapsed > max_proof_duration {
            let pending = self.0.get_mut(&game).expect("entry just inspected");
            warn!(
                game = %game,
                elapsed = ?elapsed,
                limit = ?max_proof_duration,
                "proof session timed out, will retry"
            );
            pending.retry_count += 1;
            pending.phase = ProofPhase::NeedsRetry;
            return Ok(Some(ProofUpdate::NeedsRetry));
        }

        let request = GetProofRequest { session_id };

        let response = proof_requester.get_proof(request).await?;

        // Re-borrow after the await point.
        let pending = match self.0.get_mut(&game) {
            Some(p) => p,
            None => return Ok(None),
        };

        let update = match response.status {
            ProofStatus::Succeeded => {
                let Some(result) = response.result else {
                    warn!(game = %game, "proof succeeded without result, treating as retryable failure");
                    pending.retry_count += 1;
                    pending.phase = ProofPhase::NeedsRetry;
                    return Ok(Some(ProofUpdate::NeedsRetry));
                };
                let proof_bytes = match &pending.kind {
                    ProofKind::Zk { .. } => {
                        ChallengerProofAdapter::snark_groth16_dispute_proof_bytes(result)?
                    }
                    ProofKind::Tee { .. } => {
                        match ChallengerProofAdapter::tee_dispute_proof_bytes(
                            result,
                            pending.expected_root,
                        ) {
                            Ok(proof_bytes) => proof_bytes,
                            Err(e) => {
                                warn!(
                                    game = %game,
                                    error = %e,
                                    "TEE proof validation failed, falling back to ZK"
                                );
                                pending.retry_count += 1;
                                pending.phase = ProofPhase::NeedsRetry;
                                return Ok(Some(ProofUpdate::NeedsRetry));
                            }
                        }
                    }
                };
                let update = ProofUpdate::Ready(proof_bytes.clone());

                pending.phase = ProofPhase::ReadyToSubmit { proof_bytes };

                update
            }
            ProofStatus::Failed => {
                warn!(game = %game, error_message = ?response.error_message, "proof job failed");
                pending.retry_count += 1;
                pending.phase = ProofPhase::NeedsRetry;
                ProofUpdate::NeedsRetry
            }
            ProofStatus::Queued | ProofStatus::Running => ProofUpdate::Pending,
        };

        Ok(Some(update))
    }
}

/// Result of advancing a pending proof via [`PendingProofs::poll`].
#[derive(Debug, Clone)]
pub enum ProofUpdate {
    /// The proof succeeded — type-prefixed bytes are ready for submission.
    Ready(Bytes),
    /// The proof job failed — the entry is retained for retry.
    NeedsRetry,
    /// The proof is still in progress.
    Pending,
}
