//! Pending proof state machine and collection.
//!
//! [`PendingProofs`] tracks in-flight proof sessions keyed by dispute-game
//! address. Each entry moves through a [`ProofPhase`] lifecycle:
//! `AwaitingProof` → `ReadyToSubmit` (on success) or `NeedsRetry` (on failure).
//!
//! Each entry also carries a [`DisputeIntent`] that determines whether the
//! completed proof will be submitted via `challenge()` or `nullify()` on-chain.

use std::{
    collections::HashMap,
    time::{Duration, Instant},
};

use alloy_primitives::{Address, B256, Bytes};
use base_prover_service_client::ProofRequesterProvider;
use base_prover_service_protocol::{GetProofRequest, ProofStatus, SnarkPlonkProofRequest};
use tracing::warn;

use crate::{ChallengerMetrics, ChallengerProofAdapter};

/// The kind of proof being generated.
#[derive(Debug, Clone)]
pub enum ProofKind {
    /// A TEE (Trusted Execution Environment) attestation proof.
    ///
    /// Carries an optional pre-built ZK fallback request and intent so the
    /// driver can initiate a ZK proof after TEE proof or submission failures.
    /// The fallback is `None` when building the ZK request failed (e.g.
    /// `checkpoint_start_block` error); in that case no ZK fallback is possible.
    Tee {
        /// Pre-built ZK request and intent for fallback if TEE submission fails.
        zk_fallback: Option<(SnarkPlonkProofRequest, DisputeIntent)>,
    },
    /// A ZK (zero-knowledge) proof generated by the ZK proving service.
    ///
    /// Carries the original request parameters so the driver can re-initiate
    /// `proveBlockRange` on failure.
    Zk {
        /// Original request parameters for retry.
        prove_request: SnarkPlonkProofRequest,
    },
}

impl ProofKind {
    /// Returns `true` if this is a TEE proof.
    pub const fn is_tee(&self) -> bool {
        matches!(self, Self::Tee { .. })
    }
}

/// The intended on-chain action for a completed proof.
///
/// A TEE proof always targets `nullify()`. A ZK proof may target either
/// `challenge()` (Path 1: challenging a wrong TEE proposal) or `nullify()`
/// (Path 2: nullifying a fraudulent ZK challenge, Path 3: nullifying a
/// wrong ZK proposal).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DisputeIntent {
    /// Submit via `challenge()` — challenges a TEE proof with a competing ZK proof.
    Challenge,
    /// Submit via `nullify()` — nullifies an existing proof.
    Nullify,
}

/// Phase of a pending proof: awaiting prover service, ready for on-chain
/// submission, or waiting for a retry after failure.
#[derive(Debug, Clone)]
pub enum ProofPhase {
    /// Waiting for the ZK proof service to complete.
    AwaitingProof {
        /// Session ID returned by the ZK proof service.
        session_id: String,
        /// Wall-clock time at which the proof request was initiated.
        started_at: Instant,
    },
    /// Proof obtained — proof bytes are ready for dispute submission.
    ReadyToSubmit {
        /// Type-prefixed proof bytes.
        proof_bytes: Bytes,
    },
    /// Proof job failed — the driver should re-initiate `proveBlockRange`.
    NeedsRetry,
}

/// State for an in-flight proof session.
#[derive(Debug, Clone)]
pub struct PendingProof {
    /// Current phase of this proof lifecycle.
    pub phase: ProofPhase,
    /// The kind of proof (TEE or ZK). For ZK proofs this also carries the
    /// original request parameters needed for retry.
    pub kind: ProofKind,
    /// The index of the invalid intermediate root.
    pub invalid_index: u64,
    /// The expected correct root at that index.
    pub expected_root: B256,
    /// Number of times this proof has been retried after failure.
    pub retry_count: u32,
    /// Number of retryable TEE submission failures already retried for this ready proof.
    pub tee_submit_retry_count: u32,
    /// The intended on-chain dispute action once the proof is ready.
    pub intent: DisputeIntent,
}

impl PendingProof {
    /// Creates a new `PendingProof` in the `AwaitingProof` phase.
    pub fn awaiting(
        session_id: String,
        invalid_index: u64,
        expected_root: B256,
        prove_request: SnarkPlonkProofRequest,
        intent: DisputeIntent,
    ) -> Self {
        Self {
            phase: ProofPhase::AwaitingProof { session_id, started_at: Instant::now() },
            kind: ProofKind::Zk { prove_request },
            invalid_index,
            expected_root,
            retry_count: 0,
            tee_submit_retry_count: 0,
            intent,
        }
    }

    /// Creates a new TEE `PendingProof` in the `AwaitingProof` phase.
    pub fn awaiting_tee(
        session_id: String,
        invalid_index: u64,
        expected_root: B256,
        zk_fallback: Option<(SnarkPlonkProofRequest, DisputeIntent)>,
    ) -> Self {
        Self {
            phase: ProofPhase::AwaitingProof { session_id, started_at: Instant::now() },
            kind: ProofKind::Tee { zk_fallback },
            invalid_index,
            expected_root,
            retry_count: 0,
            tee_submit_retry_count: 0,
            intent: DisputeIntent::Nullify,
        }
    }

    /// Creates a new ZK `PendingProof` in the `ReadyToSubmit` phase.
    pub const fn ready(
        proof_bytes: Bytes,
        invalid_index: u64,
        expected_root: B256,
        prove_request: SnarkPlonkProofRequest,
        intent: DisputeIntent,
    ) -> Self {
        Self {
            phase: ProofPhase::ReadyToSubmit { proof_bytes },
            kind: ProofKind::Zk { prove_request },
            invalid_index,
            expected_root,
            retry_count: 0,
            tee_submit_retry_count: 0,
            intent,
        }
    }
}

/// Collection of in-flight proof sessions keyed by dispute-game address.
#[derive(Debug, Default)]
pub struct PendingProofs(HashMap<Address, PendingProof>);

impl PendingProofs {
    /// Creates an empty collection.
    pub fn new() -> Self {
        Self::default()
    }

    /// Inserts a pending proof for the given game address.
    pub fn insert(&mut self, game: Address, proof: PendingProof) {
        self.0.insert(game, proof);
    }

    /// Removes the pending proof for the given game address.
    pub fn remove(&mut self, game: &Address) {
        self.0.remove(game);
    }

    /// Returns a reference to the pending proof for the given game address.
    pub fn get(&self, game: &Address) -> Option<&PendingProof> {
        self.0.get(game)
    }

    /// Returns a mutable reference to the pending proof for the given game address.
    pub fn get_mut(&mut self, game: &Address) -> Option<&mut PendingProof> {
        self.0.get_mut(game)
    }

    /// Returns `true` if there is a pending proof for the given game address.
    pub fn contains_key(&self, game: &Address) -> bool {
        self.0.contains_key(game)
    }

    /// Returns the game addresses with pending proofs.
    pub fn addresses(&self) -> Vec<Address> {
        self.0.keys().copied().collect()
    }

    /// Returns the number of pending proofs.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns `true` if there are no pending proofs.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Polls prover service for an in-flight proof and advances the entry.
    ///
    /// - **`AwaitingProof`** — sends a `GetProofRequest` to prover service
    ///   and transitions the entry based on the response status.
    /// - **`ReadyToSubmit`** — returns [`ProofUpdate::Ready`] immediately.
    /// - **`NeedsRetry`** — returns [`ProofUpdate::NeedsRetry`] immediately
    ///   so the driver can re-initiate `proveBlockRange`.
    ///
    /// Returns `Ok(None)` when `game` has no entry in the collection.
    pub async fn poll<P: ProofRequesterProvider>(
        &mut self,
        game: Address,
        proof_requester: &P,
        max_proof_duration: Duration,
    ) -> eyre::Result<Option<ProofUpdate>> {
        let pending = match self.0.get(&game) {
            Some(p) => p,
            None => return Ok(None),
        };

        let (session_id, started_at) = match &pending.phase {
            ProofPhase::AwaitingProof { session_id, started_at } => {
                (session_id.clone(), *started_at)
            }
            ProofPhase::ReadyToSubmit { proof_bytes } => {
                return Ok(Some(ProofUpdate::Ready(proof_bytes.clone())));
            }
            ProofPhase::NeedsRetry => {
                return Ok(Some(ProofUpdate::NeedsRetry));
            }
        };

        // Check the timeout before the RPC so persistent transport errors
        // don't keep the entry pinned in `AwaitingProof`.
        let elapsed = started_at.elapsed();
        if elapsed > max_proof_duration {
            let pending = self.0.get_mut(&game).expect("entry just inspected");
            warn!(
                game = %game,
                elapsed = ?elapsed,
                limit = ?max_proof_duration,
                "proof session timed out, will retry"
            );
            ChallengerMetrics::proof_session_failures_total(
                ChallengerMetrics::PROOF_FAILURE_TIMEOUT,
            )
            .increment(1);
            pending.retry_count += 1;
            pending.phase = ProofPhase::NeedsRetry;
            return Ok(Some(ProofUpdate::NeedsRetry));
        }

        let request = GetProofRequest { session_id };

        let response = proof_requester.get_proof(request).await?;

        // Re-borrow after the await point.
        let pending = match self.0.get_mut(&game) {
            Some(p) => p,
            None => return Ok(None),
        };

        let update = match response.status {
            ProofStatus::Succeeded => {
                let Some(result) = response.result else {
                    warn!(game = %game, "proof succeeded without result, treating as retryable failure");
                    ChallengerMetrics::proof_session_failures_total(
                        ChallengerMetrics::PROOF_FAILURE_MALFORMED,
                    )
                    .increment(1);
                    pending.retry_count += 1;
                    pending.phase = ProofPhase::NeedsRetry;
                    return Ok(Some(ProofUpdate::NeedsRetry));
                };
                let proof_bytes = match &pending.kind {
                    ProofKind::Zk { .. } => {
                        ChallengerProofAdapter::snark_plonk_dispute_proof_bytes(result)?
                    }
                    ProofKind::Tee { .. } => {
                        match ChallengerProofAdapter::tee_dispute_proof_bytes(
                            result,
                            pending.expected_root,
                        ) {
                            Ok(proof_bytes) => proof_bytes,
                            Err(e) => {
                                warn!(
                                    game = %game,
                                    error = %e,
                                    "TEE proof validation failed, falling back to ZK"
                                );
                                ChallengerMetrics::proof_session_failures_total(
                                    ChallengerMetrics::PROOF_FAILURE_TEE_VALIDATION,
                                )
                                .increment(1);
                                pending.retry_count += 1;
                                pending.phase = ProofPhase::NeedsRetry;
                                return Ok(Some(ProofUpdate::NeedsRetry));
                            }
                        }
                    }
                };
                let update = ProofUpdate::Ready(proof_bytes.clone());

                pending.phase = ProofPhase::ReadyToSubmit { proof_bytes };

                update
            }
            ProofStatus::Failed => {
                warn!(game = %game, error_message = ?response.error_message, "proof job failed");
                ChallengerMetrics::proof_session_failures_total(
                    ChallengerMetrics::PROOF_FAILURE_FAILED,
                )
                .increment(1);
                pending.retry_count += 1;
                pending.phase = ProofPhase::NeedsRetry;
                ProofUpdate::NeedsRetry
            }
            ProofStatus::Queued | ProofStatus::Running => ProofUpdate::Pending,
        };

        Ok(Some(update))
    }
}

/// Result of advancing a pending proof via [`PendingProofs::poll`].
#[derive(Debug, Clone)]
pub enum ProofUpdate {
    /// The proof succeeded — type-prefixed bytes are ready for submission.
    Ready(Bytes),
    /// The proof job failed — the entry is retained for retry.
    NeedsRetry,
    /// The proof is still in progress.
    Pending,
}

#[cfg(test)]
mod tests {
    use std::{
        sync::{Arc, Mutex},
        time::Duration,
    };

    use alloy_primitives::{Address, B256};
    use base_prover_service_protocol::{ZkBackend, ZkProofRequest, ZkVm};

    use super::*;
    use crate::test_utils::{MockZkProofProvider, MockZkProofState, addr};

    const fn minimal_prove_request() -> SnarkPlonkProofRequest {
        SnarkPlonkProofRequest {
            proof: ZkProofRequest {
                start_block_number: 0,
                number_of_blocks_to_prove: 1,
                sequence_window: None,
                l1_head: None,
                intermediate_root_interval: None,
                schedule_l2_block_number: None,
                zk_artifact_hash: None,
                zk_vm: ZkVm::Sp1,
                zk_backend: ZkBackend::Cluster,
            },
            prover_address: Address::ZERO,
        }
    }

    fn awaiting_proof(session_id: &str) -> PendingProof {
        PendingProof::awaiting(
            session_id.to_owned(),
            0,
            B256::ZERO,
            minimal_prove_request(),
            DisputeIntent::Challenge,
        )
    }

    #[tokio::test]
    async fn poll_transitions() {
        for (status, max_proof_duration, expected_retry_count) in [
            (ProofStatus::Failed, Duration::from_secs(3600), 1),
            (ProofStatus::Running, Duration::from_secs(3600), 0),
            (ProofStatus::Running, Duration::ZERO, 1),
        ] {
            let zk = Arc::new(MockZkProofProvider {
                state: Mutex::new(MockZkProofState { proof_status: status, ..Default::default() }),
            });
            let mut proofs = PendingProofs::new();
            proofs.insert(addr(0), awaiting_proof("session"));

            let update = proofs.poll(addr(0), &*zk, max_proof_duration).await.unwrap();
            let should_retry = expected_retry_count != 0;

            let entry = proofs.get(&addr(0)).unwrap();
            assert_eq!(entry.retry_count, expected_retry_count);
            if should_retry {
                assert!(matches!(update, Some(ProofUpdate::NeedsRetry)));
                assert!(matches!(entry.phase, ProofPhase::NeedsRetry));
            } else {
                assert!(matches!(update, Some(ProofUpdate::Pending)));
                assert!(matches!(entry.phase, ProofPhase::AwaitingProof { .. }));
            }
        }
    }

    #[cfg(feature = "metrics")]
    mod metrics_emission {
        use alloy_primitives::Bytes;
        use base_proof_primitives::Proposal;
        use base_prover_service_protocol::{
            ProofResult as ApiProofResult, TeeKind, TeeProofResult,
        };
        use metrics_util::{
            MetricKind,
            debugging::{DebugValue, DebuggingRecorder},
        };

        use super::*;
        use crate::ChallengerMetrics;

        fn assert_failure_metric(
            proof: PendingProof,
            state: MockZkProofState,
            max_proof_duration: Duration,
            expected_reason: &str,
        ) {
            let recorder = DebuggingRecorder::new();
            let snapshotter = recorder.snapshotter();
            metrics::with_local_recorder(&recorder, || {
                let runtime =
                    tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
                runtime.block_on(async {
                    let zk = MockZkProofProvider { state: Mutex::new(state) };
                    let mut proofs = PendingProofs::new();
                    proofs.insert(addr(0), proof);
                    proofs.poll(addr(0), &zk, max_proof_duration).await.unwrap();
                });

                let snapshot = snapshotter.snapshot().into_vec();
                let count = snapshot.iter().find_map(|(key, _, _, value)| {
                    if key.kind() != MetricKind::Counter
                        || key.key().name() != "base_challenger.proof_session_failures_total"
                        || !key.key().labels().any(|label| {
                            label.key() == "reason" && label.value() == expected_reason
                        })
                    {
                        return None;
                    }
                    match value {
                        DebugValue::Counter(value) => Some(*value),
                        _ => None,
                    }
                });

                assert_eq!(count, Some(1));
            });
        }

        #[test]
        fn poll_emits_failure_metrics() {
            let expected_root = B256::repeat_byte(0xaa);
            let bad_proposal = Proposal {
                output_root: B256::repeat_byte(0xbb),
                signature: Bytes::from_static(&[0; 65]),
                l1_origin_hash: B256::ZERO,
                l1_origin_number: 0,
                l2_block_number: 0,
                prev_output_root: B256::ZERO,
                config_hash: B256::ZERO,
                schedule_id: B256::ZERO,
            };

            for (proof, state, max_proof_duration, expected_reason) in [
                (
                    awaiting_proof("stuck-session"),
                    MockZkProofState { proof_status: ProofStatus::Running, ..Default::default() },
                    Duration::ZERO,
                    ChallengerMetrics::PROOF_FAILURE_TIMEOUT,
                ),
                (
                    awaiting_proof("failed-session"),
                    MockZkProofState { proof_status: ProofStatus::Failed, ..Default::default() },
                    Duration::from_secs(3600),
                    ChallengerMetrics::PROOF_FAILURE_FAILED,
                ),
                (
                    awaiting_proof("malformed-session"),
                    MockZkProofState {
                        proof_status: ProofStatus::Succeeded,
                        omit_result_on_success: true,
                        ..Default::default()
                    },
                    Duration::from_secs(3600),
                    ChallengerMetrics::PROOF_FAILURE_MALFORMED,
                ),
                (
                    PendingProof::awaiting_tee(
                        "tee-bad-root-session".to_owned(),
                        0,
                        expected_root,
                        Some((minimal_prove_request(), DisputeIntent::Challenge)),
                    ),
                    MockZkProofState {
                        proof_status: ProofStatus::Succeeded,
                        result: Some(ApiProofResult::Tee(TeeProofResult {
                            aggregate_proposal: bad_proposal,
                            proposals: Vec::new(),
                            tee_kind: TeeKind::AwsNitro,
                            tee_signer: Address::repeat_byte(0x11),
                        })),
                        ..Default::default()
                    },
                    Duration::from_secs(3600),
                    ChallengerMetrics::PROOF_FAILURE_TEE_VALIDATION,
                ),
            ] {
                assert_failure_metric(proof, state, max_proof_duration, expected_reason);
            }
        }
    }
}
