[package]
name = "base-execution-state-provider"
description = "Reth storage provider."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
rayon = {workspace = true }
metrics = {workspace = true}
strum = { workspace = true }
alloy-eips = {workspace = true}
smallvec = { workspace = true }
itertools = { workspace = true }
alloy-chains = { workspace = true }
alloy-genesis = { workspace = true }
reth-chain-state = {workspace = true}
base-common-io-files = { workspace = true }
base-common-chain-config = { workspace = true }
base-common-types-payload = { workspace = true }
base-execution-evm-runtime = { workspace = true }
eyre = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }
reth-trie = {workspace = true, features = ["metrics"]}
rocksdb = { workspace = true, features = ["default"] }
tracing = {workspace = true, features = ["attributes"]}
alloy-eip7928 = { workspace = true, features = ["rlp"] }
parking_lot = {workspace = true, features = ["default"]}
notify = { workspace = true, features = ["macos_fsevent"] }
alloy-primitives = {workspace = true, features = ["map-foldhash"]}
tokio = { workspace = true, features = ["sync"], optional = true }
base-common-types-chain = { workspace = true, features = ["reth"] }
base-common-runtime-tasks = {workspace = true,  features = ["rayon"]}
base-execution-state-database = {workspace = true, features = ["mdbx"]}
base-execution-state-api = {workspace = true, features = ["db-api", "std"]}
base-common-observability-metrics = {workspace = true, features = ["metrics"]}
base-execution-state-types = {workspace = true, features = ["reth-codec", "std"]}
base-execution-state-memory = {workspace = true, features = ["reth-codec", "std"]}
reth-primitives-traits = {workspace = true, features = ["dashmap", "reth-codec", "secp256k1", "std"]}

[target.'cfg(unix)'.dependencies]
libc = { workspace = true, features = ["default"] }
[dev-dependencies]
assert_matches = { workspace = true }
alloy-hardforks = { workspace = true }
reth-testing-utils = { workspace = true }
base-common-chain-config = { workspace = true }
rand = { workspace = true, features = ["default"] }
tempfile = { workspace = true, features = ["default"] }
reth-trie = {workspace = true, features = ["test-utils"]}
reth-chain-state = {workspace = true, features = ["test-utils"]}
base-common-types-chain = {workspace = true, features = ["serde"]}
tokio-stream = { workspace = true, features = ["default", "sync"] }
base-execution-state-database = {workspace = true, features = ["test-utils"]}
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
reth-primitives-traits = {workspace = true, features = ["arbitrary", "test-utils"]}
base-execution-state-types = {workspace = true, features = ["arbitrary", "test-utils"]}
base-execution-state-memory = {workspace = true, features = ["arbitrary", "test-utils"]}

[features]
jemalloc = ["rocksdb/jemalloc"]
partial-persistence = ["base-execution-state-types/partial-persistence"]
test-utils = [
    "base-execution-state-database/test-utils",
    "reth-trie/test-utils",
    "reth-chain-state/test-utils",
    "reth-primitives-traits/test-utils",
    "base-common-types-chain/test-utils",
    "base-execution-state-types/test-utils",
    "base-common-runtime-tasks/test-utils",
    "dep:tokio",
    "base-execution-state-memory/test-utils",
]
rayon = []
