[package]
name = "base-consensus-cli"
description = "CLI argument types for Base consensus clients"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
dirs = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
metrics = { workspace = true }
alloy-signer = { workspace = true }
alloy-genesis = { workspace = true }
base-protocol = { workspace = true }
base-cli-utils = { workspace = true }
alloy-primitives = { workspace = true }
base-consensus-peers = { workspace = true }
base-consensus-derive = { workspace = true }
base-consensus-engine = { workspace = true }
base-consensus-gossip = { workspace = true }
base-consensus-sources = { workspace = true }
base-common-runtime-tasks = { workspace = true }
tracing = { workspace = true, features = ["std"] }
url = { workspace = true, features = ["default"] }
eyre = { workspace = true, features = ["default"] }
discv5 = { workspace = true, features = ["libp2p"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["default"] }
backon = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }
reqwest = { workspace = true, features = ["default"] }
alloy-chains = { workspace = true, features = ["std"] }
tokio-util = { workspace = true, features = ["default"] }
base-consensus-rpc = { workspace = true, features = ["default"] }
base-consensus-disc = { workspace = true, features = ["metrics"] }
base-consensus-node = { workspace = true, features = ["metrics"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
base-common-chain-config = {workspace = true, features = ["default"]}
base-consensus-providers = { workspace = true, features = ["metrics"] }
base-common-client-ethereum = {workspace = true, features = ["default"]}
base-common-chain-activation = { workspace = true, features = ["default", "metrics"] }
libp2p = { workspace = true, features = ["secp256k1", "macros", "tokio", "tcp", "noise", "gossipsub", "ping", "yamux", "identify"] }

[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
httpmock = { workspace = true, features = ["default"] }
tempfile = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "test-util"] }

[features]
default = ["otlp"]
otlp = ["base-cli-utils/otlp"]
