[package]
name = "basectl-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dirs = { workspace = true }
serde_yaml = { workspace = true }
alloy-contract = { workspace = true }
alloy-transport = { workspace = true }
base-tx-manager = { workspace = true }
base-common-network = { workspace = true }
base-consensus-peers = { workspace = true }
base-proof-contracts = { workspace = true }
base-consensus-gossip = { workspace = true }
base-proof-submission = { workspace = true }
alloy-rpc-types-txpool = { workspace = true }
base-common-precompiles = { workspace = true }
serde = { workspace = true, features = ["std"] }
base-prover-service-client = { workspace = true }
tracing = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
alloy-eips = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["default"] }
anyhow = { workspace = true, features = ["default"] }
ratatui = { workspace = true, features = ["default"] }
arboard = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
crossterm = { workspace = true, features = ["default"] }
toml = { workspace = true, features = ["parse", "serde"] }
base-common-evm = { workspace = true, features = ["std"] }
alloy-sol-types = { workspace = true, features = ["std"] }
base-common-rpc-types = { workspace = true, features = []}
url = { workspace = true, features = ["default", "serde"] }
jsonrpsee = { workspace = true, features = ["http-client"] }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-rpc-types-eth = { workspace = true, features = ["std"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
base-protocol = { workspace = true, features = ["serde", "std"] }
base-common-chains = { workspace = true, features = ["default"] }
base-upgrade-signal = { workspace = true, features = ["default"] }
alloy-transport-http = { workspace = true, features = ["default"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
base-common-genesis = { workspace = true, features = ["serde", "std"] }
base-common-consensus = { workspace = true, features = ["k256", "std"] }
base-prover-service-protocol = { workspace = true, features = ["default"] }
base-consensus-rpc = { workspace = true, features = ["default", "client"] }
tokio = { workspace = true, features = ["default", "macros", "net", "process", "time"] }
tokio-tungstenite = { workspace = true, features = ["default", "rustls-tls-webpki-roots"] }
alloy-provider = { workspace = true, features = ["default", "admin-api", "net-api", "pubsub", "txpool-api", "ws"] }
[dev-dependencies]
tempfile = { workspace = true, features = ["default"] }
jsonrpsee = { workspace = true, features = ["server"] }
axum = { workspace = true, features = ["tokio", "http1", "json"] }
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread"] }
base-prover-service-protocol = { workspace = true, features = ["default", "rpc-server"] }
