[package]
name = "basectl-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dirs = { workspace = true }
serde_yaml = { workspace = true }
alloy-transport = { workspace = true }
base-proof-l1-submission = { workspace = true }
base-proof-submission = { workspace = true }
base-common-client-rollup = {workspace = true}
serde = { workspace = true, features = ["std"] }
base-proof-service-client = { workspace = true }
base-common-l1-transactions = { workspace = true }
tracing = { workspace = true, features = ["std"] }
base-common-client-contracts = { workspace = true }
base-consensus-network-service = {workspace = true}
thiserror = { workspace = true, features = ["std"] }
alloy-eips = { workspace = true, features = ["std"] }
anyhow = { workspace = true, features = ["default"] }
base-execution-evm-precompiles = { workspace = true }
chrono = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }
arboard = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
ratatui = { workspace = true, features = ["default"] }
crossterm = { workspace = true, features = ["default"] }
alloy-sol-types = { workspace = true, features = ["std"] }
toml = { workspace = true, features = ["parse", "serde"] }
url = { workspace = true, features = ["default", "serde"] }
jsonrpsee = { workspace = true, features = ["http-client"] }
alloy-primitives = { workspace = true, features = ["serde"] }
base-common-types-rpc = {workspace = true, features = ["std"]}
alloy-rpc-client = { workspace = true, features = ["default"] }
alloy-transport-http = { workspace = true, features = ["default"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
base-execution-evm-runtime = { workspace = true, features = ["std"] }
base-common-types-chain = { workspace = true, features = ["k256", "std"] }
base-common-chain-activation = { workspace = true, features = ["default"] }
base-proof-service-protocol = { workspace = true, features = ["default"] }
base-consensus-batch-types = { workspace = true, features = ["serde", "std"] }
base-common-chain-config = {workspace = true, features = ["default", "serde", "std"]}
tokio = { workspace = true, features = ["default", "macros", "net", "process", "time"] }
tokio-tungstenite = { workspace = true, features = ["default", "rustls-tls-webpki-roots"] }
base-common-client-ethereum = {workspace = true, features = ["admin-api", "default", "net-api", "pubsub", "txpool-api", "ws"]}

[dev-dependencies]
jsonrpsee = { workspace = true, features = ["server"] }
tempfile = { workspace = true, features = ["default"] }
axum = { workspace = true, features = ["tokio", "http1", "json"] }
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread"] }
base-proof-service-protocol = { workspace = true, features = ["default", "rpc-server"] }
