[package]
name = "base-consensus-source-providers"
version.workspace = true
description = "Alloy Backed Providers"

edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
c-kzg = { workspace = true }
tower = { workspace = true }
reth-db = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
alloy-signer = { workspace = true }
alloy-genesis = { workspace = true }
alloy-transport = {workspace = true}
reth-provider = { workspace = true }
reth-rpc-layer = { workspace = true }
serde = {workspace = true, features = ["std"]}
base-common-chain-config = { workspace = true }
base-execution-state-api = { workspace = true }
metrics = { workspace = true, optional = true }
tracing = {workspace = true, features = ["std"]}
url = {workspace = true, features = ["default"]}
base-consensus-batch-types = { workspace = true }
base-execution-state-types = { workspace = true }
lru = { workspace = true, features = ["default"] }
thiserror = {workspace = true, features = ["std"]}
base-consensus-derive-pipeline = { workspace = true }
notify = { workspace = true, features = ["default"] }
rustls = { workspace = true, features = ["default"] }
serde_json = { workspace = true, features = ["std"] }
alloy-serde = { workspace = true, features = ["std"] }
reqwest = { workspace = true, features = ["default"] }
base-common-observability-metrics = { workspace = true }
alloy-primitives = {workspace = true, features = ["map"]}
base-common-types-rpc = { workspace = true, features = []}
alloy-eips = { workspace = true, features = ["kzg", "std"] }
alloy-rpc-client = {workspace = true, features = ["default"]}
http-body-util = { workspace = true, features = ["default"] }
base-common-types-chain = { workspace = true, features = ["std"]}
tokio = {workspace = true, features = ["default", "full", "time"]}
base-common-types-payload = { workspace = true, features = ["std", "serde"] }
base-common-client-ethereum = {workspace = true, features = ["default", "reqwest", "ws"]}
alloy-transport-http = {workspace = true, features = ["default", "hyper", "hyper-tls", "reqwest", "reqwest-rustls-tls"]}

[dev-dependencies]
reth-db-common = { workspace = true }
base-common-types-rpc = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
httpmock = { workspace = true, features = ["default"] }
reth-provider = { workspace = true, features = ["test-utils"] }
tokio = {workspace = true, features = ["default", "macros", "test-util"]}

[features]
default = []
metrics = ["base-consensus-derive-pipeline/metrics", "base-common-observability-metrics/metrics", "dep:metrics"]
