[package]
name = "base-protocol"
description = "Protocol Types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
brotli = { workspace = true }
alloy-rlp = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
ambassador = { workspace = true }
async-trait = { workspace = true }
alloy-genesis = { workspace = true }
alloc-no-stdlib = { workspace = true }
base-common-types-rpc = { workspace = true }
serde = { workspace = true, optional = true }
base-common-types-chain = { workspace = true }
base-common-types-payload = {workspace = true}
base-common-chain-config = { workspace = true }
tracing = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["display"] }
miniz_oxide = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map"] }
spin = { workspace = true, optional = true, features = ["default"] }
arbitrary = { workspace = true, features = ["derive"], optional = true }
tracing-subscriber = { workspace = true, features = ["default", "fmt"], optional = true }

[dev-dependencies]
tracing = { workspace = true }
serde_json = { workspace = true }
brotli = { workspace = true, features = ["std"] }
spin = { workspace = true, features = ["default"] }
rstest = { workspace = true, features = ["default"] }
arbitrary = { workspace = true, features = ["derive"] }
proptest = { workspace = true, features = ["default"] }
criterion = { workspace = true, features = ["default"] }
iai-callgrind = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "full"] }
alloy-primitives = { workspace = true, features = ["arbitrary"] }
base-common-types-rpc = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default", "std", "std_rng"] }
base-common-chain-config = { workspace = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = ["default", "fmt"] }

[[bench]]
name = "batch_transaction"
harness = false

[[bench]]
name = "frame_parse"
harness = false

[[bench]]
name = "batch_transaction_iai"
harness = false

[[bench]]
name = "frame_parse_iai"
harness = false

[features]
default = [ "std" ]
test-utils = [
	"base-common-chain-config/test-utils",
	"dep:spin",
    "dep:tracing",
	"dep:tracing-subscriber",
]
std = [
    "base-common-types-chain/std",
    "alloy-eips/std",
    "alloy-genesis/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "base-common-types-payload/std",
    "base-common-types-rpc/std",
    "base-common-chain-config/std",
    "brotli/std",
    "derive_more/std",
    "miniz_oxide/std",
    "serde?/std",
    "spin?/std",
    "thiserror/std",
    "tracing?/std",
]
serde = [
    "base-common-types-chain/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "base-common-types-payload/serde",
    "base-common-types-rpc/serde",
    "base-common-chain-config/serde",
    "dep:serde",
    "miniz_oxide/serde",
    "tracing-subscriber?/serde",
]
arbitrary = [
    "base-common-types-chain/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-primitives/rand",
    "base-common-types-payload/arbitrary",
    "base-common-types-rpc/arbitrary",
    "base-common-chain-config/arbitrary",
    "dep:arbitrary",
    "std",
]
