[package]
name = "base-infra-snapshotter-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true, features = ["default"] }
anyhow = { workspace = true, features = ["default"] }
bollard = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
base-execution-state-maintenance = { workspace = true }
clap = { workspace = true, features = ["default", "derive", "env"] }
tokio = { workspace = true, features = ["default", "rt", "fs", "time"] }
base-common-client-ethereum = { workspace = true, features = ["default", "reqwest"] }
aws-sdk-s3 = { workspace = true, features = ["rustls", "default-https-client", "rt-tokio"] }

[dev-dependencies]
serde_json = { workspace = true }
bollard = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
tempfile = { workspace = true, features = ["default"] }
serial_test = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "full"] }
testcontainers-modules = { workspace = true, features = ["minio"] }
aws-config = { workspace = true, features = ["default-https-client", "rt-tokio"] }
testcontainers = { workspace = true, features = ["blocking", "host-port-exposure"] }
