[package]
name = "base-execution-state-database"
description = "Database primitives used in reth."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
serde = { workspace = true }
metrics = {workspace = true }
arrayvec = { workspace = true }
thiserror = { workspace = true }
modular-bitfield = { workspace = true }
base-common-io-files = { workspace = true }
page_size = { workspace = true, optional = true }
derive_more = {workspace = true, features = ["full"]}
sysinfo = { workspace = true, features = ["system"] }
roaring = { workspace = true, features = ["default"] }
tracing = { workspace = true, features = ["attributes"] }
reth-nippy-jar = { workspace = true, features = ["default"] }
alloy-primitives = {workspace = true, features = ["map-foldhash"]}
base-common-types-chain = { workspace = true, features = ["serde"]}
eyre = { workspace = true, optional = true, features = ["default"] }
strum = { workspace = true, features = ["derive"], optional = true }
quanta = { workspace = true, optional = true, features = ["default"] }
rustc-hash = { workspace = true, features = ["std"], optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }
proptest = { workspace = true, optional = true, features = ["default"] }
tempfile = { workspace = true, optional = true, features = ["default"] }
parking_lot = { workspace = true, optional = true, features = ["default"] }
base-common-observability-tracing = { workspace = true, features = ["default"] }
reth-primitives-traits = { workspace = true, features = ["serde", "reth-codec"] }
base-execution-state-types = {workspace = true, features = ["reth-codec", "serde"]}
base-execution-state-memory = {workspace = true, features = ["reth-codec", "serde"]}
base-common-observability-metrics = { workspace = true, optional = true, features = ["metrics"]}
reth-libmdbx = { workspace = true, features = ["default", "return-borrowed", "read-tx-timeouts"], optional = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true, features = ["default"] }
[dev-dependencies]
serde = { workspace = true }
test-fuzz = { workspace = true }
assert_matches = { workspace = true }
proptest-arbitrary-interop = { workspace = true }
rand = { workspace = true, features = ["default"] }
arbitrary = {workspace = true, features = ["derive"]}
proptest = {workspace = true, features = ["default"]}
serde_json = { workspace = true, features = ["alloc"] }
tempfile = { workspace = true, features = ["default"] }
parking_lot = { workspace = true, features = ["default"] }
base-common-types-chain = {workspace = true, features = ["test-utils"]}
reth-primitives-traits = { workspace = true, features = ["reth-codec"] }
base-execution-state-memory = {workspace = true, features = ["reth-codec"]}
alloy-primitives = {workspace = true, features = ["getrandom", "map-foldhash", "rand"]}
base-execution-state-types = {workspace = true, features = ["arbitrary", "reth-codec"]}

[features]
default = ["mdbx"]
mdbx = [
    "dep:reth-libmdbx",
    "dep:eyre",
    "dep:page_size",
    "dep:quanta",
    "base-common-observability-metrics",
    "dep:strum",
    "dep:rustc-hash",
]
test-utils = [
    "dep:tempfile",
    "mdbx",
    "arbitrary",
    "parking_lot",
    "reth-nippy-jar/test-utils",
    "reth-primitives-traits/test-utils",
    "base-execution-state-types/test-utils",
    "base-execution-state-memory/test-utils",
    "base-common-types-chain/test-utils",
]
arbitrary = [
    "alloy-primitives/arbitrary",
    "base-common-types-chain/arbitrary",
    "reth-primitives-traits/arbitrary",
    "base-execution-state-types/arbitrary",
    "base-execution-state-memory/arbitrary",
    "dep:arbitrary",
    "dep:proptest",
]
disable-lock = []
