[package]
name = "base-proof-witness-mpt"
description = "Utilities for interacting with and iterating through a merkle patricia trie"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
alloy-rlp = { workspace = true }
alloy-trie = { workspace = true }
base-common-types-payload = { workspace = true }
alloy-primitives = { workspace = true, features = ["rlp"] }
serde = { workspace = true, features = ["derive", "alloc"], optional = true }
[dev-dependencies]
base-common-types-chain = { workspace = true }
rand = { workspace = true, features = ["default"] }
reqwest = { workspace = true, features = ["default"] }
proptest = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "full"] }
alloy-transport-http = { workspace = true, features = ["default"] }
base-common-client-ethereum = { workspace = true, features = ["default", "reqwest"] }
criterion = { workspace = true, features = ["default", "html_reports"] }
base-common-types-rpc = { workspace = true, features = ["serde", "std"] }
[[bench]]
name = "trie_node"
harness = false

[features]
default = [ "serde" ]
std = [
    "alloy-primitives/std",
    "alloy-rlp/std",
    "alloy-trie/std",
    "base-common-types-payload/std",
    "serde?/std",
    "thiserror/std",
]
serde = [
	"alloy-primitives/serde",
	"alloy-trie/serde",
	"base-common-types-payload/serde",
	"dep:serde",
]
