[package]
name = "base-execution-evm-fees"
description = "Base transaction compression estimation, L1 data fees, and operator fees"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives = { workspace = true }
base-common-chain-config = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
rstest = { workspace = true, features = ["default"] }
criterion = { workspace = true, features = ["default"] }
iai-callgrind = { workspace = true, features = ["default"] }

[[bench]]
name = "flz"
harness = false

[[bench]]
name = "flz_iai"
harness = false

[features]
default = ["std"]
std = ["alloy-primitives/std", "base-common-chain-config/std"]

