[package]
name = "base-txpool-tracing"
description = "Transaction tracing extensions for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
serde_json = { workspace = true }
base-execution-state-provider = { workspace = true }
alloy-primitives = { workspace = true }
base-execution-txpool = { workspace = true }
metrics = { workspace = true, optional = true }
lru = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default"] }
chrono = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
base-common-observability-events = { workspace = true }
base-common-observability-metrics = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
tokio-stream = { workspace = true, features = ["default"] }
base-common-observability-tracing = { workspace = true, features = ["default"] }

[dev-dependencies]
base-testing-support = { workspace = true }
base-execution-state-memory = { workspace = true }
eyre = { workspace = true, features = ["default"] }
alloy-eips = { workspace = true, features = ["std"] }
base-node-runner = { workspace = true, features = ["test-utils"] }
base-common-types-payload = { workspace = true, features = ["std"] }
base-execution-txpool = { workspace = true, features = ["test-utils"] }
base-common-types-chain = { workspace = true, features = ["reth", "std"] }

[features]
default = ["metrics"]
metrics = ["base-common-observability-metrics/metrics", "base-common-observability-events/metrics", "dep:metrics"]
