[package]
name = "base-precompile-storage"
description = "EVM storage abstractions and runtime traits for Base native precompiles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
revm = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
alloy-sol-types = { workspace = true }
base-evm-context = { workspace = true }
alloy-primitives = { workspace = true }
base-evm-handler = { workspace = true }
base-precompile-macros = { workspace = true }
derive_more = { workspace = true, features = ["from", "try_into"] }
[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
proptest = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["rand"] }
[[test]]
name = "contract"
required-features = ["test-utils"]

[features]
default = [ "std" ]
std = [
    "base-evm-handler/std",
    "alloy-primitives/std",
    "alloy-sol-types/std",
    "derive_more/std",
    "revm/std",
    "thiserror/std",
    "tracing/std",
]
test-utils = [ "std" ]
