[package]
name = "base-upgrade-signal"
description = "L1 upgrade signal reader utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
base-retry = { workspace = true }
base-metrics = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-transport = { workspace = true }
metrics = { workspace = true, optional = true }
tower = { workspace = true, features = ["util"] }
url = { workspace = true, features = ["default"] }
eyre = { workspace = true, features = ["default"] }
thiserror = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
backon = { workspace = true, features = ["default"] }
futures = { workspace = true, features = ["default"] }
alloy-sol-types = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive", "std"] }
alloy-primitives = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["default"] }
base-common-genesis = { workspace = true, features = ["std"] }
alloy-rpc-types-eth = { workspace = true, features = ["std"] }
reqwest = { workspace = true, features = ["default", "json"] }
alloy-rpc-client = { workspace = true, features = ["default"] }
clap = { workspace = true, features = ["default", "derive", "env"] }
[dev-dependencies]
rstest = { workspace = true, features = ["default"] }
httpmock = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default", "macros", "rt", "time"] }
[features]
default = []
metrics = [ "base-metrics/metrics", "dep:metrics" ]
