[package]
name = "base-upgrade-signal"
description = "L1 upgrade signal reader utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-metrics.workspace = true

# alloy
alloy-provider.workspace = true
alloy-primitives = { workspace = true, features = ["std"] }
alloy-sol-types = { workspace = true, features = ["std"] }
alloy-rpc-types-eth = { workspace = true, features = ["std"] }

# general
url.workspace = true
metrics = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive", "env"] }
thiserror = { workspace = true, features = ["std"] }

[features]
default = []
metrics = [ "base-metrics/metrics", "dep:metrics" ]
