name: Action Tests

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

permissions:
  contents: read

jobs:
  action-tests:
    name: Action Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
        with:
          free-disk: "true"
          native-deps: "true"
          mold: "true"
          foundry: "true"
          components: clippy
          tools: cargo-nextest
          rust-cache-shared-key: "stable"
      - name: Build test contracts
        run: just build::contracts
      - name: Lint action tests
        run: just actions::lint-ci
      - name: Run action tests
        run: just actions::test-ci
