name: CI Main Cache

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

permissions:
  contents: read

jobs:
  warm-stable-cache:
    name: Warm Stable Cache
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
        with:
          free-disk: "true"
          native-deps: "true"
          mold: "true"
          foundry: "true"
          sp1: "true"
          elf-cache: "true"
          rust-cache-shared-key: "stable"
          rust-cache-save: "true"
      - run: just build::ci
