[package]
name = "base-proofs-extension"
description = "Proofs extension for Base node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-tasks = { workspace = true }
base-node-runner = { workspace = true }
base-node-context = { workspace = true }
base-execution-trie = { workspace = true }
tracing = { workspace = true, features = ["std"] }
eyre = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["default"] }
reth-db = { workspace = true, features = ["default"] }
base-node-core = { workspace = true, features = ["default"] }
base-execution-rpc = { workspace = true, features = ["default"] }
base-execution-exex = { workspace = true, features = ["metrics"] }
