[package]
name = "base-execution-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A payload builder for base-reth that builds Base payloads."

[lints]
workspace = true

[dependencies]
revm = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
alloy-rlp = { workspace = true }
alloy-evm = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
derive_more = { workspace = true }
base-metrics = { workspace = true }
base-bundles = { workspace = true }
base-protocol = { workspace = true }
reth-consensus = { workspace = true }
alloy-hardforks = { workspace = true }
base-common-evm = { workspace = true }
alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
reth-payload-util = { workspace = true }
reth-execution-cache = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-eip8130 = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
base-execution-chainspec = { workspace = true }
metrics = { workspace = true, optional = true }
base-observability-events = { workspace = true }
reth-basic-payload-builder = { workspace = true }
reth-payload-builder-primitives = { workspace = true }
reth-storage-api = { workspace = true, features = ["default"] }
reth-trie-common = { workspace = true, features = ["default"] }
reth-engine-primitives = { workspace = true, features = ["std"] }
base-common-consensus = { workspace = true, features = ["reth"] }
reth-trie-parallel = { workspace = true, features = ["default"] }
base-common-chains = { workspace = true, features = ["default"] }
base-execution-consensus = { workspace = true, features = ["std"] }
reth-execution-types = { workspace = true, features = ["default"] }
base-execution-txpool = { workspace = true, features = ["default"] }
reth-payload-validator = { workspace = true, features = ["default"] }
reth-payload-primitives = { workspace = true, features = ["default"] }
base-execution-evm = { workspace = true, features = ["default", "witness"] }
base-common-rpc-types-engine = { workspace = true, features = ["serde", "std"] }
[dev-dependencies]
metrics-exporter-prometheus = { workspace = true }
reth-provider = { workspace = true, features = ["test-utils"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
base-observability-events = { workspace = true, features = ["test-utils"] }
base-execution-evm = { workspace = true, features = ["default", "test-utils"] }

[features]
default = [ "metrics" ]
metrics = [
    "base-common-evm/metrics",
    "base-metrics/metrics",
    "base-observability-events/metrics",
    "dep:metrics",
    "base-execution-evm/metrics",
]
