[package]
name = "base-execution-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A payload builder for base-reth that builds Base payloads."

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
alloy-rlp = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
serde_json = { workspace = true }
reth-tasks = { workspace = true }
base-state = { workspace = true }
base-metrics = { workspace = true }
base-bundles = { workspace = true }
futures-util = { workspace = true }
reth-metrics = { workspace = true }
base-protocol = { workspace = true }
alloy-hardforks = { workspace = true }
base-common-evm = { workspace = true }
base-evm-handler = { workspace = true }
base-evm-context = { workspace = true }
reth-chain-state = { workspace = true }

reth-payload-util = { workspace = true }
reth-execution-cache = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-eip8130 = { workspace = true }
base-execution-chainspec = { workspace = true }
moka = { workspace = true, features = ["sync"] }
metrics = { workspace = true, optional = false }
base-observability-events = { workspace = true }
derive_more = { workspace = true, features = ["full"]}
tracing = { workspace = true, features = ["attributes"]}
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream = { workspace = true, features = ["default"] }
futures-core = { workspace = true, features = ["default"] }
reth-storage-api = { workspace = true, features = ["default"] }
reth-trie-common = { workspace = true, features = ["default"] }
reth-engine-primitives = { workspace = true, features = ["std"] }
base-common-consensus = { workspace = true, features = ["reth"] }
base-common-chains = { workspace = true, features = ["default"] }
base-execution-trie = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"]}
base-execution-consensus = { workspace = true, features = ["std"] }
reth-execution-types = { workspace = true, features = ["default"] }
base-execution-txpool = { workspace = true, features = ["default"] }
base-execution-payload-types = { workspace = true, features = ["default"] }
base-execution-evm = { workspace = true, features = ["default", "witness"] }
base-common-rpc-types-engine = {workspace = true, features = ["serde", "std"]}
[dev-dependencies]
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
reth-provider = { workspace = true, features = ["test-utils"] }
base-execution-chainspec = { workspace = true, features = ["default"] }
base-observability-events = { workspace = true, features = ["test-utils"] }
base-execution-evm = { workspace = true, features = ["default", "test-utils"] }

[features]
default = ["metrics"]
metrics = [
    "base-common-evm/metrics",
    "base-metrics/metrics",
    "base-observability-events/metrics",
    "base-execution-evm/metrics",
]
test-utils = [
    "reth-chain-state/test-utils",
    "reth-primitives-traits/test-utils",
    "tokio/rt",
    "reth-execution-cache/test-utils",
    "base-execution-trie/test-utils",
]
