[package]
name = "base-execution-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A payload builder for base-reth that builds Base payloads."

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
metrics = { workspace = true  }
alloy-rlp = { workspace = true }
thiserror = { workspace = true }
alloy-eips = { workspace = true }
base-state = { workspace = true }
reth-tasks = { workspace = true }
serde_json = { workspace = true }
base-bundles = { workspace = true }
base-metrics = { workspace = true }
futures-util = { workspace = true }
reth-metrics = { workspace = true }
base-protocol = { workspace = true }
alloy-hardforks = { workspace = true }
base-evm-context = { workspace = true }
reth-chain-state = { workspace = true }
reth-payload-util = { workspace = true }
reth-execution-cache = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
base-execution-eip8130 = { workspace = true }
reth-primitives-traits = { workspace = true }
base-execution-evm-runtime = {workspace = true}
base-observability-events = { workspace = true }
moka = { workspace = true, features = ["sync"] }
derive_more = { workspace = true, features = ["full"]}
tracing = { workspace = true, features = ["attributes"]}
tokio = { workspace = true, features = ["sync", "time"] }
futures-core = { workspace = true, features = ["default"] }
tokio-stream = { workspace = true, features = ["default"] }
reth-storage-api = { workspace = true, features = ["default"] }
reth-trie-common = { workspace = true, features = ["default"] }
reth-engine-primitives = { workspace = true, features = ["std"] }
base-execution-trie = { workspace = true, features = ["default"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"]}
base-common-types-chain = { workspace = true, features = ["reth"] }
reth-execution-types = { workspace = true, features = ["default"] }
base-execution-txpool = { workspace = true, features = ["default"] }
base-common-chain-config = {features = ["default"], workspace = true}
base-common-types-payload = {workspace = true, features = ["serde", "std"]}
base-execution-payload-types = { workspace = true, features = ["default"] }
base-execution-evm-blocks = {features = ["default", "std", "witness"], workspace = true}

[dev-dependencies]
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
reth-provider = { workspace = true, features = ["test-utils"] }
base-common-chain-config = { workspace = true, features = ["std"] }
base-observability-events = { workspace = true, features = ["test-utils"] }
base-execution-evm-blocks = { workspace = true, features = ["default", "test-utils"] }

[features]
default = ["metrics"]
metrics = [
    "base-execution-evm-runtime/metrics",
    "base-metrics/metrics",
    "base-observability-events/metrics",
    "base-execution-evm-blocks/metrics",
]
test-utils = [
    "reth-chain-state/test-utils",
    "reth-primitives-traits/test-utils",
    "tokio/rt",
    "reth-execution-cache/test-utils",
    "base-execution-trie/test-utils",
]
