[package]
name = "base-node-context"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Shared Base node components and launch context."

[lints]
workspace = true

[dependencies]
reth-network = { workspace = true }
reth-provider = { workspace = true }
reth-node-core = { workspace = true }
base-execution-txpool = { workspace = true }
reth-engine-primitives = { workspace = true }
base-common-runtime-tasks = {workspace = true}
base-execution-evm-blocks = {workspace = true}
base-execution-payload-builder = { workspace = true }
